google/clspv

deps.json

Tested with RelWithDebugInfo and Debug builds on Linux.

Update to top-of-tree LLVM and Clang

---

utils/fetch_sources.py

In addition to the current Python 2 compatibility.

Make utils/fetch_sources.py compatible with Python 3

---

lib/SPIRVProducerPass.cpp
test/nop.cl

Do this so we can use StorageBuffer storage class
Fixes https://github.com/google/clspv/issues/21

Declare SPV_KHR_storage_buffer_storage_class extension

---

lib/SPIRVProducerPass.cpp

Avoid polluting the main ValueMap until we actually
generate the SPIR-V constants.  It's less confusing
this way, and matches how we track and generate types.

Use separate UniqueVector to track constants

---

lib/SPIRVProducerPass.cpp
test/char4_insert.cl

Fixes https://github.com/google/clspv/issues/48

Fix truncation of i32 to i8

---

deps.json

Pick up fix for SPIRV-Tools issue 782

Refresh SPIRV-Tools dependency

---

deps.json

Pick up first SPIRV-Tools v2017.1-dev commits

Update SPIRV-Tools and SPIRV-Headers

---

lib/SPIRVProducerPass.cpp
test/uchar4_extract_to_float.cl

Fixes https://github.com/google/clspv/issues/55

Fix extraction of uchar4 components

---

CONTRIBUTING.md

Also include updated links to both CLA sites.

Clarify corporate vs. personal CLA

---

tools/driver/main.cpp

Fixes https://github.com/google/clspv/issues/3

Write output files only if compilaion succeeds

---

lib/SPIRVProducerPass.cpp
test/MathBuiltins/float2_fmod.cl
test/MathBuiltins/float3_fmod.cl
test/MathBuiltins/float4_fmod.cl
test/MathBuiltins/float_fmod.cl

Fixes https://github.com/google/clspv/issues/79

Support fmod in scalar and vector forms

---

test/MathBuiltins/float2_fmod.cl
test/MathBuiltins/float3_fmod.cl
test/MathBuiltins/float4_fmod.cl
test/MathBuiltins/float_fmod.cl
test/spvasm2checks.pl

Fix spvasm2checks so it actually matches

---

lib/SPIRVProducerPass.cpp
test/MathBuiltins/float2_acospi.cl
test/MathBuiltins/float2_asinpi.cl
test/MathBuiltins/float2_atan2pi.cl
test/MathBuiltins/float3_acospi.cl
test/MathBuiltins/float3_asinpi.cl
test/MathBuiltins/float3_atan2pi.cl
test/MathBuiltins/float4_acospi.cl
test/MathBuiltins/float4_asinpi.cl
test/MathBuiltins/float4_atan2pi.cl
test/MathBuiltins/float_acospi.cl
test/MathBuiltins/float_asinpi.cl
test/MathBuiltins/float_atan2pi.cl

Fixes https://github.com/google/clspv/issues/84
Fixes https://github.com/google/clspv/issues/85
Fixes https://github.com/google/clspv/issues/86

Support atan2pi, acos2pi, atan2pi

---

lib/ReplaceOpenCLBuiltinPass.cpp
lib/SPIRVProducerPass.cpp
test/MathBuiltins/float2_fract_private.cl
test/MathBuiltins/float3_fract_private.cl
test/MathBuiltins/float4_fract_private.cl
test/MathBuiltins/float_fract_private.cl

The tests have to workaround the disassembler rounding up the nearly-1
value up to 1.0

Support fract, with pointer-to-private variants

---

lib/ReplaceLLVMIntrinsicsPass.cpp
test/LLVMIntrinsics/memset_null_many_copies.cl

Fixes https://github.com/google/clspv/issues/94

Fix memset of null value spanning multiple pointee locations

---

lib/ClusterPodKernelArgumentsPass.cpp
test/cluster_pod_args_reuse_pod_type.cl

Fixes https://github.com/google/clspv/issues/104

Cluster-pod-args: Reuse struct types

---

lib/SPIRVProducerPass.cpp
test/ImageBuiltins/get_image_height_image2d_readonly.cl
test/ImageBuiltins/get_image_height_image2d_writeonly.cl
test/ImageBuiltins/get_image_width_imaged2d_readonly.cl
test/ImageBuiltins/get_image_width_imaged2d_writeonly.cl

Supports both read_only and write_only images.
Partially addresses https://github.com/google/clspv/issues/122

Support get_image_width get_image_height on 2D

---

lib/SPIRVProducerPass.cpp

Also Remove dead variable nextSpecID

Simplify code, mostly use SPIRVOperand shift operator

---

lib/SPIRVProducerPass.cpp

Remove instruction constructor that takes a word count

Cleanup: SPIRVInstruction constructor counts its own words

---

include/clspv/Passes.h
lib/CMakeLists.txt
lib/InlineFuncWithPointerToFunctionArgPass.cpp
test/ptr_function_as_return.cl
test/ptr_function_in_callee.cl
tools/driver/main.cpp

Inline a function if its return value or any argument is
a pointer to the Function storage class.  This avoids many
cases of OpPtrAccessChain on Function storage class.
Fixes https://github.com/google/clspv/issues/135

Inline functions with ptr to Function storage class

---

tools/driver/main.cpp

Pointer-to-void tends to turn into pointer-to-char, which trips up
some things.

User error if pointer-to-void is used

---

cmake/strip_banned_opencl_features.cmakescript
docs/OpenCLCOnVulkan.md
lib/ReplaceOpenCLBuiltinPass.cpp
test/HalfStorage/clspv_vloada_half2_global.cl
test/HalfStorage/clspv_vloada_half2_local.cl
test/HalfStorage/clspv_vloada_half2_private.cl
test/HalfStorage/clspv_vloada_half4_global.cl
test/HalfStorage/clspv_vloada_half4_local.cl
test/HalfStorage/clspv_vloada_half4_private.cl

Works on global, local, and private pointers.

Add __clspv_vloada_half4, __clspv_vloada_half2

---

docs/OpenCLCOnVulkan.md
lib/ReplaceOpenCLBuiltinPass.cpp
test/HalfStorage/vloada_half2_global.cl
test/HalfStorage/vloada_half4_global.cl

It has support for global and constant address spaces.

Support vloada_half2 and vloada_half4

---

deps.json

Passes on Release and Debug builds

Update SPIRV-Tools and SPRIV-Headers to latest

---

deps.json

Includes -combine-access-chain

Update known-good SPIRV-Tools

---

lib/ClusterConstants.cpp
lib/DefineOpenCLWorkItemBuiltinsPass.cpp
lib/FunctionInternalizerPass.cpp
lib/HideConstantLoadsPass.cpp
lib/InlineFuncWithPointerBitCastArgPass.cpp
lib/OpenCLInlinerPass.cpp
lib/Option.cpp
lib/ReorderBasicBlocksPass.cpp
lib/ReplaceOpenCLBuiltinPass.cpp
lib/ReplacePointerBitcastPass.cpp
lib/RewriteInsertsPass.cpp
lib/SPIRVProducerPass.cpp
lib/SplatArgPass.cpp
lib/SplatSelectCondition.cpp
lib/UndoBoolPass.cpp
lib/UndoByvalPass.cpp
lib/UndoGetElementPtrConstantExprPass.cpp
lib/UndoSRetPass.cpp
lib/UndoTranslateSamplerFoldPass.cpp
lib/UndoTruncatedSwitchConditionPass.cpp

Also sort some of the header includes

Avoid system include syntax for llvm/ and clspv/

---

docs/OpenCLCOnVulkan.md

Fix typo in documentation

---

docs/OpenCLCOnVulkan.md

Document more missing built-in functions

---

lib/SPIRVProducerPass.cpp
test/MathBuiltins/float2_fma.cl
test/MathBuiltins/float3_fma.cl
test/MathBuiltins/float4_fma.cl
test/MathBuiltins/float_fma.cl

Passes the OpenCL conformance tests run via clvk on NVidia
hardware.

Add support for the fma built-in

---

lib/ReplaceOpenCLBuiltinPass.cpp
test/AtomicBuiltins/atom_add_int.cl
test/AtomicBuiltins/atom_add_uint.cl
test/AtomicBuiltins/atom_and_int.cl
test/AtomicBuiltins/atom_and_uint.cl
test/AtomicBuiltins/atom_cmpxchg_int.cl
test/AtomicBuiltins/atom_cmpxchg_uint.cl
test/AtomicBuiltins/atom_dec_int.cl
test/AtomicBuiltins/atom_dec_uint.cl
test/AtomicBuiltins/atom_inc_int.cl
test/AtomicBuiltins/atom_inc_uint.cl
test/AtomicBuiltins/atom_max_int.cl
test/AtomicBuiltins/atom_max_uint.cl
test/AtomicBuiltins/atom_min_int.cl
test/AtomicBuiltins/atom_min_uint.cl
test/AtomicBuiltins/atom_or_int.cl
test/AtomicBuiltins/atom_or_uint.cl
test/AtomicBuiltins/atom_sub_int.cl
test/AtomicBuiltins/atom_sub_uint.cl
test/AtomicBuiltins/atom_xchg_int.cl
test/AtomicBuiltins/atom_xchg_uint.cl
test/AtomicBuiltins/atom_xor_int.cl
test/AtomicBuiltins/atom_xor_uint.cl

All these pass the OpenCL conformance tests run via clvk on
NVidia hardware.

Support global atom_* atomic functions for 32-bit integer types

---

utils/make_test.py

Add copyright header to utils/make_test.py

---

lib/SPIRVProducerPass.cpp

Contributes to #238.
Fix MSVC 2017 build (and clang formatting). I tested this using the latest 2017 build (19.15.26732.1).
@pscoe2 can you try this and see if it fixes your issue?

Fix windows build

---

.gitignore
include/clspv/Compiler.h
lib/CMakeLists.txt
lib/Compiler.cpp
lib/FrontendPlugin.cpp
lib/FrontendPlugin.h
tools/driver/CMakeLists.txt

* Moved driver functionality into lib/
* split frontend plugin into a separate file
* split driver functionality into multiple functions
Doing this in preparation for adding a library interface for clspv.

Refactor the driver.

---

lib/UBOTypeTransformPass.cpp
test/UBO/constant_and_image.cl

* Don't map opaque structs
* They never need rewritten
* Added a test

Fix opaque struct type mapping

---

docs/OpenCLCOnVulkan.md
lib/ReplaceOpenCLBuiltinPass.cpp
test/IntegerBuiltins/rotate/rotate_uint.cl
test/IntegerBuiltins/rotate/rotate_uint2.cl
test/IntegerBuiltins/rotate/rotate_uint3.cl
test/IntegerBuiltins/rotate/rotate_uint4.cl
test/IntegerBuiltins/rotate/rotate_ulong.cl
test/IntegerBuiltins/rotate/rotate_ulong2.cl
test/IntegerBuiltins/rotate/rotate_ulong3.cl
test/IntegerBuiltins/rotate/rotate_ulong4.cl
test/IntegerBuiltins/rotate/rotate_ushort.cl
test/IntegerBuiltins/rotate/rotate_ushort2.cl
test/IntegerBuiltins/rotate/rotate_ushort3.cl
test/IntegerBuiltins/rotate/rotate_ushort4.cl

Add support for the rotate built-in function

---

deps.json
lib/SPIRVProducerPass.cpp
test/DirectResourceAccess/ro_image2_sampler_args.cl
test/DirectResourceAccess/ro_image3_sampler_args.cl
test/ImageBuiltins/get_image_height_image2d_readonly.cl
test/ImageBuiltins/get_image_width_imaged2d_readonly.cl
test/ImageBuiltins/read_imagef_sampler_float2.cl
test/ImageBuiltins/read_imagef_sampler_float4.cl
test/ImageBuiltins/read_only_image2d_passed_to_other_function.cl
test/ImageBuiltins/read_only_image3d_passed_to_other_function.cl
test/ProgramScopeConstants/constant_array_with_function_call.cl
test/SamplerMap/KernelScopeSampler.cl
test/SamplerMap/ModuleScopeSampler.cl
test/SamplerMap/TwoModuleScopeSamplers.cl
test/UBO/constant_and_image.cl
test/hack_undef_image.cl
test/image2d.cl
test/image2d_read.cl
test/image3d.cl
test/image3d_read.cl

* Validator catches some errors with unit tests now
* no longer generate NonWritable for read_only images since we generate
them as sampled
* have some tests expect to fail validation

Update SPIRV-Tools and SPIRV-Headers deps

---

CMakeLists.txt

Support building out-of-tree SPIRV-{Headers,Tools}

---

utils/make_test.py

This helps with producing smaller test cases in an automated
fashion.

Add an option to make_test.py to remove groups of instructions

---

lib/FrontendPlugin.cpp
test/UBO/bad_ssbo_scalar.cl
test/UBO/bad_ssbo_vec2.cl
test/UBO/bad_ssbo_vec4.cl

* Introduced layout enum
* currently supports UBO and SSBO standard layouts
* updated checks to share most code
* updated some diagnostic messages

Perform layout checks for global buffers

---

lib/SPIRVProducerPass.cpp

The end goal is to provide a generic mechanism that makes
it easy to directly generate a specific instruction in
other passes.
This change only covers the trivial cases.

Unify handling of most SPIR-V intrinsics in the producer pass

---

docs/OpenCLCOnVulkan.md
lib/ReplaceOpenCLBuiltinPass.cpp
test/MathBuiltins/copysign/copysign_float.cl
test/MathBuiltins/copysign/copysign_float2.cl
test/MathBuiltins/copysign/copysign_float3.cl
test/MathBuiltins/copysign/copysign_float4.cl

Passes the relevant conformance tests.
Closes #287.

Add support for the copysign built-in function

---

lib/SPIRVProducerPass.cpp
test/issue-311.cl

Includes a cut-down version of the failing code reported in
#311.
Fixes #311.

Fix replacement of multiple spirv.store_null calls

---

test/issue-311.cl

I merged a change that needed rebased. This fixes the test.

Fix test using -S

---

lib/Compiler.cpp

Add a ParseOptions function to handle common steps

---

docs/OpenCLCOnVulkan.md
lib/Option.cpp
test/Int8/int8_default.cl
test/ProgramScopeConstants/in_storage_buffer_descriptor_map.cl
test/Structs/insert_value_issue_14.cl
test/UBO/array_stride_32.cl
test/UBO/constant_wrapping.cl
test/UBO/global_wrapping.cl
test/UBO/max_ubo_size.cl
test/UBO/nested_padding.cl
test/UBO/transform_global.cl
test/UBO/transform_local.cl
test/UBO/transform_padding.cl
test/char4_constant.cl
test/char4_constant_zero.cl
test/char4_insert.cl
test/char4_insert_from_float.cl
test/char4_issue15_a.cl
test/char4_issue15_b.cl
test/uchar4_extract_to_float.cl
test/uchar4_insert_from_float.cl

Fixes #296
* Flip -int8 to be on by default
* Update some tests to disable it
* Add a test for the default

Make char support default on

---

lib/AllocateDescriptorsPass.cpp
lib/Constants.h
lib/SPIRVProducerPass.cpp

Add a symbolic name for clspv.sampler.var.literal

---

lib/ReplaceOpenCLBuiltinPass.cpp

Separate the replacement logic from the code that generates
the replacement value to remove duplicate code.

Simplify replacement of built-in functions from a list of names

---

kokoro/check-format/build.sh
kokoro/check-format/continuous.cfg
kokoro/check-format/presubmit_check_format.cfg
utils/check_code_format.sh

Contributes to #344
* Adds the github-side of the bot configurations

Add code format configurations

---

lib/ReplaceLLVMIntrinsicsPass.cpp
test/LLVMIntrinsics/memset_stray_bitcast.ll

Cleanup unused bitcasts after ReplaceLLVMIntrinsics

---

lib/ClusterPodKernelArgumentsPass.cpp
lib/FrontendPlugin.cpp
lib/SPIRVProducerPass.cpp
lib/UBOTypeTransformPass.cpp
lib/UndoByvalPass.cpp
lib/UndoSRetPass.cpp
test/UBO/bad_pod_ubo.cl
test/UBO/clustered_pod_type_mutate.cl
test/UBO/clustered_pod_ubo.cl

Fixes #218
* Add frontend check for pod ubo arguments
* update clustering to generate valid layouts by inserting padding
* mutate pod arg types in UBO type transform
* tests
* Propagate argument names in UndoByvalPass and UndoSRetPass
* previously some arguments would not maintain their names

Pod ubo layout

---

lib/ReplaceOpenCLBuiltinPass.cpp
test/CommonBuiltins/no_duplicate_barrier.cl
test/CommonBuiltins/no_duplicate_barrier.ll

Fixes #365
* Set the noduplicate attribute on barriers
* add tests

Do not allow barriers to be duplicated

---

lib/FrontendPlugin.cpp
test/Structs/mutual_recursion_error.cl
test/Structs/nested_pointer_error.cl
test/Structs/nested_pointer_error2.cl

Fixes #376
* Add a frontend diagnostic if a structure contains a pointer
* tests

Add an error for pointers in structs

---

include/clspv/Passes.h
lib/Compiler.cpp
lib/SPIRVProducerPass.cpp

Fixes #265
* Remove code to support assembly generation
* Option to output assempbly was previously removed

Remove assembly generation code

---

lib/ReplaceOpenCLBuiltinPass.cpp
lib/SPIRVOp.cpp
lib/SPIRVProducerPass.cpp
test/RelationalBuiltins/all/all_overloads.ll
test/RelationalBuiltins/any/any_overloads.ll
test/RelationalBuiltins/isinf_overloads.ll
test/RelationalBuiltins/isnan_overloads.ll

Use InsertSPIRVOp to create calls to relational SPIR-V intrinsics

---

lib/ReplaceOpenCLBuiltinPass.cpp
lib/SPIRVProducerPass.cpp

Move dot built-in function replacement out of the producer pass

---

lib/SPIRVProducerPass.cpp

Remove unused GetI32Zero function

---

lib/ReplaceLLVMIntrinsicsPass.cpp
lib/SPIRVProducerPass.cpp

Use store instructions instead of spirv.store_null intrinsic

---

cmake/spirv_c_strings.py
lib/Constants.h

Missing includes for standalone compiles.

Build fixes for pre-compiled headers

---

lib/MultiVersionUBOFunctionsPass.cpp

Modified the list as it was iterated over previously.

Fix user iteration

---

cmake/CMakeLists.txt

Fixes #406
* Force generation of the include file directory

Ensure generated files directory is created

---

CMakeLists.txt
deps.json
kokoro/scripts/linux/build.sh

* Remove clang from deps.json
* Switch LLVM in deps.json to LLVM monorepo
* Update CMakeLists.txt for new setup

Switch to use the LLVM monorepo

---

utils/make_test.py

Fix make_test.py for Python 3

---

lib/ReplaceOpenCLBuiltinPass.cpp
test/MathBuiltins/isfinite/isfinite_double.ll
test/MathBuiltins/isfinite/isfinite_double2.ll
test/MathBuiltins/isfinite/isfinite_double3.ll
test/MathBuiltins/isfinite/isfinite_double4.ll
test/MathBuiltins/isfinite/isfinite_float.ll
test/MathBuiltins/isfinite/isfinite_float2.ll
test/MathBuiltins/isfinite/isfinite_float3.ll
test/MathBuiltins/isfinite/isfinite_float4.ll
test/MathBuiltins/isfinite/isfinite_half.ll
test/MathBuiltins/isfinite/isfinite_half2.ll
test/MathBuiltins/isfinite/isfinite_half3.ll
test/MathBuiltins/isfinite/isfinite_half4.ll

Add support for the isfinite built-in function

---

deps.json
lib/DirectResourceAccessPass.cpp
lib/ShareModuleScopeVariables.cpp
lib/SignedCompareFixupPass.cpp

Update LLVM dep

---

lib/SPIRVProducerPass.cpp
test/fnegate.cl

Fixes #440
* Add support to generate OpFNegate
* Add a test

Support fnegate

---

lib/SPIRVProducerPass.cpp

Fixes #442
* Add a new unique vector that tracks image types
* iterate through this vector instead of the image type map so that
OpTypeSampledImage instructions are generated deterministically
Note: no tests for this, since the behaviour was non-deterministic previously.

Generate OpTypeSampledImage deterministically

---

kokoro/clvk-linux-clang-debug/build.sh
kokoro/clvk-linux-clang-debug/continuous.cfg
kokoro/clvk-linux-clang-debug/presubmit.cfg
kokoro/scripts/linux/build-clvk.sh

Will populate script once bot is in place (so it can be tested properly before landing). Also waiting for one more Clvk change to land.

Add empty script for clvk bot

---

kokoro/amber-linux-gcc-release/build.sh
kokoro/amber-linux-gcc-release/continuous.cfg
kokoro/amber-linux-gcc-release/presubmit.cfg

Add infrastructure to create a Kokoro bot that runs amber tests.

Dummy scripts for amber bot

---

docs/OpenCLCOnVulkan.md
lib/Builtins.cpp
lib/ReplaceOpenCLBuiltinPass.cpp
lib/SPIRVProducerPass.cpp
lib/Types.cpp
test/ImageBuiltins/get_image_width_image1d_readonly.cl
test/ImageBuiltins/get_image_width_image1d_writeonly.cl
test/ImageBuiltins/image_1d_capability.cl
test/ImageBuiltins/read_imagef_sampler_float.cl
test/ImageBuiltins/read_imagei_sampler_float.cl
test/ImageBuiltins/read_imageui_sampler_float.cl
test/ImageBuiltins/sampled_1d_capability.cl
test/ImageBuiltins/sampled_1d_read_image_with_int_coord.ll
test/ImageBuiltins/write_imagef_int.cl
test/ImageBuiltins/write_imagei_int.cl
test/ImageBuiltins/write_imageui_int.cl
test/SpecializeImageTypes/image1d_float_get_image_width.ll
test/SpecializeImageTypes/image1d_float_sampled_get_image_width.ll
test/SpecializeImageTypes/read_image1d_float.ll
test/SpecializeImageTypes/read_image1d_int.ll
test/SpecializeImageTypes/read_image1d_uint.ll
test/SpecializeImageTypes/write_image1d_float.ll
test/SpecializeImageTypes/write_image1d_int.ll
test/SpecializeImageTypes/write_image1d_uint.ll

Fixes #454
* Add support for 1D (non-arrayed) images
* sampled read (int and float coord)
* write
* get_image_width
* tests

Support 1D images

---

amber/run_tests.py
kokoro/amber-linux-gcc-release/build.sh
kokoro/scripts/linux/build-amber.sh

* Checkout and build amber against this clspv
* Run amber tests using swiftshader

Add Amber bot functionality

---

cmake/strip_banned_opencl_features.py
lib/ReplaceOpenCLBuiltinPass.cpp
test/CommonBuiltins/work_group_barrier.cl

* Support the work_group_barrier(cl_mem_fence_flags) version
* not the cl_memory_scope version
* Add a test

Allow the work_group_barrier alias for barrier

---

lib/SPIRVProducerPass.cpp

- Return std::shared_ptr from the Mk*() helpers
- Destroy SPIRVInstruction objects when SPIRVProducerPass is destroyed

Fix memory leaks in SPIRVProducerPass

---

lib/SPIRVProducerPass.cpp
test/half-constants.cl

* Add the ability to generate half float constants
* New test

Half float literal support

---

lib/UndoTruncatedSwitchConditionPass.cpp
test/widen_switch_condition_binary_ops.ll

Handle some basic binary operators when undo switch condition truncation.
Fixes #482

Truncate switch

---

include/clspv/DescriptorMap.h
lib/DescriptorMap.cpp

These are also needed by clients.

Add sampler component masks to DescriptorMap.h

---

kokoro/scripts/linux/build-amber.sh
kokoro/scripts/linux/build-clvk.sh
kokoro/scripts/linux/build.sh

Upgrade the GCC used in for Linux Kokoro bots

---

utils/fetch_sources.py

Use the most basic Python code to make a file system path.

Avoid Python distutils.dir_util

---

docs/OpenCLCOnVulkan.md
include/clspv/PushConstant.h
lib/DeclarePushConstantsPass.cpp
lib/DefineOpenCLWorkItemBuiltinsPass.cpp
lib/PushConstant.cpp
test/WorkItemBuiltins/get_enqueued_local_size.cl

Start implementing support for non-uniform NDRanges, following the approach outlined in #522 

Add support for get_enqueued_local_size()

---

lib/ReplaceOpenCLBuiltinPass.cpp
lib/SPIRVOp.cpp
test/GeometricBuiltins/half2_dot.cl
test/GeometricBuiltins/half3_dot.cl
test/GeometricBuiltins/half4_dot.cl
test/GeometricBuiltins/half_dot.cl

* Add support for half variants of dot
* Add new tests

Support half variants of dot

---

lib/DeclarePushConstantsPass.cpp
lib/DefineOpenCLWorkItemBuiltinsPass.cpp
test/WorkItemBuiltins/via-push-constant-enabled-but-not-used.cl

Only declare push constants when they will be used

---

lib/Builtins.cpp

* Fix missing parenthesis warning in Builtins.cpp

Fix warnings

---

lib/ReplacePointerBitcastPass.cpp
test/PointerCasts/issue-551.ll

... when the destination type's width is not 32-bit.
Fixes #551

Fix a pointer bitcast replacement with load user case

---

lib/UndoInstCombinePass.cpp
test/UndoInstCombine/extract_load_cast.cl
test/UndoInstCombine/extract_load_cast_3xi32_to_6xi16.ll
test/UndoInstCombine/extract_load_cast_inst_3xi32_to_6x16.ll
test/UndoInstCombine/undo_shuffle_load_cast_3xi32_to_6xi16.ll

* Handle casts of pointer to vectors that get loaded
* More tests

Handle more instcombine vector casts

---

include/clspv/Passes.h
lib/CMakeLists.txt
lib/Compiler.cpp
lib/Passes.cpp
lib/Passes.h
lib/StripFreezePass.cpp
test/StripFreeze/strip_chain_freeze.ll
test/StripFreeze/strip_multiple_uses.ll
test/StripFreeze/strip_single_freeze.ll

Fixes #558
* Simple pass run before most clspv passes to strip freezes
* Add tests

Add a pass to strip freeze instructions

---

utils/fetch_sources.py

Add support for shallow clones to fetch_sources.py

---

lib/SPIRVProducerPass.cpp

* cache current Module
Related to issue google#545

SPIRVProducerPass refactor - phase1.1

---

docs/OpenCLCOnVulkan.md

Fixes #520
* Samplers no longer require a sampler map

Remove sampler restrictions

---

lib/SPIRVProducerPass.cpp
test/Reflection/different_reqd_work_group_sizes.cl
test/Reflection/mixed_reqd_workgroup_sizes.cl
test/different_reqd_work_group_sizes.cl
test/mixed_reqd_work_group_sizes.cl

Fixes #629
* Generate WorkgroupSize builtin if not all kernels specify
reqd_work_group_size
* Do not generate LocalSize execution mode if WorkgroupSize builtin is
generated
* new tests

Support mixed reqd_work_group_size attributes

---

docs/OpenCLCOnVulkan.md
lib/ReplaceOpenCLBuiltinPass.cpp
test/RelationalBuiltins/isnormal/isnormal_double.ll
test/RelationalBuiltins/isnormal/isnormal_double2.ll
test/RelationalBuiltins/isnormal/isnormal_float.ll
test/RelationalBuiltins/isnormal/isnormal_float2.ll
test/RelationalBuiltins/isnormal/isnormal_half.ll
test/RelationalBuiltins/isnormal/isnormal_half2.ll

* Implement isnormal via integer comparisons
* lit tests
* update docs
* Passes OpenCL CTS for 32-bit float

Implement isnormal

---

lib/SPIRVProducerPass.cpp
test/bool_to_double_cast.cl
test/bool_to_float_cast.cl
test/bool_to_half_cast.cl

* Use the correct type for constants generated by uitofp i1
* Add tests

Fix casts from bool to half/double

---

lib/SPIRVProducerPass.cpp
test/CommonBuiltins/clamp/float2_clamp.cl
test/CommonBuiltins/clamp/float3_clamp.cl
test/CommonBuiltins/clamp/float4_clamp.cl
test/CommonBuiltins/clamp/float_clamp.cl
test/CommonBuiltins/clamp/half2_clamp.cl
test/CommonBuiltins/clamp/half3_clamp.cl
test/CommonBuiltins/clamp/half4_clamp.cl
test/CommonBuiltins/clamp/half_clamp.cl

Fixes #506
* Floating-point clamps use NClamp instead of Fclamp
* update tests
cc: @mantognini

Change fclamp to nclamp

---

lib/LongVectorLoweringPass.cpp
test/LongVectorLowering/globals.ll

Next feature for #613 is support for global variables. This one should be a bit simpler than previous PR, but comments are always welcome.

Lower global variables

---

lib/ReplaceOpenCLBuiltinPass.cpp
lib/SPIRVProducerPass.cpp
test/MathBuiltins/expm1/expm1_double2.ll
test/MathBuiltins/expm1/expm1_float.ll
test/MathBuiltins/expm1/expm1_float2.ll
test/MathBuiltins/expm1/expm1_half.ll
test/MathBuiltins/log/float2_log1p.ll
test/MathBuiltins/log/float3_log1p.ll
test/MathBuiltins/log/float4_log1p.ll
test/MathBuiltins/log/float_log1p.ll
test/MathBuiltins/pown/pown_double2.ll
test/MathBuiltins/pown/pown_float.ll
test/MathBuiltins/pown/pown_float2.ll
test/MathBuiltins/pown/pown_half.ll
test/MathBuiltins/sincos/sincos_double2.ll
test/MathBuiltins/sincos/sincos_float.ll
test/MathBuiltins/sincos/sincos_float2.ll
test/MathBuiltins/sincos/sincos_half.ll

* Support sincos
* Use llvm.sin and llvm.cos
* Support expm1
* use llvm.exp - 1
* Support pown
* use llvm.pow with fp conversion
* Switch log1p to use llvm.log
* Producer support for llvm.log, llvm.exp and llvm.pow

More math builtin support

---

docs/OpenCLCOnVulkan.md
lib/ReplaceOpenCLBuiltinPass.cpp
test/SynchronizationBuiltins/atomic_work_item_fence.cl

* Update docs
* Code gens to OpMemoryBarrier

Support atomic_work_item_fence

---

deps.json
lib/Compiler.cpp

Update LLVM and remove 3d image write workaround

---

lib/LongVectorLoweringPass.cpp
test/LongVectorLowering/bitcast.ll
test/MathBuiltins/acos/float8_acos.cl
test/MathBuiltins/acos/float8_acosh.cl
test/MathBuiltins/asin/float8_asinh.cl
test/MathBuiltins/atan/float8_atanh.cl
test/MathBuiltins/ceil/float8_ceil.cl
test/MathBuiltins/cos/float8_cos.cl
test/MathBuiltins/exp/float8_exp2.cl
test/MathBuiltins/floor/float8_floor.cl
test/MathBuiltins/isfinite/isfinite_float8.ll
test/MathBuiltins/log/float8_log.cl
test/MathBuiltins/pow/float8_pow.cl
test/MathBuiltins/sin/float8_sin.cl
test/MathBuiltins/sin/float8_sinh.cl
test/MathBuiltins/tan/float8_tan.cl
test/MathBuiltins/tan/float8_tanh.cl
test/MathBuiltins/trunc/float8_trunc.cl

This completes Arm's prototype (#613) with support for some additional builtin functions. Some builtins are still missing and can be added later by any contributor.

Support additional builtin functions

---

lib/Compiler.cpp
test/HalfStorage/vstore_half2_pointer_cast_to_float4.cl
test/one_global_buffer_arg.cl
test/one_uint_arg.cl

Clean up dead code after simplify/replace pointer bitcasts

---

lib/ThreeElementVectorLoweringPass.cpp

* Update for removed CreateGEP and CreateLoad APIs

Fix compile failures

---

lib/LongVectorLoweringPass.cpp
test/LongVectorLowering/clamp.ll
test/LongVectorLowering/degrees.ll
test/LongVectorLowering/min.ll
test/LongVectorLowering/minf.ll
test/LongVectorLowering/radians.ll
test/LongVectorLowering/sign.ll
test/LongVectorLowering/smoothstep.ll
test/LongVectorLowering/step.ll
test/LongVectorLowering/stepf.ll

add missing builtins to pass OpenCL CTS:
clamp
degrees
min
minf
radians
sign
smoothstep
step
stepf

LongVectorLowering: add missing commonfns fcts

---

lib/ThreeElementVectorLoweringPass.cpp
test/phi_novec3.ll

Need more test, but should be enough to fix issue from #795

vec3: implement phi nodes support

---

lib/LongVectorLoweringPass.cpp
lib/ThreeElementVectorLoweringPass.cpp
test/LongVectorLowering/phi.cl
test/LongVectorLowering/phi.ll

Also fixes vec3 phi nodes support
Fix #770

longvector: implement phi nodes support

---

lib/LongVectorLoweringPass.cpp
test/LongVectorLowering/char_struct_ssbo.cl
test/LongVectorLowering/pod_kernel_args.cl
test/LongVectorLowering/struct.cl
test/LongVectorLowering/struct.ll

longvector: add nested types support

---

lib/ReplaceOpenCLBuiltinPass.cpp
lib/SPIRVProducerPass.cpp
lib/Types.cpp
lib/Types.h
test/ImageBuiltins/get_image_width_image1d_buffer_readonly.cl
test/ImageBuiltins/get_image_width_image1d_buffer_readwrite.cl
test/ImageBuiltins/get_image_width_image1d_buffer_writeonly.cl
test/ImageBuiltins/image_1d_buffer.cl
test/ImageBuiltins/image_1d_buffer_capability.cl
test/SpecializeImageTypes/image1d_buffer_float_get_image_width.ll
test/SpecializeImageTypes/read_image1d_buffer_float.ll
test/SpecializeImageTypes/read_image1d_buffer_int.ll
test/SpecializeImageTypes/read_image1d_buffer_uint.ll
test/SpecializeImageTypes/write_image1d_buffer_float.ll
test/SpecializeImageTypes/write_image1d_buffer_int.ll
test/SpecializeImageTypes/write_image1d_buffer_uint.ll

This patch is the complement of ongoing work on clvk side.

Add support for image1d buffer

---

lib/LongVectorLoweringPass.cpp
test/LongVectorLowering/char_struct_ssbo.cl
test/LongVectorLowering/opspirv_struct_return.ll
test/LongVectorLowering/pod_kernel_args.cl
test/LongVectorLowering/struct.cl
test/LongVectorLowering/struct.ll

longvector: support spirvop that return struct

---

include/clspv/Option.h
lib/Option.cpp
lib/SPIRVProducerPass.cpp

Add support for SPIR-V 1.6

---

lib/MultiVersionUBOFunctionsPass.h
lib/ReplaceOpenCLBuiltinPass.h
lib/ReplacePointerBitcastPass.h
lib/RewriteInsertsPass.h
lib/SignedCompareFixupPass.h
lib/UndoGetElementPtrConstantExprPass.h

These came up using a stricter compiler.

Fix some includes in updated passes

---

lib/MultiVersionUBOFunctionsPass.cpp

Remove usage of pointer element type in MultiVersionUBOFunctions

---

docs/OpenCLCOnVulkan.md
include/clspv/Compiler.h
include/clspv/Option.h
lib/AllocateDescriptorsPass.cpp
lib/Compiler.cpp
lib/Option.cpp
lib/SPIRVProducerPass.cpp

* remove remaining uses of the sampler map in the codebase
* update more operand uses to use ClspvOperand

Remove sampler map

---

amber/integer/hadd_uint.amber
amber/integer/rhadd_uint.amber

* Missed updating entry point names in bind statement

Fix amber tests

---

lib/AutoPodArgsPass.cpp

Avoid use-after-move

---

include/clspv/Option.h
lib/Compiler.cpp
lib/Option.cpp
lib/SPIRVProducerPass.cpp
test/debug-information-control-flow.cl
test/debug-information.cl

This is part of the effort to integrate clspv into [compiler explorer](https://github.com/compiler-explorer/compiler-explorer)

Add first support for debug information

---

lib/DefineOpenCLWorkItemBuiltinsPass.cpp
lib/DefineOpenCLWorkItemBuiltinsPass.h
lib/PushConstant.cpp
test/WorkItemBuiltins/get_global_linear.cl
test/WorkItemBuiltins/get_local_linear_id.cl

Here I've added definitions for the OpenCL C 2.0+ builtins get_global_linear_id and get_local_linear_id.

Defined get_global_linear_id and get_local_linear_id

---

deps.json
kokoro/scripts/linux/build.sh
kokoro/scripts/macos/build.sh
kokoro/scripts/windows/build.bat
lib/AddFunctionAttributesPass.cpp
lib/HideConstantLoadsPass.cpp
lib/ReplaceLLVMIntrinsicsPass.cpp
lib/ReplaceOpenCLBuiltinPass.cpp
lib/ReplacePointerBitcastPass.cpp
lib/RewriteInsertsPass.cpp
lib/SPIRVOp.cpp
lib/SPIRVOp.h
lib/SPIRVProducerPass.cpp
test/AddFunctionAttributes/translate_literal_sampler.ll
test/SpecializeImageTypes/image1d_array_float_get_image_width.ll
test/SpecializeImageTypes/image1d_buffer_float_get_image_width.ll
test/SpecializeImageTypes/image1d_float_get_image_width.ll
test/SpecializeImageTypes/image2d_array_float_get_image_height.ll
test/SpecializeImageTypes/image2d_array_float_get_image_width.ll
test/SpecializeImageTypes/image2d_float_get_image_height.ll
test/SpecializeImageTypes/image2d_float_get_image_width.ll
test/Structs/byval.cl
test/Structs/sret.cl
test/explicit_stdin.cl
test/nop.cl
test/reqd_work_group_size-non-uniform.cl
test/reqd_work_group_size.cl

* Update LLVM
* switch uses of removed function attributes to memory effects
* Fix tests broken by #936
* fixes sizes in replace pointer bitcasts
* Update bots to run check-spirv-64

Updates and fixes

---

lib/SPIRVProducerPass.cpp
lib/Types.h
test/PushConstant/add_to_interface.ll

Fixes #947
* Add missing include
* Add push constant variable to 1.4+ interface always

Ensure push constant variable is added to 1.4+ interface

---

README.md

kpet has added a clspv channel in clvk server.
Let's communication about it by adding a badge to clvk discord server here.

add discord badge in README

---

lib/ReplacePointerBitcastPass.cpp
test/PointerCasts/opaque_cast_and_no_cast.ll

* Do not transform users that are not implicit casts

Don't transform non-implicit casts

---

lib/BuiltinsEnum.h
lib/BuiltinsMap.inc
lib/MemFence.h
lib/ReplaceOpenCLBuiltinPass.cpp
lib/ReplaceOpenCLBuiltinPass.h
test/AddressSpaceQualifierBuiltins/get_fence.cl

This fixes CTS tests: 
generic_variable_const
generic_ptr_to_host_mem
This contribution is being made by Codeplay on behalf of Samsung

Replace get_fence builtin

---

deps.json
lib/SPIRVProducerPass.cpp
test/KernelArgInfo/kernel-arg-info.cl
test/PhysicalStorageBuffers/physical_global_exclude_image.cl
test/PhysicalStorageBuffers/physical_global_pointer_args.cl
test/PhysicalStorageBuffers/physical_global_ptrtoint.cl
test/Reflection/constant_data_storage_buffer.cl
test/Reflection/different_reqd_work_group_sizes.cl
test/Reflection/global_offset_spec_constant.cl
test/Reflection/global_push_constants.cl
test/Reflection/global_size_and_work_dim.cl
test/Reflection/literal_sampler.cl
test/Reflection/mixed_reqd_workgroup_sizes.cl
test/Reflection/multiple_arguments.cl
test/Reflection/multiple_kernel_decls.cl
test/Reflection/pod_push_constant_argument.cl
test/Reflection/pod_storage_buffer_argument.cl
test/Reflection/pod_uniform_buffer_argument.cl
test/Reflection/property_required_workgroup_size.cl
test/Reflection/readwrite_image_argument.cl
test/Reflection/sampled_image_argument.cl
test/Reflection/sampler_argument.cl
test/Reflection/storage_buffer_argument.cl
test/Reflection/storage_image_argument.cl
test/Reflection/uniform_buffer_argument.cl
test/Reflection/work_dim_spec_constant.cl
test/Reflection/workgroup_argument.cl
test/Reflection/workgroup_size_spec_constant.cl
test/SubGroup/get_sub_group_max_size.cl

We're already using instructions from version 3.

Bump version of non-semantic instruction set to 4

---

lib/LogicalPointerToIntPass.cpp
lib/SPIRVProducerPass.cpp
test/SPIRVProducer/num_args.cl

Generate the NumArguments kernel reflection operand

---

deps.json
lib/FixupStructuredCFGPass.cpp
lib/FixupStructuredCFGPass.h

* Split conditional loop headers when both edges enter the body of the loop

Fix structured loops

---

test/LongVectorLowering/opaque_constgep.ll

opaque_constgep.ll is passing, enable it

---

lib/Types.cpp
test/AllocateDescriptors/atomic_spirv_op.ll

add missing atomic operation in InferType

---

lib/LongVectorLoweringPass.cpp
lib/SpecializeImageTypes.cpp

* Remove some debug output
* Followup to #1035

Support TargetExtType in long vector lowering

---

lib/LongVectorLoweringPass.cpp
test/LongVectorLowering/ptrtoint.ll

fix longvector lowering pass with ptr/int cast

---

lib/Types.cpp
test/int_arg-info.cl

clvk/api_tests is failing compiling the test added by this PR.

fix InferType for non pointer argument

---

lib/SPIRVProducerPass.cpp
test/issue-1074.ll

implement bitreverse intrinsic

---

lib/AllocateDescriptorsPass.cpp
lib/ArgKind.cpp
lib/BitcastUtils.cpp
lib/Builtins.cpp
lib/LongVectorLoweringPass.cpp
lib/NormalizeGlobalVariable.cpp
lib/ReplaceLLVMIntrinsicsPass.cpp
lib/ReplaceOpenCLBuiltinPass.cpp
lib/ReplacePointerBitcastPass.cpp
lib/RewritePackedStructs.cpp
lib/RewritePackedStructs.h
lib/SimplifyPointerBitcastPass.cpp
lib/SimplifyPointerBitcastPass.h
lib/ThreeElementVectorLoweringPass.cpp
lib/Types.cpp
lib/UBOTypeTransformPass.cpp
lib/UndoInstCombinePass.cpp
test/PushConstant/cluster_global_pod_args-arrays.ll
test/PushConstant/cluster_global_pod_args-short_array.ll
test/PushConstant/cluster_global_pod_args-structs.ll
test/PushConstant/cluster_global_pod_args-vectors.ll
test/Spv1p4/interface_global_push_constant.ll
test/Spv1p4/interface_private_builtin.ll

Option.cpp and SPIRVProducerPass.cpp are still to be cleaned
Ref #816

clean transparent pointers

---

lib/SimplifyPointerBitcastPass.cpp
test/PointerCasts/fake_cast.ll
test/PointerCasts/issue-1032.cl

fix runOnGEPImplicitCasts by using helpers from bitcastutils

---

lib/ShareModuleScopeVariables.cpp
test/ShareModuleScopeVariables/no_sharing.ll

we used to compare ptr with ptr, which is almost always true (only address space can differ).

fix sharemodulescopevariables

---

cmake/util.cmake

clspv_combine_static_lib is taking over 4min on my machine. This is due to the recursive call to clspv_get_transitive_libs which is called multiple times with the same arguments, and each time it is getting properties that it already has to endup removing duplicates.
Instead, just create a variable to know that we have already run it for one target, and do nothing if it has already been called.
This is reducing clspv_combine_static_lib to less that 1s on my machine.

improve clspv_get_transitive_libs performance

---

lib/LowerAddrSpaceCastPass.cpp
lib/LowerAddrSpaceCastPass.h
test/AddressSpaceCast/issue-1096.ll
test/AddressSpaceCast/issue-1097.ll

add callinst support in loweraddrspacecastpass

---

lib/LongVectorLoweringPass.cpp
test/LongVectorLowering/mix.ll

* Fixes CTS commonfns/mix test

Support mix of long vectors

---

lib/BitcastUtils.cpp
lib/SimplifyPointerBitcastPass.cpp
lib/SimplifyPointerBitcastPass.h
test/PointerCasts/invalid_gep_from_gep.ll
test/PointerCasts/invalid_local_cast.ll
test/PointerCasts/multiple_implcit_casts.ll
test/PointerCasts/opaque_trivial_casts.ll
test/PointerCasts/unneeded_indices.ll

- clean GetIdxsForTyFromOffset for Constant Path with structure types
- reorganise simplify function
- add runOnUnneededIndices to avoid implicitCasts issue with #1109
- add debug log in simplify pointer bitcast pass
- update & add tests
This PR is needed to solve issue from #1109
Fix #1115

update pointer bitcast management

---

lib/Builtins.cpp
lib/Builtins.h
lib/ReplaceOpenCLBuiltinPass.cpp
lib/SplatArgPass.cpp

fix async_strided_copy with half

---

lib/PrintfPass.cpp
lib/SPIRVProducerPass.cpp
test/Printf/printf_physical_buffer.cl
test/Printf/printf_pointer.ll

fix printf support with physical addressing
fix printf of pointers

complete printf support

---

lib/LongVectorLoweringPass.cpp
test/LongVectorLowering/atan.ll
test/LongVectorLowering/atan2.ll
test/LongVectorLowering/issue-1155.cl
test/LongVectorLowering/rsqrt.ll
test/LongVectorLowering/sqrt.ll

add missing builins in longvectorlowering pass

---

lib/BitcastUtils.cpp
lib/ReplacePointerBitcastPass.cpp
test/PointerCasts/issue-1174.cl

fix types use in several calls to CreateAdd

---

lib/ReplacePointerBitcastPass.cpp
test/PointerCasts/issue-1187.ll
test/PointerCasts/store-zeroinitializer.ll

fix handle of zerovalue in computestore (replacepointerbitcast)

---

lib/BitcastUtils.cpp
lib/BitcastUtils.h
lib/ReplacePointerBitcastPass.cpp
test/PointerCasts/issue-1192.ll

fix load of complex struct

---

lib/SimplifyPointerBitcastPass.cpp
test/PointerCasts/issue-1197-2.ll
test/PointerCasts/issue-1197.ll

add gep between instruction with implicit cast to help rework it

---

lib/BitcastUtils.cpp
lib/LowerPrivatePointerPHIPass.cpp
test/PrivatePointerPHI/ptrtoint.ll

also avoid accessing nullptr in BitcastUtils::IsImplicitCast
Ref #1209

add support for ptrtoint in LowerPrivatePointerPHI

---

lib/LowerPrivatePointerPHIPass.cpp
lib/LowerPrivatePointerPHIPass.h
test/PrivatePointerPHI/icmp.ll
test/PrivatePointerPHI/icmp2.ll
test/PrivatePointerPHI/ptrtoint.ll

also add a map to avoid making twice the same gep.
Ref #1222 #1221

add support for icmp in LowerPrivatePointerPHIPass

---

lib/LowerPrivatePointerPHIPass.cpp

Use proper type for ptr offset

fix LowerPrivatePointerPHIPass

---

kokoro/scripts/linux/build-amber.sh
kokoro/scripts/linux/build-clvk.sh
kokoro/scripts/linux/build.sh

Update clang and gcc versions for kokoro

---

test/PointerCasts/issue-1243.ll

add example of issue 1243 to detect changes in clspv

---

lib/NativeMathPass.cpp

decorate libclc functions with noimplicitFloat

---

lib/LowerPrivatePointerPHIPass.cpp
test/PrivatePointerPHI/complex_struct.ll

Lower complex struct in alloca used in private pointer phi

---

lib/BitcastUtils.cpp
test/PointerCasts/issue-1192.ll
test/PointerCasts/issue-1221.ll

also fixed test/PointerCasts/issue-1192.ll missing a FileCheck command
Ref #1221

consider unsized types in ExtractOffsetFromGEP

---

lib/SimplifyPointerBitcastPass.cpp
test/PointerCasts/issue-1221-2.ll

only upgrade constant cast of integer

---

lib/BitcastUtils.cpp
lib/HideConstantLoadsPass.cpp
lib/SPIRVProducerPass.cpp
lib/ThreeElementVectorLoweringPass.cpp
lib/Types.cpp

Use StringRef::starts_with instead of startswith

---

lib/SimplifyPointerBitcastPass.cpp

We what to upgrade all other function. Especially the calls ending up on atomics operation

only skip memcpy in runOnUpgradeableConstantCasts

---

lib/Types.cpp
test/PointerCasts/select.ll

This is fixing an issue when enabling physical addressing following latest llvm changes

fix infer type of SelectInst

---

lib/FrontendPlugin.cpp
test/CPlusPlus/reference-parameter.cl

Support reference types in IsSupportedType

---

test/PhysicalStorageBuffers/physical_global_ptrtoint.cl

fix physical_global_ptrtoint.cl

---

lib/SimplifyPointerBitcastPass.cpp
test/PhysicalStorageBuffers/physical_constant_ptrtoint.cl

fix physical_constant_ptrint.cl

---

lib/SimplifyPointerBitcastPass.cpp
test/PointerCasts/upgradable_cst_casts.ll

We need to take care of phis first, otherwise we could end up trying to access phis that has been reworked by the Worklist loop.

fix runOnUpgradeableConstantCasts

---

kokoro/check-format/build-docker.sh
kokoro/scripts/linux/build-amber.sh
kokoro/scripts/linux/build-clvk.sh
kokoro/scripts/linux/build.sh

kokoro: Linux builds use Python 3.12

---

lib/PrintfPass.cpp
test/Printf/printf_string_64bit_ptr.ll
test/Printf/printf_string_with_null.ll

Support printf string args with nul

---

kokoro/scripts/macos/build.sh

This is required for Kokoro Apple Silicon images

kokoro mac: download CMake

---

deps.json
lib/NormalizeGlobalVariable.cpp
test/NormalizeGlobalVariables/multiple_uses2.ll

* Copy users before modifying them...
* Reuse normalized variable when types match

Fix global variable normalization

---

lib/BitcastUtils.cpp
test/PointerCasts/issue-1392.cl

BitcastUtils.cpp: fix GetIdxsForTyFromOffset

---

lib/AllocateDescriptorsPass.cpp
lib/ClusterConstants.cpp
lib/FixupStructuredCFGPass.cpp
lib/MultiVersionUBOFunctionsPass.cpp
lib/PrintfPass.cpp
lib/PushConstant.cpp
lib/RemoveUnusedArguments.cpp
lib/ReplaceLLVMIntrinsicsPass.cpp
lib/ReplaceOpenCLBuiltinPass.cpp
lib/ReplacePointerBitcastPass.cpp
lib/RewriteInsertsPass.cpp
lib/RewritePackedStructs.cpp
lib/SPIRVOp.cpp
lib/ScalarizePass.cpp
lib/SimplifyPointerBitcastPass.cpp
lib/UndoByvalPass.cpp
lib/UndoSRetPass.cpp
lib/UndoTranslateSamplerFoldPass.cpp
lib/UndoTruncateToOddIntegerPass.cpp

Fix to remove usage of deprecated template

---

CMakeLists.txt

spirv-tools library is needed for clspv-reflection

build spirv-tools even for android

---

kokoro/amber-linux-gcc-release/build.sh
kokoro/clvk-linux-clang-debug/build.sh
kokoro/linux-clang-debug/build.sh
kokoro/linux-clang-release/build.sh
kokoro/linux-gcc-debug/build.sh
kokoro/linux-gcc-release/build.sh

kokoro: linux: use cpp-builder instead of radial-build

---

lib/LongVectorLoweringPass.cpp
test/LongVectorLowering/native_exp.ll

add support native_exp in longvectorloweringpass
