google/clspv

- docs/OpenCLCOnVulkan.md
- include/clspv/Passes.h
- lib/SPIRVProducerPass.cpp
- tools/driver/main.cpp
The value is a quoted string containing the sampler literal
initializer expression (with whitespace removed).  The string
expression lists the components in sorted order, for easier
machine processing.
Adding this explicit expression makes it easier to use the descriptor
map since you no longer have to decode the integer value for the sampler.
Instead, it closely matches the expression in the specified samplermap
input file.
> Add samplerExpr to samplers in the descriptor map

- cmake/strip_banned_opencl_features.cmakescript
- tools/driver/main.cpp
Two commits in this PR:
1
Emit user error for some uses of long vectors
Error out when there is a function definition which has an unsupported
vector type for return value or any of its parameters.
2
Error out for unsupported vector types in function bodies
Now that we've added the length 8 and 16 vector types again,
we should emit errors when they are used inside function bodies.
> Error for unsupported vector types

- lib/SPIRVProducerPass.cpp
- test/mfmt_c.cl
Read the characters as unsigned integers before shifting them around.
Also, be sure you don't have a stale reference to the binary
buffer string.
Also changes the format to decimal numbers, one per line.
Fixes https://github.com/google/clspv/issues/23
> Fix -mfmt=c

- lib/SPIRVProducerPass.cpp
- test/cluster_pod_args_larger_alignment.cl
Take alignment into account, by using the DataLayout
for the target.
Also makes it match the descriptormap output, which is already
more correct.
Fixes https://github.com/google/clspv/issues/27
> Fix member offsets for storage buffers

- cmake/spirv_c_strings.cmakescript
This is required to be able to build against latest SPIRV-Headers
Fixes https://github.com/google/clspv/issues/38
> Ignore ShaderViewportIndexLayerNV capability due to alias

- lib/SPIRVProducerPass.cpp
- test/char4_issue15_a.cl
- test/char4_issue15_b.cl
This is incrementally better than what we have now, but I suspect
we should have remapped the types earlier in the flow, and we should
never see the i8 at this point.
Fixes https://github.com/google/clspv/issues/15
> SPIR-V type for i8 always aliases the type for i32

- lib/SPIRVProducerPass.cpp
- test/Structs/insert_value_issue_14.cl
- test/char4_constant.cl
- test/char4_constant_zero.cl
Cover both when all components are int constants, or
when some are undef values.
Fixes https://github.com/google/clspv/issues/36
> Fix generation of <4 x i8> constants

- lib/SPIRVProducerPass.cpp
- test/char4_insert.cl
- Use Not rather than LogicalNot
- Register the last SPIR-V instruction ID for
the LLVM insertion.
Fixes https://github.com/google/clspv/issues/44
> Fix insertion into <4 x i8>

- lib/SPIRVProducerPass.cpp
- test/IntegerBuiltins/int2_clz.cl
- test/IntegerBuiltins/int3_clz.cl
- test/IntegerBuiltins/int4_clz.cl
- test/IntegerBuiltins/uint2_clz.cl
- test/IntegerBuiltins/uint3_clz.cl
- test/IntegerBuiltins/uint4_clz.cl
In the subtraction, use a splat vector of value 31 rather than scalar 31.
Fixes https://github.com/google/clspv/issues/54
> Fix codegen for vector clz

- lib/DefineOpenCLWorkItemBuiltinsPass.cpp
- lib/SPIRVProducerPass.cpp
- test/VaryingLocalSizes/one_kernel.cl
- test/VaryingLocalSizes/reqd_work_group_size_one_kernel.cl
- test/VaryingLocalSizes/reqd_work_group_size_two_kernels.cl
- test/VaryingLocalSizes/two_kernels.cl
- test/get_local_size.cl
Change the implementation of the get_local_size implementation to
avoid some driver bugs:
- One issue is trouble extracting individual elements.  It's seems to
work better to read the entire vector at once.
- Another issue is that we have to extract directly from the spec
composite value directly rather than from a variable initialized with
that spec constant value.
> WIP: Read WorkgroupSize as whole vector from the spec constant value

- include/clspv/Passes.h
- lib/CMakeLists.txt
- lib/SplatSelectCondition.cpp
- test/opselect_float2.cl
- tools/driver/main.cpp
For an OpSelect with vector data operands, the condition
must be a bool vector with the same number of elements.
In this way SPIR-V is a slightly more restrictive than
LLVM IR.
Fixes https://github.com/google/clspv/issues/65
> OpSelect: vectorize bool condition for vector operands

- docs/OpenCLCOnVulkan.md
- lib/SPIRVProducerPass.cpp
- test/VaryingLocalSizes/reqd_work_group_size_two_kernels.cl
- test/VaryingLocalSizes/two_kernels.cl
- test/descriptor_set_default.cl
- test/descriptor_set_distinct.cl
Use option -distinct-kernel-descriptor-sets to retain old behaviour
> By default, reuse descriptor sets across kernels

- docs/OpenCLCOnVulkan.md
- lib/ArgKind.cpp
- lib/ArgKind.h
- lib/CMakeLists.txt
- lib/ClusterPodKernelArgumentsPass.cpp
- lib/SPIRVProducerPass.cpp
- test/descriptor_map_argtype.cl
argKind is better because it doesn't have the connotation of providing OpenCL C type information.
It's a reduction of that.
> Change argType to argKind in descriptormap file

- include/clspv/Passes.h
- lib/CMakeLists.txt
- lib/HideConstantLoadsPass.cpp
- test/ProgramScopeConstants/select_between_constant_load.cl
- test/spvasm2checks.pl
- tools/driver/main.cpp
Prevent instcombine from generating selects over pointer-to-constant
which turn into OpSelect over pointer-to-Private which is invalid
even with VariablePointers.
We prevent it by temporarily wrapping the loads from constant
memory via an opaque function.  After all instcombines have been
run, unwrap those loads again.
> Hide loads from constant memory from instcombine

- lib/SPIRVProducerPass.cpp
The compiler doesn't error out, but will emit a call to a function
with id 0.  I don't know how to error out from within the code
generator.
This will make it easier to debug the case where we are missing
support for a builtin.
> Report call to unknown function

- lib/SPIRVProducerPass.cpp
- test/hack_undef.cl
Work around drive bug documented in https://github.com/google/clspv/issues/95
> Add -hack-undef: Use OpConstantNull instead of OpUndef

- lib/ClusterPodKernelArgumentsPass.cpp
- test/ImageBuiltins/read_imagef_sampler_float2.cl
- test/cluster_pod_args_globals_scalars.cl
- test/cluster_pod_args_locals_scalars.cl
Use option -no-inline-pod to avoid inlining, i.e. get the old
behaviour.  But it's deprecated.
> Cluster pod kernel args: Inline the inner function by default

- lib/\
- test/VaryingLocalSizes/reqd_work_group_size_two_kernels.cl
- test/VaryingLocalSizes/two_kernels.cl
- test/descriptor_set_default.cl
- test/reuse_kernel_arg_var.cl
We can reuse such a variable if:
- it is of the same type
- it was last used for a different function
- it uses the same binding number
Fixes https://github.com/google/clspv/issues/103
> Reuse kernel arg variables for StorageBuffers

- test/spvasm2checks.pl
Adds two options:
--numeric  :  only pattern match against numeric ids
--re2   : assume RE2 is the matcher, so we can use \w to match ID characters.  (This is good for use with https://github.com://google/effcee )
Fixes https://github.com/google/clspv/issues/114
> Nicer spvasm2checks

- CMakeLists.txt
This trims the number of default targets to build from 3299 to 1306 on my machine.
This is when you only care about `clspv`, not the `check-spirv` target.
> Set EXCLUDE_FROM_ALL for LLVM and SPIRV-Tools

- include/clspv/Passes.h
- lib/CMakeLists.txt
- lib/RewriteInsertsPass.cpp
- lib/SPIRVProducerPass.cpp
- test/Structs/insert_value_issue_14.cl
- test/composite_construct.cl
- test/composite_construct_varying.cl
- test/hack_inserts_constant.cl
- test/hack_inserts_undef.cl
- test/hack_inserts_varying.cl
- test/hack_inserts_zero.cl
- tools/driver/main.cpp
Rewrite insertions into structs to avoid OpCompositeInsert
By default: replace chains of OpCompositeInsert that cover all members of the struct.  Only rewrites cases where where the insertion replaces a top-level member of the struct (i.e. only has one indexing operand).  It also only recognizes the pattern where the members are inserted in index order.  This is turned on by default since this always makes the code smaller.
With option -hack-inserts, generalize rewrite *partial* chains, i.e. those that don't cover the entire struct.  This is a little more aggressive in that members don't have to be inserted in order.
> Rewrite inserts

- lib/SPIRVProducerPass.cpp
This helps with debugging the compiler.
> Add option -show-ids to show SPIR-V Ids of Functions

- docs/OpenCLCOnVulkan.md
- include/clspv/AddressSpace.h
- include/clspv/Option.h
- include/clspv/Passes.h
- lib/CMakeLists.txt
- lib/ClusterConstants.cpp
- lib/ClusterPodKernelArgumentsPass.cpp
- lib/ConstantEmitter.cpp
- lib/ConstantEmitter.h
- lib/Option.cpp
- lib/ReplaceOpenCLBuiltinPass.cpp
- lib/RewriteInsertsPass.cpp
- lib/SPIRVProducerPass.cpp
- test/PointerAccessChains/pointer_index_in_called_function.cl
- test/PointerAccessChains/pointer_index_is_constant_1.cl
- test/ProgramScopeConstants/constant_array_with_function_call.cl
- test/ProgramScopeConstants/constant_array_with_function_call_module_constants_storage_buffer.cl
- test/ProgramScopeConstants/in_storage_buffer_descriptor_map.cl
- test/ProgramScopeConstants/in_storage_buffer_descriptor_map_arr_arr.cl
- test/ProgramScopeConstants/in_storage_buffer_descriptor_map_arr_vec3.cl
- test/ProgramScopeConstants/in_storage_buffer_descriptor_map_no_constants.cl
- test/pod_in_ubo.cl
- tools/driver/main.cpp
Add -pod-ubo : put plain-old-data arguments in uniform buffers instead of storage buffers.  This could be faster.
Add -module-constants-in-storage-buffer:  Big change enabled by new option.
- Don't use Private variables for __constant data
- Module-scope constants are collected into a single storage buffer
- That storage buffer must be initialized by the host to contain the right initialization data by the time the pipeline executes
- The initialization data is emitted to the descriptor map along with the descriptor set and binding
This is more correct, fixing variable-pointers validation for cases where pointer-to-constant was being dereferenced inside a function.
> Cluster constants

- docs/\
- lib/ArgKind.cpp
- lib/ArgKind.h
- lib/ClusterPodKernelArgumentsPass.cpp
- lib/SPIRVProducerPass.cpp
- test/cluster_pod_args_locals_scalars.cl
- test/ptr_local_struct.cl
- test/ptr_local_struct_cluster_pod_args.cl
- Descriptor map says it's a local, not a buffer.
- Don't allocate a binding for such variables.
- Maps to OpVariable in Workgroup storge of type OpTypeArray
- Array size is an integer specialization constant, with SpecId unique
to that integer.
- Document pointer-to-local kernel args
- Add tests
- Refactor SPIRVOperandList into its own class
Add a shift operator to add operands to the list.
Add MkId and MkNum helpers to make operands.
> Support pointer-to-local kernel arguments

- include/clspv/Option.h
- lib/Option.cpp
- lib/SPIRVProducerPass.cpp
- test/get_global_size_hack_initializers.cl
Use -hack-initializers to work around driver bugs that cause the
get_global_size builtin function to return the wrong value if used with
a non-constant dimension argument.
The underlying issue is that SPIR-V Private variable initializers may
not take effect.  The workaround is to start every kernel with an
explicit store to write the initializer value.  This is only required
for a compiler-generated variable that stores the workgroup size, only
used to implement the get_global_size builtin.
> Add -hack-initializers to work around a driver bug

- lib/SPIRVProducerPass.cpp
It prints to stderr, then proceeds to crash.
It's bad, but better than nothing.
> Print message if literal sampler without sampler map

- test/MathBuiltins/float2_acospi.cl
- test/MathBuiltins/float2_asinpi.cl
- test/MathBuiltins/float2_atan2pi.cl
- test/MathBuiltins/float2_exp10.cl
- test/MathBuiltins/float2_half_exp10.cl
- test/MathBuiltins/float2_native_exp10.cl
- test/MathBuiltins/float3_acospi.cl
- test/MathBuiltins/float3_asinpi.cl
- test/MathBuiltins/float3_atan2pi.cl
- test/MathBuiltins/float3_exp10.cl
- test/MathBuiltins/float3_half_exp10.cl
- test/MathBuiltins/float3_native_exp10.cl
- test/MathBuiltins/float4_acospi.cl
- test/MathBuiltins/float4_asinpi.cl
- test/MathBuiltins/float4_atan2pi.cl
- test/MathBuiltins/float4_exp10.cl
- test/MathBuiltins/float4_half_exp10.cl
- test/MathBuiltins/float4_native_exp10.cl
- test/MathBuiltins/float_acospi.cl
- test/MathBuiltins/float_asinpi.cl
- test/MathBuiltins/float_atan2pi.cl
- test/MathBuiltins/float_exp10.cl
- test/MathBuiltins/float_half_exp10.cl
- test/MathBuiltins/float_native_exp10.cl
The SPIRV-Tools disassembler recently started printing
more digits in floating point numbers, to better reproduce
values.
This change accommodates both old and new SPIRV-Tools by truncating
the specified floating point digits to match.
> Tests: Reduce number of digits to match

- lib/ReplaceLLVMIntrinsicsPass.cpp
- test/LLVMIntrinsics/lifetime_start.cl
The corresponding OpLifetimeStart and OpLifetimeEnd instructions
require Kernel capability, so we can't use them in Vulkan shaders
anyway.  Just remove them.
Fixes https://github.com/google/clspv/issues/142
> Remove @llvm.lifetime.* intrinsics

- lib/CMakeLists.txt
- lib/DescriptorCounter.cpp
- lib/DescriptorCounter.h
- lib/SPIRVProducerPass.cpp
It's in module-scope metadata with name "clspv.descriptor.index"
This will make it easier to allocate descriptor sets in different parts
of the compiler.
> Current descriptor set index maintained in named metadata

- lib/CMakeLists.txt
- lib/SPIRVProducerPass.cpp
Temporarily disable W4596.
Disable W5039, W5045
Fix a few others.
Progress toward #153
> Fix some new VS2017 warnings

- include/clspv/Option.h
- include/clspv/Passes.h
- lib/AllocateDescriptorsPass.cpp
- lib/CMakeLists.txt
- lib/DirectResourceAccessPass.cpp
- lib/Option.cpp
- lib/SPIRVProducerPass.cpp
- test/DirectResourceAccess/common_global_into_helper.cl
- test/DirectResourceAccess/constant_arg.cl
- test/DirectResourceAccess/global_arg.cl
- test/DirectResourceAccess/inconsistent_kernel_args_global.cl
- test/DirectResourceAccess/local_arg.cl
- test/DirectResourceAccess/partial_access_chain_global.cl
- test/DirectResourceAccess/ro_image2_sampler_args.cl
- test/DirectResourceAccess/ro_image3_sampler_args.cl
- test/DirectResourceAccess/wo_image2_args.cl
- test/DirectResourceAccess/wo_image3_args.cl
- test/ImageBuiltins/read_only_image2d_passed_to_other_function.cl
- test/ImageBuiltins/read_only_image3d_passed_to_other_function.cl
- test/ImageBuiltins/write_only_image2d_passed_to_other_function.cl
- test/ImageBuiltins/write_only_image3d_passed_to_other_function.cl
- test/PointerAccessChains/pointer_deref.cl
- test/PointerAccessChains/pointer_index_in_called_function.cl
- test/PointerAccessChains/pointer_index_is_constant_0.cl
- test/PointerAccessChains/pointer_index_is_constant_1.cl
- test/ResourceVar/pointer_to_constant_arg_into_helper_fn.cl
- test/spvasm2checks.pl
- tools/driver/main.cpp
Where possible, convert helper function accesses to resource variables
into direct accesses of that resource variable.  This happens under
the following conditions:
- Affects kernel arguments of the following type, which are converted
to resource variables that are associated with Vulkan descriptors:
- pointer-to-global
- pointer-to-constant
- image
- sampler
- All callees of the helper function are using the same resource
variable. (E.g. Generally, same kernel argument index and same type.)
- The base pointer of the resource is passed in (directly, without
modification or sub-object access chain)
Use option -no-dra to disable this optimization.
Use of -distinct-kernel-descriptor-sets disables this optimiztaion.
List of commits included
------------------------
1.
Resource var call also …
> Direct Resource Access optimization

- lib/DirectResourceAccessPass.cpp
- test/DirectResourceAccess/global_subobject_base.cl
When nesting one GEP inside another, account for the fact
that the first ("element" or "slide") index will be combined
with the last element of the previous (dominating) GEP.
If we don't do this then the type accounting is wrong and we
generate an invalid GEP.
> Direct resource access: Fix gep zero counting

- include/clspv/Option.h
- include/clspv/Passes.h
- lib/CMakeLists.txt
- lib/DirectResourceAccessPass.cpp
- lib/Option.cpp
- lib/SignedCompareFixupPass.cpp
- test/hack_scf_32bit.cl
- tools/driver/main.cpp
With -hack-scf, replace signed integer comparisons with other
equivalent instructions.
> Add -hack-scf: signed integer comparisons fixup

- lib/ReplacePointerBitcastPass.cpp
Resolves
```
[911/1316] Building CXX object lib/CMakeFiles/clspv_core.dir/ReplacePointerBitcastPass.cpp.o
../lib/ReplacePointerBitcastPass.cpp:163:15: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
if (GEP = dyn_cast<GetElementPtrInst>(BitCastUser)) {
~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../lib/ReplacePointerBitcastPass.cpp:163:15: note: place parentheses around the assignment to silence this warning
if (GEP = dyn_cast<GetElementPtrInst>(BitCastUser)) {
^
(                                             )
../lib/ReplacePointerBitcastPass.cpp:163:15: note: use '==' to turn this assignment into an equality comparison
if (GEP = dyn_cast<GetElementPtrInst>(BitCastUser)) {
^
==
../lib/ReplacePointerBitcastPass.cpp:809:15: warning: using the …
```
> Fix -Wparentheses warnings

- include/clspv/Option.h
- include/clspv/Passes.h
- lib/CMakeLists.txt
- lib/Option.cpp
- lib/ScalarizePass.cpp
- test/Scalarize/constant_struct.cl
- test/Scalarize/nested_struct.cl
- tools/driver/main.cpp
* Currently only scalarizes struct type phis if an option (-hack-phis)
is enabled
* Includes a test
The idea is that this pass can be extended as necessary to handle any scalarization cases that prove to necessary in the future.
> Pass to scalarize composites

- lib/UndoGetElementPtrConstantExprPass.cpp
* Will proceed with replacement for instructions and not fail if any
other constants are users
> Expand constant gep replacement

- CMakeLists.txt
- utils/fetch_sources.py
The default behaviour doesn't change but a project embedding clspv
can now:
- pass SPIRV_HEADERS_SOURCE_DIR to provide SPIRV-Headers
- pass SPIRV_TOOLS_SOURCE_DIR to provide SPIRV-Tools
- pass a list of dependencies to be managed by utils/fetch_sources.py
> Make it possible to provide SPIRV-Tools and SPIRV-Headers externally

- lib/SPIRVProducerPass.cpp
- test/CommonBuiltins/float2_smoothstep.cl
- test/CommonBuiltins/float3_smoothstep.cl
- test/CommonBuiltins/float4_smoothstep.cl
- test/CommonBuiltins/float_smoothstep.cl
This suffers from the same issues as step (see #199).
The supported cases (all parameters having the same type)
pass the OpenCL conformance tests run via clvk on NVidia
hardware.
> Add partial support for the smoothstep built-in

- docs/OpenCLCOnVulkan.md
This is definitely supported now.
> Remove 'local' kernel arguments from the list of restrictions

- docs/OpenCLCOnVulkan.md
- lib/ClusterPodKernelArgumentsPass.cpp
- lib/SPIRVProducerPass.cpp
- test/DirectResourceAccess/common_global_into_helper.cl
- test/ProgramScopeConstants/in_storage_buffer_descriptor_map.cl
- test/ProgramScopeConstants/in_storage_buffer_descriptor_map_arr_arr.cl
- test/ProgramScopeConstants/in_storage_buffer_descriptor_map_arr_vec3.cl
- test/ProgramScopeConstants/in_storage_buffer_descriptor_map_no_constants.cl
- test/cluster_pod_args_locals_scalars_pod_in_ubo.cl
- test/descriptor_map_argtype.cl
- test/pod_in_ubo.cl
- test/ptr_local_struct.cl
- test/ptr_local_struct_cluster_pod_args.cl
Enable users to:
- know how much memory to allocate for their pod buffer when
using -cluster-pod-kernel-args
- check the size of the data bound to pod bindings is correct
Fixes #185 
> Emit pod argument size to descriptor map

- lib/SPIRVProducerPass.cpp
- test/bool_vector_and.cl
- test/bool_vector_or.cl
Bitwise instructions were being emitted. The tests added only cover `And` and `Or` as I couldn't find a way of producing `Xor` on boolean vectors which seems to line up with a few observations from the OpenCL specification:
- there is no xor logical operator (although `^^` has been reserved for that use)
- boolean vectors aren't explicitly specified (even though `booln` (2,3,4,8 and 16) is a reserved type)
- the result of relational operators applied to two vectors is guaranteed to be a vector of signed integers (this is the case that made me discover the issue)
Clang's omission of the sign extension to integer vectors when the result of multiple relational operators is only used by a logical operation is an optimisation. Since there is no logical xor operator it is reasonable for Clang …
> Fix codegen for logical operations on bool vectors

- test/CMakeLists.txt
Projects that embed clspv and relocate the clspv binary in the build
output couldn't use the check-spirv target as clspv wasn't where
lit.py expected to find it.
Use a generator expression so the path is correct in all cases.
> Make the check-spirv target work for projects embedding clspv

- tools/driver/main.cpp
This is required to be defined by §6.10 in the OpenCL
spec when image support is present.
> Always define the __IMAGE_SUPPORT__ macro

- include/clspv/Option.h
- lib/Compiler.cpp
- lib/Option.cpp
- lib/ReorderBasicBlocksPass.cpp
* Adds -hack-block-order to produce blocks in structured order to
satisfy some drivers
Did not change the default ordering because this is slower, the default ordering should be accepted by drivers and there would be too many test updates.
> Add an option for a stronger basic block ordering

- kokoro/scripts/windows/build.bat
- kokoro/windows-msvc-2015-release/build.bat
- kokoro/windows-msvc-2017-debug/build.bat
- kokoro/windows-msvc-2017-release/build.bat
* Don't build any LLVM targets
* Run Release and RelWithDebInfo instead of RelWithDebInfo and Debug
Testing whether Windows bots will still timeout in this configuration.
> Attempt to speed windows bots

- docs/OpenCLCOnVulkan.md
It seems there are tests / implementation for a few of these (ex: [acospi](https://github.com/google/clspv/blob/master/test/MathBuiltins/float2_acospi.cl)).
> Update readme for supported built-in math functions

- lib/ReplaceLLVMIntrinsicsPass.cpp
- lib/SPIRVProducerPass.cpp
- test/LLVMIntrinsics/memcpy_from_constant.cl
Fixes #254
* Handle constant expression bitcasts when replacing memcpy and memset
* update spirv producer to not attempt to replace constant operands
* add a test
> Handle constant expression casts in intrinsic args

- include/clspv/Option.h
- lib/FrontendPlugin.cpp
- lib/Option.cpp
* -std430-ubo-layout disables standard UBO layout checks
The frontend should verify the ssbo layouts, but currently does not. Leaving that for a different PR.
> Add option to turn UBO layout checks off

- lib/SPIRVProducerPass.cpp
- test/opselect_constants_int_scalar.cl
- test/opselect_constants_int_vector.cl
- test/opselect_constants_long_scalar.cl
- test/opselect_constants_long_vector.cl
- test/opselect_constants_short_scalar.cl
- test/opselect_constants_short_vector.cl
...so that non-32-bit integer types are correctly handled.
Also delete a bit of nearby dead code.
Fixes #235.
> Generalise the production of constants for OpSelect

- docs/OpenCLCOnVulkan.md
- lib/ReplaceOpenCLBuiltinPass.cpp
- test/IntegerBuiltins/upsample/upsample_int.cl
- test/IntegerBuiltins/upsample/upsample_int2.cl
- test/IntegerBuiltins/upsample/upsample_int3.cl
- test/IntegerBuiltins/upsample/upsample_int4.cl
- test/IntegerBuiltins/upsample/upsample_short.cl
- test/IntegerBuiltins/upsample/upsample_short2.cl
- test/IntegerBuiltins/upsample/upsample_short3.cl
- test/IntegerBuiltins/upsample/upsample_short4.cl
The tests added here are a compromise between succinctness,
ease of maintenance and coverage. The second argument to upsample
is a constant and its conversion to the result type is folded
into the constant. However, using two non-constant arguments
leads to a much longer and brittler test if one wants to ensure
that their relative ordering is correct.
> Add support for the upsample built-in function

- lib/ClusterPodKernelArgumentsPass.cpp
- test/cluster_pod_args_pod_only.cl
There are programs out there with code like this.
> Allow -cluster-pod-kernel-args on kernels with only pod arguments

- lib/Compiler.cpp
When used as an online compiler clspv must reset the command line between compiles.
> Fix option parsing for repeated compiles online

- lib/AllocateDescriptorsPass.cpp
- lib/Compiler.cpp
- lib/SPIRVProducerPass.cpp
- test/Coherent/coherent_barrier_subfunction.cl
- test/Coherent/coherent_simple.cl
- test/Coherent/coherent_subfunction_parameter.cl
- test/Coherent/frexp.cl
- test/Coherent/missing_barrier.cl
- test/Coherent/parameter_one_use_is_coherent.cl
- test/Coherent/read_only.cl
- test/Coherent/selection.cl
- test/Coherent/write_only.cl
Global variables that are read and written in kernels that have barrier/fence synchronization are now decorated as coherent.
Descriptor allocation identifies whether variables are both read and written in synchronized kernels. Coherency is a new discriminant so coherent and non-coherent variables are not shared.
The spirv producer annotates function parameters by searching backwards to see which resource variables are used with it. Any coherent variable turns a function parameter coherent.
> Coherent decoration for global variables

- include/clspv/Option.h
- lib/UndoBoolPass.cpp
- test/Int8/bool_to_char.cl
Fixes #288
* Valid uses cases when -int8 is enabled
* In either event the IR would be invalid if the instruction had uses
that remained.
> Only remove trivially dead insts in UndoBoolPass

- lib/ClusterPodKernelArgumentsPass.cpp
- test/cluster_pod_args_attributes.cl
Attributes weren't being transfered to the remapped arguments.
This change only covers transfering attributes for pointer
arguments.
> Fix handling of attributes in ClusterPodKernelArgumentsPass

- docs/OpenCLCOnVulkan.md
Such a broad restriction on 64-bit integer types no longer
makes sense. If specific things don't work, they should be
documented instead.
> Update type restrictions in documentation

- lib/Compiler.cpp
- lib/UBOTypeTransformPass.cpp
- test/UBO/char_ubo_struct.cl
- test/UBO/large_padding.cl
- test/UBO/large_padding_std430.cl
- test/UBO/odd_size_padding.cl
Fixes #279
* Type mutation now replaces any char array if char arrays are not
supported
* char arrays are supported if -int8 and -std430-ubo-layout are
specified
* New tests
> Support chars in UBOs

- lib/ReplaceOpenCLBuiltinPass.cpp
- lib/SPIRVProducerPass.cpp
All replacements are now done in the ReplaceOpenCLBuiltinPass.
> Replace calls to abs() with unsigned values in a more consistent way

- test/CMakeLists.txt
All tests that use clspv-opt will fail in a project that embeds
clspv and changes the location of only the clspv binary in the
build output.
> Don't assume that clspv and clspv-opt are in the same folder

- lib/Compiler.cpp
- test/UBO/bad_after_array.cl
- test/UBO/bad_array.cl
- test/UBO/bad_int_array.cl
- test/UBO/bad_scalar.cl
- test/UBO/bad_ssbo_scalar.cl
- test/UBO/bad_ssbo_vec2.cl
- test/UBO/bad_ssbo_vec4.cl
- test/UBO/bad_struct.cl
- test/UBO/bad_vec2.cl
- test/UBO/bad_vec4.cl
- test/UBO/relaxed_int_array.cl
- test/Warnings/error.cl
- test/Warnings/ignored.cl
- test/Warnings/simple.cl
Enable all warnings.
Support the two standard OpenCL options -w and -Werror.
CompileFromSourceString prints warnings only when there
are errors. It probably shouldn't print anything to stderr
but that's another story.
> Add support for warnings

- lib/CMakeLists.txt
- lib/Constants.h
- lib/ReplaceOpenCLBuiltinPass.cpp
- lib/SPIRVOp.cpp
- lib/SPIRVOp.h
- lib/SPIRVProducerPass.cpp
- test/IntegerBuiltins/mad_hi/mad_hi_all_overloads.cl
- test/IntegerBuiltins/mul_hi/mul_hi_all_overloads.cl
Directly calling a specific SPIR-V instruction is a common
idiom which should be shorter to write than it currently is.
Besides, having a centralised scheme that deals with encoding
SPIR-V intrinsics removes the need to worry about issues like
#308.
This change introduces a utility function that inserts a call
to a SPIR-V instruction passed as a parameter. It automatically
inserts required functions into the module if needed and
guarantees they have a unique name with a simple mangling
scheme.
The current encoding makes the IR a bit less readable as
the functions used to encode SPIR-V instructions are named
after the opcode number rather than the instruction name.
This can be improved upon later if felt necessary.
This change also uses the new mechanism for the mul_hi/mad_hi
built-in …
> Introduce a mechanism to call specific SPIR-V instructions

- lib/AllocateDescriptorsPass.cpp
- test/unused-local-arg-dmap.cl
Applications or runtimes like clvk that rely on the
descriptor map to know about valid kernel argument indices
need all arguments in the descriptor map, even if they're
unused.
> Always report local arguments in descriptor map

- lib/SPIRVProducerPass.cpp
- test/Coherent/coherent_multiple_subfunctions.cl
Fixes #332
* Other function args encountered after the initial arg would not
correctly traverse to the caller
* Added a test
> Fix coherent parameter tracing

- lib/ClusterPodKernelArgumentsPass.cpp
- test/cluster_pod_args_attibutes_on_pod.cl
Attributes for non-POD arguments were correctly transferred
to the remapped arguments but so were attributes for POD
arguments which led to invalid attributes applied to the
POD structure in some cases.
The comments were describing the correct behaviour but the
code was doing something else.
> Fix attributes transfer in ClusterPodKernelArgumentsPass

- include/clspv/AddressSpace.h
- include/clspv/Option.h
- include/clspv/Passes.h
- lib/CMakeLists.txt
- lib/Compiler.cpp
- lib/DemangleKernelNames.cpp
- lib/FrontendPlugin.cpp
- lib/Option.cpp
- lib/SPIRVProducerPass.cpp
- test/CPlusPlus/kernel-overload.cl
- test/CPlusPlus/object-and-overload.cl
- test/CPlusPlus/template.cl
This change adds experimental support for C++ via Clang's
OpenCL C++ mode.
In that mode Clang uses OpenCL's generic address space for
a number of things so I've added it to
clspv::AddressSpace to align clspv's internal convention
with what Clang does a bit better.
This currently has to be used with -inline-entry-points to
maximise the chances that all traces of generic address
space will have been removed before passes that don't
support it. I have another change that plugs LLVM's address
space inference pass and enables quite a bit more code to be
compiled (and the use of the generic address space generally)
but it requires a couple of minor changes to LLVM.
Kernel function overloads are forbidden in the FrontendPlugin
with a custom diagnostic message. Kernel function names
are demangled …
> [RFC] Experimental C++ support

- kokoro/check-format/build_continuous.sh
- kokoro/check-format/continuous.cfg
- utils/check_code_format.sh
* Provide an option to the code formatter to check the whole repo
* Change the CI version to use the new option
> Make the Format CI bot do something

- lib/ReplacePointerBitcastPass.cpp
- test/PointerCasts/store_cast_char_to_float.cl
- test/PointerCasts/store_cast_short_to_float.cl
Fixes #334
* Shift should be sized by the source bitwidth
* Added tests for char -> float and short -> float
> Fix shifts in scalar store pointer casts

- include/clspv/Passes.h
- lib/CMakeLists.txt
- lib/CallGraphOrderedFunctions.cpp
- lib/CallGraphOrderedFunctions.h
- lib/Compiler.cpp
- lib/DirectResourceAccessPass.cpp
- lib/MultiVersionUBOFunctionsPass.cpp
- lib/UBOTypeTransformPass.cpp
- test/UBO/can_dra_but_disabled.cl
- test/UBO/can_dra_but_disabled_two_kernels.cl
- test/UBO/cannot_dra.cl
- test/UBO/extra_arg.cl
- test/UBO/extra_args.cl
- test/UBO/long_specialization_chain.cl
- test/UBO/mixed_inlining.cl
- test/UBO/multiple_ubo_args.cl
- test/UBO/needs_inlined.cl
Fixes #330 
* changes to the type mutation to touch fewer types
* RebuildType just calls MapType with rewrite == false to be clear
Pass to specialize/inline functions with UBOs
SPIR-V does not support passing UBOs by reference. If DRA cannot
determine a singular source of a UBO, the new pass will either
specialize it or inline it. The decision is made on a per call basis.
* Refactored CallGraphOrderedFunctions to de-duplicate it
* added cleanup passes to run after specialization
* Added tests
This removes the requirement to exhaustively inline entry points. It has many opportunities for future improvement by handling more cases that it currently resorts to inlining to solve. Currently it handles chains of GEPs from a resource variable.
Future improvements:
* This pass hits similar targets …
> Don't require inlining to use UBOs

- lib/Compiler.cpp
- test/emit_ir.cl
This adds the flag `--emit-ir` which can be used in conjunction with
`clspv-opt` to develop and debug clspv passes.
The flag emits LLVM IR right after the module has been parsed.  It
seemed the most natural place to dump the IR, because it gives the most
flexibility.  Once the initial IR has been generated, all the passes up
to the problematic one can be applied via `clspv-opt`.
> Add flag to emit LLVM IR after parsing.

- include/clspv/Option.h
- lib/Compiler.cpp
- lib/Option.cpp
Clang now defines it by default (was picked up in the update)
and the conformance tests check that this is defined if and only
if the runtime advertises support.
> Add an option to undefine __IMAGE_SUPPORT__

- deps.json
- lib/Compiler.cpp
- test/CPlusPlus/generic-addrspace.cl
- test/CPlusPlus/issue-357.cl
This enables support for the generic address space in all
cases where the final address space can be inferred before
the SPIR-V production.
This should provide a step change in the amount of C++ code
that can be compiled.
Nota: both the Clang and LLVM updates are required to make
this work.
Fixes #357.
> [C++] Replace generic address space before SPIR-V production

- lib/Compiler.cpp
- test/print-all.cl
- tools/clspv-opt/main.cpp
Passes were not registering their print-after/print-before flags.  This calls the pass initializer and adds a test for a clspv pass.
> Fix #361 - Initialize clspv passes into the registry.

- lib/SPIRVProducerPass.cpp
They were replaced by AtomicRMW instructions a long time ago.
> Remove unused SPIR-V atomic intrinsics

- lib/CMakeLists.txt
- lib/ClusterConstants.cpp
- lib/NormalizeGlobalVariable.cpp
- lib/NormalizeGlobalVariable.h
- lib/SPIRVProducerPass.cpp
- test/NormalizeGlobalVariables/cluster_constants.ll
- test/NormalizeGlobalVariables/constant_bitcast.cl
- test/NormalizeGlobalVariables/different_geometry.ll
- test/NormalizeGlobalVariables/mismatched_depths.ll
- test/NormalizeGlobalVariables/multiple_uses.ll
Addresses some failures in customer kernels due to the way clang
codegen's constant aggregates.
* New utility to normalize constant global variables
* called in cluster constants and spirv producer
* rewrites global constants with constant bitcast users that are just
simple reinterpret casts
* added several tests
> Normalize constant global variables

- CMakeLists.txt
This CL updates the build files to allow setting the
CLSPV_LLVM_SOURCE_DIR and CLSPV_CLANG_SOURCE_DIR without specifying an
EXTERNAL_LLVM.
Because those directories maybe outside the clspv/ source tree we have
to provide the build directory when calling add_subdirectory.
> Allow external LLVM and Clang folders.

- lib/SPIRVProducerPass.cpp
- test/if_branch_to_loop_needs_selection_merge.cl
Fixes #377
* Change identification of the back-edge test for selection merge
generation
* merge is needed unless the branch is loop latch
* added a test
> Change selection merge generation

- lib/AllocateDescriptorsPass.cpp
- lib/ReplaceOpenCLBuiltinPass.cpp
- lib/SPIRVProducerPass.cpp
- test/Coherent/coherent_fence_simple.cl
- test/CommonBuiltins/no_duplicate_barrier.ll
Add missing test for coherent decorations.
Contributes to #308.
> Use InsertSPIRVOp to create calls to barrier SPIR-V intrinsics

- lib/ReplaceOpenCLBuiltinPass.cpp
- lib/SPIRVProducerPass.cpp
Since LLVM frem instructions are equivalent to OpFRem, use that
instead of directly replacing with the SPIR-V instruction as that
might enable additional optimizations.
> Move fmod built-in function replacement out of the producer pass

- cmake/CMakeLists.txt
The fix introduced for #406 only works when building clspv
standalone. When embedding clspv in another project
CLSPV_BINARY_DIR has to be used instead of CMAKE_BINARY_DIR.
Also introduce a variable for that directory.
> Fix generated files directory creation when embedding clspv

- lib/SPIRVProducerPass.cpp
- test/global-variable-no-undef-initializer.cl
This was avoided most of the time by luck because the OpUndef
wouldn't be in the value map. This change makes it a guarantee
and the added assert will catch any cases where initializers
are omitted by accident.
The new test case has been produced by reducing a kernel from
the SHOC benchmark suite.
> Prevent OpVariable from being produced with an OpUndef initializer

- deps.json
- lib/SPIRVProducerPass.cpp
Fixes #425
* Update SPIRV-Tools dep to include new validation
* Add clustered constants to the list of structs needing layout
decorations
> Add layout decorations to constants in SSBOs

- lib/Compiler.cpp
- test/ir-input.ll
Add a -x option to select the input type, defaulting to OpenCL C.
> Add support for taking LLVM IR as input

- lib/SPIRVProducerPass.cpp
- test/VariablePointers/function_call_image_param.cl
- test/VariablePointers/function_call_sampler_param.cl
Fixes #438
* Do not add VariablePointersStorageBuffer capability due to image or
sampler function parameters
* new tests
> Don't add variable pointers due to images and samplers

- amber/README.md
- amber/images/read_image2d_r32f.amber
- amber/images/read_image2d_r32i.amber
- amber/images/read_image2d_r32ui.amber
- amber/images/read_image2d_rg32f.amber
- amber/images/read_image2d_rg32i.amber
- amber/images/read_image2d_rg32ui.amber
- amber/images/read_image2d_rgba32f.amber
- amber/images/read_image2d_rgba32i.amber
- amber/images/read_image2d_rgba32ui.amber
- amber/images/write_image2d_r32f.amber
- amber/images/write_image2d_r32i.amber
- amber/images/write_image2d_r32ui.amber
- amber/images/write_image2d_rg32f.amber
- amber/images/write_image2d_rg32i.amber
- amber/images/write_image2d_rg32ui.amber
- amber/images/write_image2d_rgba32f.amber
- amber/images/write_image2d_rgba32i.amber
- amber/images/write_image2d_rgba32ui.amber
* New amber directory to contain Amber-based tests
* Added tests for 2D samped image reads and image writes
* formats: r32(f|ui|i), rg32(f|ui|i) and rgba32(f|ui|i)
No bots runs these yet. Short-ish term plan would be to setup a Kokoro bot that runs these against ToT [Amber](https://github.com/google/amber) using Swiftshader (at least those that Swiftshader supports).
> Add simple functional image tests

- deps.json
- lib/CMakeLists.txt
- lib/ComputeStructuredOrder.cpp
- lib/ComputeStructuredOrder.h
- lib/ReorderBasicBlocksPass.cpp
- lib/SPIRVProducerPass.cpp
- test/loop_continue_no_selection_merge.cl
Fixes #448
* Refactor structured order computation into a new file
* updates deps
* Modify SPIRVProducer pass to figure out merge and continues at the
start of the pass
* this is based on traversing in structured order
* do not generate selection merges if one side of the branch is a loop
continue or merge
* add a new test
The SPIRV-Tools update also includes the new validator check.
ComputeStructuredOrder is effectively a move from ReorderBasicBlock::StructuredOrder.
> Fix generation of selection merges

- README.md
This was missed in #265. This option is no longer supported.
> Remove references to -S from the README

- docs/OpenCLCOnVulkan.md
- lib/ReplaceOpenCLBuiltinPass.cpp
- test/ImageBuiltins/sampled_2d_3d_read_image_with_int_coords.ll
Also update the docs to reflect recent changes to image support.
AFAICT the _Z11read_imagef14ocl_image2d_ro11ocl_samplerDv4_i built-in
function I've removed doesn't exist in the OpenCL 1.2 spec.
> Support sampled read_image{f,i,ui} with integer coordinates for 2D/3D images

- docs/OpenCLCOnVulkan.md
- include/clspv/Option.h
- lib/AllocateDescriptorsPass.cpp
- lib/Compiler.cpp
- lib/Option.cpp
- lib/SPIRVProducerPass.cpp
- test/SamplerMap/KernelScopeSampler.cl
- test/SamplerMap/TwoModuleScopeSamplers.cl
- test/SamplerMap/no_sampler_map_two_samplers.cl
- test/issue-157.cl
- test/sampler-360.cl
Contributes to #451
* Add a warning when a sampler map is provided (for both online and
offline compiles)
* the sampler is still supported and works as before if it is provided
* Without a sampler map clspv now auto-generates bindings for literal
samplers based on the sampler literal
* updated sampler map tests to also test without a sampler map
* new test to verify consistency with the descriptor map
> Deprecate the sampler map

- lib/AllocateDescriptorsPass.cpp
- lib/Constants.h
- lib/ReplaceOpenCLBuiltinPass.cpp
- lib/UndoTranslateSamplerFoldPass.cpp
- test/ImageBuiltins/unsampled_read_image.ll
- test/ImageBuiltins/unsampled_read_image_descriptor_map.cl
Fixes #464
* Support unsampled image reads for 1D, 2D and 3D images
* calls are translated to sampled reads with a literal sampler using
CLK_ADDRESS_NONE | CLK_FILTER_NEAREST | CLK_NORMALIZED_COORDS_FALSE
* Add tests
* Refactor direct uses of string literal for sampler initializer with a function
> Unsampled reads

- lib/ReplaceOpenCLBuiltinPass.cpp
- test/ImageBuiltins/half_image_builtins.ll
Contributes to #455
* Add support for sampled and unsampled reads for 1D, 2D, and 3D images
* converts to equivalent float intrinsic and converts the result
* this means unsampled reads are converted to sampled reads and
integer coordinates are converted to floating-point coordinates
* Add support for half image writes for 1D, 2D and 3D images
* data is converted to float and the corresponding float version is
used
* Added test
> Add support for half image builtins

- utils/fetch_sources.py
Newer versions of python report the following:
utils/fetch_sources.py:87: SyntaxWarning: "is" with a literal. Did you mean "=="?
> Fix warning in fetch_sources.py

- include/clspv/Option.h
- lib/Compiler.cpp
- lib/Option.cpp
- lib/SPIRVProducerPass.cpp
- test/CPlusPlus/generic-addrspace.cl
- test/CPlusPlus/issue-357.cl
- test/CPlusPlus/kernel-overload.cl
- test/CPlusPlus/object-and-overload.cl
- test/CPlusPlus/opsource.cl
- test/CPlusPlus/template.cl
- test/opsource.cl
Match what Clang does except that:
- lowercase aliases of the language names are not supported
(they are not described in the OpenCL specification)
- the default standard is OpenCL C 1.2
Remove -c++ (replaced by -cl-std=CLC++).
Turn on address space inferencing when compiling as OpenCL C 2.0.
> Add support for -cl-std option

- lib/FrontendPlugin.cpp
- test/Structs/kernel_arg_has_pointer_in_struct.cl
- test/Structs/mutual_recursion_error.cl
- test/Structs/ptr_in_struct.cl
- test/Structs/ptr_in_struct2.cl
Fixes #468
* Move the check about pointers in structs to only happen for kernel
arguments
* Add a new check to prevent recursive struct definitions
* New and updated tests
> Refactor checks about pointers in structs

- include/clspv/DescriptorMap.h
- lib/Compiler.cpp
- lib/DescriptorMap.cpp
- lib/ReplaceOpenCLBuiltinPass.cpp
This allows clients to use the sampler mask that Clspv provides without having to duplicate all of these values.
> Move sampler constants to DescriptorMap.h

- lib/SPIRVProducerPass.cpp
- test/no_int64_due_to_index_literal.cl
Fixes #497
* Do not map types for operands that end up as literal values in SPIR-V
* Add a test to ensure Int64 capability is not added
I believe the i64 come from some sort canonicalization LLVM performs.
> Don't add int64 types due to literal operands

- lib/ReplacePointerBitcastPass.cpp
- test/PointerCasts/store_cast_char_to_short.ll
- test/PointerCasts/store_cast_int_to_long.ll
- test/PointerCasts/store_cast_short_to_float.ll
Fixes #504
* Make sure the operand types match for the generated `and` and `lshr` instructions
* Add a test
> Fix stores to widening pointer casts

- deps.json
Get a version of SPIRV-Tools that avoids Python distutils.dir_util
> Update SPIRV-Tools, SPIRV-Headers

- lib/Builtins.cpp
- lib/Builtins.h
- lib/OpenCLInlinerPass.cpp
- lib/ReplaceOpenCLBuiltinPass.cpp
- lib/SPIRVProducerPass.cpp
- lib/SplatArgPass.cpp
* Updated usage in SPIRVProducer, replaced StringSwitch
* Converted SplatArgPass, programmatically generate new function call based on FunctionInfo
* Converted all ReplaceOpenCLBuiltinPass
* Iterate once over Module->getFunctionList(), switch on FunctionInfo type
* Changed all replace methods to create a Replacer lambda
* Links to #510
> Builtins::Lookup interface - phase2

- cmake/CMakeLists.txt
- cmake/spirv_c_strings.py
- lib/ReplaceLLVMIntrinsicsPass.cpp
- lib/ReplaceOpenCLBuiltinPass.cpp
- lib/SPIRVOp.h
- lib/SPIRVProducerPass.cpp
* Output always targets SPIR-V 1.0
* Fix cmake auto-generated files to also use unified1 version
* generally avoid duplicate enum values in spirv_c_strings.py
Supercedes #421
> Use unified1 version of spirv

- lib/SPIRVProducerPass.cpp
- test/VariablePointers/sampler.cl
* Don't add variable pointer capabilities due to phis of images and
samplers
* TODO: never generate those anyways
* Add an option to dump IR before SPIRVProducerPass
> Fix VariablePointer capability generation

- deps.json
- include/clspv/Passes.h
- lib/AddFunctionAttributesPass.cpp
- lib/CMakeLists.txt
- lib/Compiler.cpp
- lib/Passes.cpp
- lib/Passes.h
- test/AddFunctionAttributes/no_sampler_phi.cl
- test/AddFunctionAttributes/translate_literal_sampler.ll
Fixes #538
* Add a new pass early in the flow to add function attributes as
necessary
* Currently adds readnone and speculatable to
__translate_sampler_initializer to prevent later optimizations from
creating phis of samplers
* add tests
* update spirv headers and tools
> Add attributes to functions pass

- include/clspv/Passes.h
- lib/CMakeLists.txt
- lib/Compiler.cpp
- lib/Passes.cpp
- lib/Passes.h
- lib/UndoInstCombinePass.cpp
- test/UndoInstCombine/undo_extract_cast.cl
- test/UndoInstCombine/undo_extract_cast_2xi64_to_8xi16.ll
- test/UndoInstCombine/undo_extract_cast_4xi32_to_16xi8.ll
- test/UndoInstCombine/undo_shuffle_cast.cl
- test/UndoInstCombine/undo_shuffle_cast_2xi64_to_8xi16.ll
- test/UndoInstCombine/undo_shuffle_cast_4xi32_to16xi8.ll
Fixes #549
* New pass to undo harmful instcombine transforms
* Currently handles two cases that produce wide vectors seen in CTS
* Add tests
> Add a new pass to undo harmful instcombines

- include/clspv/DescriptorMap.h
- lib/DescriptorMap.cpp
- lib/SPIRVProducerPass.cpp
- test/DirectResourceAccess/common_global_into_helper.cl
- test/ImageBuiltins/unsampled_read_image_descriptor_map.cl
- test/ProgramScopeConstants/constant_array_with_function_call_module_constants_storage_buffer.cl
- test/ProgramScopeConstants/in_storage_buffer_descriptor_map.cl
- test/ProgramScopeConstants/in_storage_buffer_descriptor_map_arr_arr.cl
- test/ProgramScopeConstants/in_storage_buffer_descriptor_map_arr_vec3.cl
- test/descriptor_set_default.cl
- test/descriptor_set_distinct.cl
- test/kernel-decl-dmap.cl
This make it easier for clvk to support kernel with no arguments.
Fixes #536.
> Report all kernels in the descriptor map

- docs/OpenCLCOnVulkan.md
- include/clspv/ArgKind.h
- include/clspv/Option.h
- lib/AllocateDescriptorsPass.cpp
- lib/ArgKind.cpp
- lib/ClusterPodKernelArgumentsPass.cpp
- lib/Compiler.cpp
- lib/DescriptorMap.cpp
- lib/FrontendPlugin.cpp
- lib/Option.cpp
- lib/SPIRVProducerPass.cpp
- test/PushConstant/arrays.cl
- test/PushConstant/max_size_execeed_cluster.cl
- test/PushConstant/max_size_exeeded.cl
- test/PushConstant/two_ints.cl
- test/PushConstant/two_kernels_different_pc.cl
- test/PushConstant/two_kernels_share_pc.cl
Contributes to #529 
Support passing POD arguments via push constants.
New options:
* -pod-pushconstant: instruct the compiler to pass pod args in push constants
* requires clustered pod args 
* cannot be used with module scope push constants
* cannot be used with ubo pod args
* does not support arrays currently
* -max-pushconstant-size: specify the max size of push constants
* verified in the frontend
* default to Vulkan minimum of 128B
Changes:
* updated docs
*  cluster pod kernel args now records pod arg kinds correctly
* simplified uses throughout the flow since it is more reliable now
*  allocate descriptors can allocate push constant pods
> POD arguments in push constants

- lib/SPIRVProducerPass.cpp
- test/VaryingLocalSizes/one_kernel.cl
- test/VaryingLocalSizes/two_kernels.cl
* Create SPIRV Module Sections for SPIRVInstructions according to 2.4 of the spec.
* Sections: Capabilities, Extensions, Imports, MemoryModel, EntryPoints, ExecutionModes, Debug, Annotations, Types, Constants, GlobalVariables, Functions
* This removes the need for looking up where to insert OpDecorates
Phase1 enhancement for issue #545
> SPIRVProducerPass refactor - phase1

- docs/OpenCLCOnVulkan.md
- include/clspv/DescriptorMap.h
- include/clspv/SpecConstant.h
- lib/AllocateDescriptorsPass.cpp
- lib/CMakeLists.txt
- lib/Constants.h
- lib/DescriptorMap.cpp
- lib/SPIRVProducerPass.cpp
- lib/SpecConstant.cpp
- lib/SpecConstant.h
- test/workgroup_size_spec_ids.cl
* Specializations ids recorded in metadata
* used to generate new descriptor map entries
* Changed local memory spec ids to use new allocation method
* Added new enum for specialization constants
* currently only workgroup size is added to the descriptor map
Example:
```
spec_constant,workgroup_size_x,spec_id,0
spec_constant,workgroup_size_y,spec_id,1
spec_constant,workgroup_size_z,spec_id,2
```
> Add generic support to allocate spec ids

- CMakeLists.txt
- kokoro/scripts/linux/build-amber.sh
- kokoro/scripts/linux/build-clvk.sh
- kokoro/scripts/linux/build.sh
- lib/AllocateDescriptorsPass.cpp
- lib/ComputeStructuredOrder.cpp
- lib/DefineOpenCLWorkItemBuiltinsPass.cpp
- lib/FrontendPlugin.cpp
- lib/MultiVersionUBOFunctionsPass.cpp
- lib/ReplaceLLVMIntrinsicsPass.cpp
- lib/ReplaceOpenCLBuiltinPass.cpp
- lib/ReplacePointerBitcastPass.cpp
- lib/RewriteInsertsPass.cpp
- lib/SignedCompareFixupPass.cpp
- lib/SplatArgPass.cpp
- test/WorkItemBuiltins/get_global_offset-push-constant-non-constant-dim.cl
* Add compiler error to clang and gcc for unused variables
* Remove unused variables throughout the code
* Fix a bug in get_global_offset that potentially accessed out-of-bounds
memory
* updated related test
* Fixed some deprecated uses of CreateShuffleVector
> Remove unused variables

- kokoro/scripts/linux/build-amber.sh
- kokoro/scripts/linux/build-clvk.sh
Swiftshader will need >=3.13.0 so unifying how clvk and amber bots build.
> Unify cmake handling for builds that use swiftshader

- lib/ReplaceOpenCLBuiltinPass.cpp
- test/prefetch.ll
Beneficial prefetch strategies are likely to vary significanly with
devices. For now, just add a do-nothing implementation to make it
possible to compile programs that use prefetch.
> Add a do-nothing implementation of the prefetch built-in function

- docs/OpenCLCOnVulkan.md
- include/clspv/Option.h
- include/clspv/PushConstant.h
- lib/DeclarePushConstantsPass.cpp
- lib/DefineOpenCLWorkItemBuiltinsPass.cpp
- lib/PushConstant.cpp
- lib/SPIRVProducerPass.cpp
- test/WorkItemBuiltins/get_global_id-non-uniform.cl
- test/WorkItemBuiltins/get_global_size-non-uniform.cl
- test/WorkItemBuiltins/get_group_id-non-uniform.cl
- test/WorkItemBuiltins/get_num_groups-non-uniform.cl
- test/reqd_work_group_size-non-uniform.cl
- test/reqd_work_group_size.cl
This implementation uses the approach outlined in #522 and push constants
for all the values that need to be communicated by the application/runtime.
The push constant space required is quite large in the worst case (which is
unlikely to be a common occurrence in typical code). There are definitely
applications where using specialisation constants everywhere would result
in a ridiculous amount of recompilation and likely others where saving some
push constant space would be a win (especially once POD arguments will
use push constants).
The CTS tests require that reqd_work_group_size be treated not as a hard
requirement but more as an upper bound/hint which seems odd. I've created
https://github.com/KhronosGroup/OpenCL-Docs/issues/267 to discuss this.
This change satisfies the CTS and is …
> Initial support for non-uniform NDRanges

- lib/AllocateDescriptorsPass.cpp
- lib/ArgKind.cpp
- lib/ArgKind.h
- lib/ClusterPodKernelArgumentsPass.cpp
- lib/Constants.h
- lib/SPIRVProducerPass.cpp
- test/multiple_local_ptr_args.cl
Fixes #577
* Only assign spec ids in AllocateDescriptorMap
* Remove spec ids from the kernel arg map
* when setting up the descriptor map with the kernel arg map use the
module metadata created in AllocateDescriptorMap
* test
> Fix local arg spec id assignment

- docs/OpenCLCOnVulkan.md
- include/clspv/Option.h
- include/clspv/SpecConstant.h
- lib/DeclarePushConstantsPass.cpp
- lib/DefineOpenCLWorkItemBuiltinsPass.cpp
- lib/Option.cpp
- lib/PushConstant.cpp
- lib/PushConstant.h
- lib/SPIRVProducerPass.cpp
- lib/SpecConstant.cpp
- test/WorkItemBuiltins/get_global_id-with-global-offset-push-constant.cl
- test/WorkItemBuiltins/get_global_id-with-global-offset-spec-constant.cl
- test/WorkItemBuiltins/get_global_offset-push-constant-non-constant-dim.cl
- test/WorkItemBuiltins/get_global_offset-push-constant.cl
- test/WorkItemBuiltins/get_global_offset-spec-constant-non-constant-dim.cl
- test/WorkItemBuiltins/get_global_offset-spec-constant.cl
Contributes to #529
* -global-offset will now generate either a spec constant or push
constant
* push constant is used for OpenCL 2.0 and OpenCL C++
* push constant can be forced with -global-offset-push-constant
* global offset as a spec constant generates a private variable with
spec constant initializer
* new SpecConstant enum values for x, y and z dimensions of global
offset
* refactored some logic for push constants
* updated docs
* new tests
> Add ability to generate global offset as spec constant

- lib/SPIRVProducerPass.cpp
- test/CPlusPlus/generic-addrspace.cl
- test/CPlusPlus/object-and-overload.cl
- test/UBO/constant_and_image.cl
- test/UBO/transform_local.cl
- test/ptr_local_struct.cl
- test/ptr_local_struct_cluster_pod_args.cl
* addSPIRVInst for creating/inserting new SPIRVInstruction
* Creates/manages ResultID based on spv::HasResultAndType in one place (almost, nextID still used for second pass)
* Consolidated on SmallVector storage for SPIRVOperandVec (replaces SPIRVOperandList)
* Consolidated Workgroup variable creation
Enhancement for clspv issue #545
> SPIRVProducerPass refactor - phase2

- docs/OpenCLCOnVulkan.md
- include/clspv/Option.h
- kokoro/check-format/build.sh
- lib/AutoPodArgsPass.cpp
- lib/FrontendPlugin.cpp
- lib/Layout.cpp
- lib/Option.cpp
- lib/ReplaceOpenCLBuiltinPass.cpp
- test/AutoPodArgs/array_prevents_push_constants.ll
- test/AutoPodArgs/no_16bit_push_constant.ll
- test/AutoPodArgs/no_16bit_ubo_pushconstant.ll
- test/AutoPodArgs/no_8bit_push_constant.ll
- test/AutoPodArgs/no_8bit_ubo_pushconstant.ll
- test/Diagnostics/no-pushconstant-16bit.cl
- test/Diagnostics/no-pushconstant-8bit.cl
- test/Diagnostics/no-ssbo-16bit.cl
- test/Diagnostics/no-ssbo-8bit.cl
- test/Diagnostics/no-ubo-16bit.cl
- test/Diagnostics/no-ubo-8bit.cl
- test/HalfStorage/vload_half_pointer_cast_from_short.cl
- test/HalfStorage/vstore_half_pointer_cast_to_short.cl
- test/HalfStorage/vstore_half_without_16bit_storage_uses_atomic_xor.cl
Contributes to #529
* Remove -f16bit_storage in favour of new options
* updated uses
* New options to restrict which storage classes support 8- and 16-bit
types
* -no-storage-16bit and -no-storage-8bit
* Default behaviour assumes support for all storage classes
* Added frontend diagnostics to check 8- and 16-bit storage support of
kernel arguments
* Modified pod arg determination to check storage class support
* Added a restriction to not generate push constant pod args if pod args
contain an array
* Added tests
> Add fine-grained storage restrictions

- lib/Compiler.cpp
- test/PushConstant/pod_vs_module_scope.cl
This check was not updated when global offsets were moved to spec constants.
> Fix check for module-scope push constants

- lib/UndoTruncatedSwitchConditionPass.cpp
- test/widen_switch_condition_binary_ops.ll
- test/widen_switch_condition_trunc.ll
We were previously inserting a mask only after binary operations,
instead of after every trunc instruction.
> Fix trunc removal in UndoTruncatedSwitchCondition

- include/clspv/Passes.h
- lib/CMakeLists.txt
- lib/Compiler.cpp
- lib/Passes.cpp
- lib/Passes.h
- lib/UndoTruncateToOddIntegerPass.cpp
- lib/UndoTruncatedSwitchConditionPass.cpp
- test/clspv-opt/options.ll
- test/widen_mixed_truncate.ll
- test/widen_switch_condition_binary_ops.ll
- test/widen_switch_condition_trunc.ll
- test/widen_truncate.ll
- test/widen_truncate_to_i32.ll
- test/widen_truncate_to_i8.ll
Fixes #583
* Changes UndoTruncatedSwitchPass to look for truncates to look for
truncates to non-power-of-2 integer sizes instead of switches on odd
sizes
* rename pass
* new logic to update instructions that aren't full rewritten
* new tests
The first commit has the heart of the changes. The second commit just renames things.
> Expand functionality to catch odd truncates

- include/clspv/PushConstant.h
- lib/AutoPodArgsPass.cpp
- lib/ClusterPodKernelArgumentsPass.cpp
- lib/DeclarePushConstantsPass.cpp
- lib/HideConstantLoadsPass.cpp
- lib/PushConstant.cpp
- lib/PushConstant.h
- lib/SPIRVProducerPass.cpp
- test/AutoPodArgs/array_prevents_push_constants.ll
- test/AutoPodArgs/enqueued_local_size_prevents_push_constant.ll
- test/AutoPodArgs/fallback_on_ssbo.ll
- test/AutoPodArgs/no_16bit_push_constant.ll
- test/AutoPodArgs/no_16bit_ubo_pushconstant.ll
- test/AutoPodArgs/no_8bit_push_constant.ll
- test/AutoPodArgs/no_8bit_ubo_pushconstant.ll
- test/AutoPodArgs/other_push_constants_prevent_global_push_constants.ll
- test/AutoPodArgs/use_global_push_constant.ll
- test/PushConstant/cluster_global_pod_args-arrays.ll
- test/PushConstant/cluster_global_pod_args-int.ll
- test/PushConstant/cluster_global_pod_args-scalars.ll
- test/PushConstant/cluster_global_pod_args-short_array.ll
- test/PushConstant/cluster_global_pod_args-structs.ll
- test/PushConstant/cluster_global_pod_args-vectors.ll
- test/PushConstant/global_push_constant_pod_args-halfs.cl
- test/PushConstant/global_push_constant_pod_args-scalars.cl
- test/PushConstant/global_push_constant_pod_args.cl
- tools/clspv-opt/main.cpp
Contributes to #529 
* AutoPodArgsPass can now decide to put pod kernel arguments into a type mangled structure shared by all kernels with that style of pod arg implementation
* The heavy lifting is in ClusterPodKernelArgumentsPass
* for this style pod args are removed from the kernel, but still appear in the kernel arg map
* instead the pod args are implemented as a struct of integers in the same variable that holds the other global push constants (e.g. region offset)
* only considers unpacked struct sizes right now
* offsets account for global push constants also being present
* When generating the wrapper function, the pass converts an appropriate number of integers back into the appropriate type
* the type conversion does a pretty good job of generating a minimal number of …
> Support global type-mangled pod args in push constants

- lib/FrontendPlugin.cpp
- test/Diagnostics/no-ssbo-16bit.cl
- test/Diagnostics/no-ssbo-8bit.cl
- test/Diagnostics/relax_16bit_pod_arg_check.cl
* Allow clustered pod args in ssbo to work despite contradictory command
line options assuming type mangled push constants will succeed
* fix tests
> Relax frontend 8- and 16-bit type check

- amber/hack_scf/sclamp.amber
- amber/hack_scf/smax.amber
- amber/hack_scf/smax_vector.amber
- amber/hack_scf/smin.amber
- lib/SignedCompareFixupPass.cpp
- test/hack_scf/sclamp.ll
- test/hack_scf/smax.ll
- test/hack_scf/smin.ll
Fixes #593
* smax, smin and sclamp now get replaced when -hack-scf is specified
* they are broken down to compare and select operations
* the compare is then replaced like the other comparisons
* new tests
> Handle smax, smin and sclamp in -hack-scf

- lib/Compiler.cpp
- test/global-variable-no-undef-initializer.cl
- test/loop_continue_no_selection_merge.cl
- test/no_pre_sampler.cl
Fixes #594
* Disable PRE in GVN
* add a test
I think this is good generally. PRE might be beneficial in some circumstances, but it seems like that decision should be made by the driver. 
I have previously given some guidance to disable it to some users which is why I attempt to detect if they have been added to the command line (multiple occurrences cause an error).
> Disable PRE in GVN

- kokoro/scripts/windows/build.bat
- kokoro/windows-msvc-2019-release/build.bat
- kokoro/windows-msvc-2019-release/continuous.cfg
- kokoro/windows-msvc-2019-release/presubmit.cfg
- lib/SPIRVProducerPass.cpp
Update windows build scripts to utilize the new VM image differences. Add scripts for MSVC 2019 (not currently enabled).
> Update msvc 2017

- tools/clspv-opt/CMakeLists.txt
Link against LLVMSupport to fix this issue:
clspv-opt.dir/main.cpp.o: undefined reference to symbol '_ZTVN4llvm2cl11OptionValueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE'
libLLVMSupport.so.11git: error adding symbols: DSO missing from command line
This only affects shared library builds.
Add transitive dependencies as well to ensure check-spirv works out of
the box with shared library build.
> Fix missing link reference to build clspv-opt

- lib/ReplaceOpenCLBuiltinPass.cpp
- lib/SPIRVProducerPass.cpp
- test/CommonBuiltins/max/half2_fmax.cl
- test/CommonBuiltins/max/half3_fmax.cl
- test/CommonBuiltins/max/half4_fmax.cl
- test/CommonBuiltins/max/half_fmax.cl
- test/CommonBuiltins/min/half2_fmin.cl
- test/CommonBuiltins/min/half3_fmin.cl
- test/CommonBuiltins/min/half4_fmin.cl
- test/CommonBuiltins/min/half_fmin.cl
- test/MathBuiltins/fmax/float2_fmax.cl
- test/MathBuiltins/fmax/float3_fmax.cl
- test/MathBuiltins/fmax/float4_fmax.cl
- test/MathBuiltins/fmax/float_fmax.cl
- test/MathBuiltins/fmin/float2_fmin.cl
- test/MathBuiltins/fmin/float3_fmin.cl
- test/MathBuiltins/fmin/float4_fmin.cl
- test/MathBuiltins/fmin/float_fmin.cl
- test/MathBuiltins/fract/float2_fract_private.cl
- test/MathBuiltins/fract/float3_fract_private.cl
- test/MathBuiltins/fract/float4_fract_private.cl
- test/MathBuiltins/fract/float_fract_private.cl
OpenCL C fmax/fmin maps to GLSL SPIR-V instruction NMax/NMin due to the
behaviour requirement on NaN inputs.
Applies by transitivity to OpenCL C fract.
> Use NMax/NMin for fmax/fmin (#506)

- tools/reflection/ReflectionParser.cpp
Prevents warning and errors about implicit fall throughs
> Add missing break

- lib/Compiler.cpp
- lib/ReplacePointerBitcastPass.cpp
- test/PointerCasts/canonical_pointer.ll
Fixes #619
* When a pointer to the first element of an array is the source of a
bitcast, generate a gep to unwrap the arrays and generate a new
bitcast for handling
* Added a test
* Added an extra pass of DCE since ReplaceLLVMIntrinsics leaves dead
code around
> Replace pointer bitcasts should handle array sources better

- CMakeLists.txt
- lib/CMakeLists.txt
- test/clspv-opt/options.ll
- tools/clspv-opt/CMakeLists.txt
- tools/reflection/CMakeLists.txt
I've noticed some issues with the build process. Namely, the available options were not the same for a static build than for a shared build. For example, the `--MultiVersionUBOFunctions` option of `clspv-opt` wasn't available in a static build. I had exactly the same issue for the pass I want to introduce for #613 so here is a general fix.
I also had to fix compilation for shared build. I tested this using `cmake --target check-spirv` with the four {Debug,Release} x {shared,static} configurations on Linux.
Below are the commit messages for the two commits in this PR.
---
1. Improve support for shared build
Fix compilation for clspv-reflection when doing a shared-library build.
- Add clspv_passes to the public list of dependencies of clspv_core so
that clspv-opt, clspv-reflection and any …
> Various improvements to the compilation process

- lib/SimplifyPointerBitcastPass.cpp
- test/PointerCasts/non_pointer_cast.ll
Ignore non-trivial casts on non-pointer types.
Add test covering this.
Developed independently of #624 but seems to address the issue as well.
> Improve SimplifyPointerBitcastPass

- include/clspv/Compiler.h
- lib/Compiler.cpp
Also stop printing the log to stderr.
> Enable CompileFromSourceString to return a build log

- lib/SPIRVProducerPass.cpp
- test/LLVMIntrinsics/unreachable.ll
This is quiet handy to have, especially when using `bugpoint` and `clspv-opt` to reduce some LLVM IR module when working on a pass.
> Map llvm.unreachable to OpUnreachable

- lib/SPIRVProducerPass.cpp
- test/PointerAccessChains/pointer_array_stride_16.cl
- test/PointerAccessChains/pointer_array_stride_32.cl
- test/PointerAccessChains/pointer_index_is_constant_1.cl
- test/ProgramScopeConstants/constant_array_with_function_call.cl
Fixes #637
* Pointer type for the base operand of an OpPtrAccessChain requires
array stride, not the result of the pointer access chain
* added some new tests
* Fixed various lint warnings
* use empty() instead of size() compared to zero
* remove some empty lines
* remove unnecessary semi-clolons
* Fix typo in a test
> Fix how ArrayStride is generated for pointers

- lib/LongVectorLoweringPass.cpp
- test/LongVectorLowering/add.ll
- test/LongVectorLowering/and.ll
- test/LongVectorLowering/frem.ll
- test/LongVectorLowering/lshr.ll
This PR continues adding support for lowering long-vectors (#613) with three commits: 1) lower `BinaryOperator`, 2) cache lowering results, 3) remove dead instructions (i.e. instruction that were lowered and therefore cached).
Later commits will bring support for many additional instructions using `InstVisitor`. This is left out for now to make this patch smaller and easier to review.
Because only `BinaryOperator`s are lowered, their operand are still long-vector. Hence, temporary instructions are generated to read those vectors and create equivalent aggregates, and vice-versa for the value generated by the binary operator. This is done in order to keep generating valid LLVM modules and won't be necessary in the future when operands are recursively visited and more kinds of instructions …
> Lower BinaryOperator instructions on long-vector

- lib/SpecializeImageTypes.cpp
- test/SpecializeImageTypes/convert_write_only_with_no_uses.ll
- test/SpecializeImageTypes/no_duplicate_storage_image_type.cl
Fixes #648
* Convert write_only images to read_write images in OpenCL 2.0 and later
even when a specialization of the image is not found
> Convert write_only images in CL2.0 and later for unspecialized images

- lib/LongVectorLoweringPass.cpp
- test/LongVectorLowering/fadd.ll
- test/LongVectorLowering/fdiv.ll
- test/LongVectorLowering/function.ll
This brings support for user-defined functions that have long-vectors as parameters and/or return type, improving support for lowering long-vectors (#613).
New tests cover this feature but also increase testing coverage of `BinaryOperators` with `fadd` and `fdiv`.
> Lower function parameters and return type

- include/clspv/Option.h
- lib/Compiler.cpp
- lib/Option.cpp
- lib/SPIRVProducerPass.cpp
- test/opsource.cl
Always enable support for non-uniform work-groups when compiling as
CL3.0.
> Add support for -cl-std=CL3.0

- lib/SPIRVProducerPass.cpp
- test/different_address_space_same_function_type.cl
- test/different_address_space_same_pointer_array_stride.cl
Fixes #651
* Prevent duplicate types and decorations from being generated for
equivalent pointer types
* Due to the shared mapping of __global and __constant to
StorageBuffer, type-based containers need extra uniquing to ensure
equivalent types don't result in invalid SPIR-V
* getSPIRVType no uses a helper function, EquivalentType to see in the
appropriate __global or __constant pointer has already been
generated
* ArrayStride decorations now check based on the resulting SPIR-V
result id instead of the LLVM type
> Prevent duplicate types and decorations

- lib/ReplaceOpenCLBuiltinPass.cpp
- test/convergent_attribute.ll
* When replacing barriers and memory fences, add the convergent
attribute to the spirv.op function
The convergent attribute indicates that the functions should not be moved into control flow with more dependencies.
> Add convergent attribute in more cases

- lib/LongVectorLoweringPass.cpp
- test/LongVectorLowering/constants.ll
- test/LongVectorLowering/elements.ll
- test/LongVectorLowering/shufflevector/shufflevector1.ll
- test/LongVectorLowering/shufflevector/shufflevector2.ll
- test/LongVectorLowering/shufflevector/shufflevector3.ll
- test/LongVectorLowering/shufflevector/shufflevector4.ll
- test/LongVectorLowering/shufflevector/shufflevector5.ll
- test/LongVectorLowering/shufflevector/shufflevector6.ll
- test/LongVectorLowering/shufflevector/shufflevector7.ll
The first commit is almost a NFC. It refactors the code to use InstVisitor to make the pass more modular. In future commits, support for a new instruction will be added with a new method overriding InstVisitor's default behaviour. The only change is that the pass will no longer print "Value not handled" (or any other message) for instruction that do not need handling, as determined by `handlingRequired`.
The second commit recursively visits instructions and lowers their operands. It adds support for a few additional kind of instructions and constants, with tests covering these, that, together with the existing support for BinaryOperator, allow turning on assertion/llvm_unreachable to alert users about features not yet supported.
> Recusiverly lower instructions

- lib/ReplaceOpenCLBuiltinPass.cpp
* Remove (effectively) duplicate implementation of rotate
* Implement in terms of more generic funnel shift left
Rotate tests pass. Cleans up duplication introduced in #650.
> Implement rotate in terms of llvm.fshl

- lib/LongVectorLoweringPass.cpp
- test/LongVectorLowering/fastmathflags.ll
- test/LongVectorLowering/fmuladd.ll
- test/LongVectorLowering/function.ll
Continuing on #613, this patch brings support for function calls with long vectors as arguments or return type.
It also adds support for `fmuladd`. Other intrinsics are left out of this prototype but the existing code should easily scale to support them.
Support for (some) OpenCL builtins will be added in a later PR.
> Lower function call and initial support for LLVM intrinsics

- docs/OpenCLCOnVulkan.md
- lib/ReplaceOpenCLBuiltinPass.cpp
- lib/SPIRVProducerPass.cpp
- test/RelationalBuiltins/isordered/double2_isordered.ll
- test/RelationalBuiltins/isordered/double_isordered.ll
- test/RelationalBuiltins/isordered/double_spirv.cl
- test/RelationalBuiltins/isordered/float2_isordered.ll
- test/RelationalBuiltins/isordered/float_isordered.ll
- test/RelationalBuiltins/isordered/float_spirv.cl
- test/RelationalBuiltins/isordered/half2_isordered.ll
- test/RelationalBuiltins/isordered/half_isordered.ll
- test/RelationalBuiltins/isordered/half_spirv.cl
- test/RelationalBuiltins/isunordered/double2_isunordered.ll
- test/RelationalBuiltins/isunordered/double_isunordered.ll
- test/RelationalBuiltins/isunordered/double_spirv.cl
- test/RelationalBuiltins/isunordered/float2_isunordered.ll
- test/RelationalBuiltins/isunordered/float_isunordered.ll
- test/RelationalBuiltins/isunordered/float_spirv.cl
- test/RelationalBuiltins/isunordered/half2_isunordered.ll
- test/RelationalBuiltins/isunordered/half_isunordered.ll
- test/RelationalBuiltins/isunordered/half_spirv.cl
* Implement in terms of `fcmp ord` and `fcmp uno` respectively followed
by an extension
* SPIRVProducer support for `fcmp ord` and `fcmp uno` in terms of
OpIsNan
* tests
* Passes OpenCL CTS for float, float2 and float4
> Implement isordered and isunordered

- docs/OpenCLCOnVulkan.md
- lib/ReplaceOpenCLBuiltinPass.cpp
- test/RelationalBuiltins/islessgreater/islessgreater_double.ll
- test/RelationalBuiltins/islessgreater/islessgreater_double2.ll
- test/RelationalBuiltins/islessgreater/islessgreater_float.ll
- test/RelationalBuiltins/islessgreater/islessgreater_float2.ll
- test/RelationalBuiltins/islessgreater/islessgreater_half.ll
- test/RelationalBuiltins/islessgreater/islessgreater_half2.ll
- test/RelationalBuiltins/isnotequal_float.cl
- test/RelationalBuiltins/isnotequal_float2.cl
- test/RelationalBuiltins/isnotequal_float3.cl
- test/RelationalBuiltins/isnotequal_float4.cl
* Update docs
* islessgreater is implemented as `fcmp one`
* Fixed a bug in isnotequal
* Changed to `fcmp une` instead of `fcmp one`
* Simplied `replaceRelational` to use an extension instead of select
* Re-tested math brute force and relational CTS for all affected
functions
> Implement islessgreater

- cmake/strip_banned_opencl_features.py
- lib/LongVectorLoweringPass.cpp
- test/LongVectorLowering/bitcast.ll
- test/LongVectorLowering/builtinfunctions.cl
- test/LongVectorLowering/memory.ll
- test/VectorLoadStore/vload16_global_float16.cl
- test/VectorLoadStore/vload8_global_float8.cl
- test/VectorLoadStore/vstore16_global_float16.cl
- test/VectorLoadStore/vstore8_global_float8.cl
Continuing on #613, this time lowering a few additional kind of instructions (AllocaInst, CastInst, LoadInst and StoreInst) which enable lowering of OpenCL vload/vstore builtin functions.
I've also replaced `isa<ConstantAggregateZero>(Cst)` with `Cst.isZeroValue()` to cover more cases ellegantly.
> Lower OpenCL vloadN and vstoreN

- lib/ReplaceOpenCLBuiltinPass.cpp
- test/MathBuiltins/fdim/fdim_double.ll
- test/MathBuiltins/fdim/fdim_double2.ll
- test/MathBuiltins/fdim/fdim_float.ll
- test/MathBuiltins/fdim/fdim_float2.ll
- test/MathBuiltins/fdim/fdim_half.ll
- test/MathBuiltins/fdim/fdim_half2.ll
* fdim requires an unordered comparison as it should return a NaN if
either input is a NaN
* add lit tests
* Passes OpenCL CTS for float
> Implement fdim

- lib/Builtins.cpp
- lib/Builtins.h
- lib/LongVectorLoweringPass.cpp
- test/CommonBuiltins/max/float8_max.cl
- test/IntegerBuiltins/max/max_int8.cl
- test/IntegerBuiltins/max/max_ushort8.cl
- test/LongVectorLowering/builtinfunctions.cl
This adds logic to lowers OpenCL builtin functions. For now, only `max` (for `float` and `int`) is supported.
The first commit uses the short-term approach I've described in #613. The second commit actually improves on that by re-using some parts of `clspv::Builtins`. Because the de-mangling process is lossy, it is not possible to produce mangled names for all cases right now, but it should be good enough for the purpose of lowering of most (if not all) builtin functions.
Note that the new overload `GetMangledFunctionName(const Builtins::FunctionInfo &info)` handles signedness of parameters while the existing `GetMangledFunctionName(const char *name, llvm::Type *type)` does not. This ensures `SMax` is still used after lowering, and not `UMax`.
Let me know what you think.
> Lowers OpenCL builtin functions

- lib/Builtins.cpp
- lib/ReplaceLLVMIntrinsicsPass.cpp
- lib/ReplaceOpenCLBuiltinPass.cpp
- lib/SPIRVOp.cpp
- lib/SPIRVProducerPass.cpp
- test/IntegerBuiltins/clz/char2_clz.ll
- test/IntegerBuiltins/clz/char_clz.ll
- test/IntegerBuiltins/clz/long2_clz.ll
- test/IntegerBuiltins/clz/long_clz.ll
- test/IntegerBuiltins/clz/short2_clz.ll
- test/IntegerBuiltins/clz/short_clz.ll
- test/IntegerBuiltins/ctz/uchar2_ctz.ll
- test/IntegerBuiltins/ctz/uchar_ctz.ll
- test/IntegerBuiltins/ctz/ulong2_ctz.ll
- test/IntegerBuiltins/ctz/ulong_ctz.ll
- test/IntegerBuiltins/ctz/ushort2_ctz.ll
- test/IntegerBuiltins/ctz/ushort_ctz.ll
* Don't replace builtins or intrinsics if they have a definition
* add implmemetations for llvm.trunc
* small change to name mangling
* fix an odd debug assertion in spirvop when reusing another function
Implement clz and ctz via llvm.ctlz and llvm.cttz
* Remove run of llvm intrinsic replacement before opencl builtin
replacement
* add cleaner methodology for replacement ReplaceLLVMIntrinsicsPass
* convert fshl to this style
* All clz and ctz functions are replaced with equivalent llvm intrinsics
* Replace llvm intrinsics implements non-32-bit versions
* update tests
* spirv producer updated to handle more llvm intrinsics
* Rotate, clz and ctz still pass CTS
Refactor copysign support
* Replace opencl builtin with llvm intrinsic
* move copysign implementation to llvm intrinsic replacement
> Refactor some builtin support

- lib/ReplaceLLVMIntrinsicsPass.cpp
- lib/ReplaceOpenCLBuiltinPass.cpp
- lib/SPIRVProducerPass.cpp
- test/MathBuiltins/cospi/cospi_double2.ll
- test/MathBuiltins/cospi/cospi_float.ll
- test/MathBuiltins/cospi/cospi_float2.ll
- test/MathBuiltins/cospi/cospi_half.ll
- test/MathBuiltins/round/float2_round.cl
- test/MathBuiltins/round/float3_round.cl
- test/MathBuiltins/round/float4_round.cl
- test/MathBuiltins/round/float_round.cl
- test/MathBuiltins/sinpi/sinpi_double2.ll
- test/MathBuiltins/sinpi/sinpi_float.ll
- test/MathBuiltins/sinpi/sinpi_float2.ll
- test/MathBuiltins/sinpi/sinpi_half.ll
- test/MathBuiltins/tanpi/tanpi_double2.ll
- test/MathBuiltins/tanpi/tanpi_float.ll
- test/MathBuiltins/tanpi/tanpi_float2.ll
- test/MathBuiltins/tanpi/tanpi_half.ll
* New implementation of round
* glsl extended instruction is insufficient to pass CTS because the
rounding mode is implementation defined
* Passes CTS
* implementations of cospi, sinpi and tanpi
* use llvm.sin and llvm.cos
* not sufficient for full conformance, but passes relaxed requirements
* backend support for llvm.sin, llvm.cos, llvm.fabs, llvm.ceil,
llvm.floor and llvm.rint
> Support more math builtins

- lib/LongVectorLoweringPass.cpp
- test/ConvertBuiltins/char/convert_char16_float16.cl
- test/ConvertBuiltins/float/convert_float8_int8.cl
- test/ConvertBuiltins/half/convert_half8_short8.cl
- test/ConvertBuiltins/int/convert_int8_short8.cl
- test/ConvertBuiltins/short/convert_short8_int8.cl
Continuing submission for #613, this adds support for the various convert_* functions and CastInst instructions. As always, feedback welcome.
---
Add support for various CastInst subclasses.
Introduce tests covering the end-to-end compilation flow for a subset of
the OpenCL convert_* builtin functions. Not all cases are covered to
avoid increasing testing time too much.
> Lower OpenCL convert_* builtin functions

- amber/run_tests.py
- kokoro/scripts/linux/build-amber.sh
* Add an option to specify the Vulkan ICD location
* Update kokoro build to use this option
* Add an option to avoid large globs
* Fix suppressions when only testing a single directory
* Fix delimiter consistency
> Changes to the Amber test runner

- lib/LongVectorLoweringPass.cpp
- test/LongVectorLowering/fastmathflags.ll
- test/LongVectorLowering/icmp.ll
- test/LongVectorLowering/select1.ll
- test/LongVectorLowering/select2.ll
- test/RelationalBuiltins/select/select_float8_uint8.cl
Continuing submission for #613, this adds support for some additional instructions. As always, feedback welcome.
---
Mark PHINode as unsupported for now. Test cases are required to
implement this feature.
Add tests covering icmp and the two forms of select instructions. Add
test covering OpenCL select builtin function. Update fast-math flag
test.
> Lower CmpInst, SelectInst, and OpenCL select()

- include/clspv/Passes.h
There is a small typo in include/clspv/Passes.h.
Should read `variables` rather than `variabls`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, variabls -> variables

- lib/LongVectorLoweringPass.cpp
- test/LongVectorLowering/builtinfunctions.cl
- test/MathBuiltins/exp/float8_exp.cl
- test/MathBuiltins/fma/float8_fma.cl
- test/MathBuiltins/fmax/float8_fmax.cl
- test/MathBuiltins/fmin/float8_fmin.cl
- test/MathBuiltins/frexp/float8_frexp_private.cl
Continuing on #613, this covers builtins similar to max: exp, fma, fmax and fmin, as well as frexp, which has a different signature.
> Lower additional OpenCL builtin functions

- docs/OpenCLCOnVulkan.md
Follow what was done when the reflection non-semantic instructions
and support for mixing kernels with and without the reqd_work_group_size
attribute (3b6097783) were introduced.
> Update work-group size section of the documentation

- lib/FrontendPlugin.cpp
- lib/LongVectorLoweringPass.cpp
- test/CommonBuiltins/max/float8_max.cl
- test/ConvertBuiltins/char/convert_char16_float16.cl
- test/ConvertBuiltins/float/convert_float8_int8.cl
- test/ConvertBuiltins/half/convert_half8_short8.cl
- test/ConvertBuiltins/int/convert_int8_short8.cl
- test/ConvertBuiltins/short/convert_short8_int8.cl
- test/IntegerBuiltins/max/max_int8.cl
- test/IntegerBuiltins/max/max_ushort8.cl
- test/LongVectorLowering/Frontend/lowering_disabled_kernel_param_pointer.cl
- test/LongVectorLowering/Frontend/lowering_enabled_kernel_param_array.cl
- test/LongVectorLowering/Frontend/lowering_enabled_kernel_param_pointer.cl
- test/LongVectorLowering/Frontend/lowering_enabled_kernel_param_scalar.cl
- test/LongVectorLowering/Frontend/lowering_enabled_kernel_param_struct.cl
- test/LongVectorLowering/gep.ll
- test/MathBuiltins/exp/float8_exp.cl
- test/MathBuiltins/fma/float8_fma.cl
- test/MathBuiltins/fmax/float8_fmax.cl
- test/MathBuiltins/fmin/float8_fmin.cl
- test/MathBuiltins/frexp/float8_frexp_private.cl
- test/RelationalBuiltins/select/select_float8_uint8.cl
This brings support for long-vector parameters for kernel functions. To implement this support, I added a limited support for GEPs -- I've updated #613 to list this as a current limitation of the prototype we've designed so far.
> Lower kernel parameters

- lib/SpecConstant.cpp
- test/Reflection/global_size_and_work_dim.cl
Metadata nodes are uniqued by default, which means this counter was
sometimes being merged with other metadata values such as push
constant declarations. Subsequent updates to this counter would then
inadvertently change the type of the push constant.
> Use distinct nodes for clspv.next_spec_constant_id

- lib/SPIRVProducerPass.cpp
- test/ConvertBuiltins/float/convert_float4_relational.cl
- test/ConvertBuiltins/half/convert_half4_relational.cl
* Add sitofp to the special case for i1 conversions to generate an
OpSelect instead of an OpConvertSToF
* Add tests that cause LLVM to generate these instructions
> Handle sitofp with i1 arguments

- lib/LongVectorLoweringPass.cpp
Without this the pass bails when it encounters any array type, even if it does not contain wide vectors.
CC @mantognini: hopefully this doesn't cause you any rebase pain. I assume there is a patch for array types coming later but adding this stub now means that I can start testing this pass on some workloads that I'm looking at now.
> Add stub for array types in the long vector pass

- lib/ArgKind.cpp
"control reaches end of non-void function"
> Fix warning in GetArgKindForPodArgs

- lib/ReplacePointerBitcastPass.cpp
- test/PointerCasts/gep_has_no_user.ll
Do not attempt to remove instructions that were not (yet) replaced but transitively remove dead instructions.
This issue was identified while using bugpoint to reduce some input. This was also identified using bugpoint: https://reviews.llvm.org/D96487, although the two issues are completely unrelated.
I've added a test case that contains the various reduced input I've used while iterating over this bugfix.
> Fix crash in ReplacePointerBitcastPass

- lib/LongVectorLoweringPass.cpp
- test/LongVectorLowering/gep.ll
Support additional forms for getelementptr instructions for the provided use cases: multiple indices and constant expressions.
When lowering globals, keep their name intact.
Related to #613.
> Lower arrays and more GEPs

- lib/CMakeLists.txt
Link against LLVMCodeGen to solve the follow issues when doing a shared-library build:
lib/libclspv_core.so: undefined reference to `llvm::createHardwareLoopsPass()'
lib/libclspv_core.so: undefined reference to `llvm::createCodeGenPreparePass()'
lib/libclspv_core.so: undefined reference to `llvm::createExpandMemCmpPass()'
lib/libclspv_core.so: undefined reference to `llvm::createSafeStackPass()'
The issue was introduce with b41cfd36 (Update LLVM (#711), 2021-02-17).
----
Would it be possible to add a CI job to check shared builds? I'm not familiar with kokoro, but it might be possible to do the following:
1. Modify [kokoro/scripts/linux/build.sh](https://github.com/google/clspv/blob/master/kokoro/scripts/linux/build.sh) by adding `-DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS:-OFF}` to the …
> Address linking issues with shared build

- CMakeLists.txt
- include/clspv/Option.h
- lib/Builtins.cpp
- lib/BuiltinsMap.inc
- lib/CMakeLists.txt
- lib/FixupStructuredCFGPass.cpp
- lib/InlineFuncWithPointerBitCastArgPass.cpp
- lib/LongVectorLoweringPass.cpp
- lib/NormalizeGlobalVariable.cpp
- lib/PushConstant.cpp
- lib/ReplaceOpenCLBuiltinPass.cpp
- lib/ReplacePointerBitcastPass.cpp
- lib/SPIRVOp.cpp
- lib/SPIRVOp.h
- lib/SPIRVProducerPass.cpp
- lib/UndoTruncateToOddIntegerPass.cpp
Include `HandleLLVMOptions` to ensure LLVM and clspv components are compiled using the same defines (for example `-D_FILE_OFFSET_BITS=64` `-D_LARGEFILE_SOURCE`). This essentially fixes this undefined reference to
```
clang::FileManager::getVirtualFile(llvm::StringRef, long, long)
```
while the following was actually defined
```
clang::FileManager::getVirtualFile(llvm::StringRef, long long, long)
```
.
As a consequence, the compilation and link options are updated and require fixes to the dependency lists of `clspv_passes` and `clspv_core`.
The second commit address various warnings:
* `-Wunused-function`: use `inline` instead of `static` in header.
* `-Wunused-but-set-variable`: code is protected in `#ifndef NDEBUG` when it is only used for the purpose of assertions.
* `-Wunused-function` …
> Fix compilation for 32-bit systems

- include/clspv/Option.h
- lib/Option.cpp
- test/reqd_work_group_size-non-uniform.cl
Support non-uniform work-groups in OpenCL 1.x as defined in the cl_arm_non_uniform_work_group_size extension specification.
https://www.khronos.org/registry/OpenCL/extensions/arm/cl_arm_non_uniform_work_group_size.txt
> Add support for cl_arm_non_uniform_work_group_size

- include/clspv/Option.h
- lib/Compiler.cpp
- lib/Option.cpp
- test/Features/cl3-disabled-features.cl
- test/Features/fp16-default.cl
- test/Features/fp16-disabled.cl
- test/Features/fp64-default-cl3.cl
- test/Features/fp64-default.cl
- test/Features/fp64-disabled-cl3.cl
- test/Features/fp64-disabled.cl
Some OpenCL applications (e.g. clpeak) conditionally enable FP16/FP64 in
kernels based on the presence of the cl_khr_fp{16,64} macros. When using
the SPIR target Clang always enables all OpenCL extensions and features
potantially resulting in applications attempting to use features not
supported on the target device.
Since Clang always enables all features when using the SPIR target,
it means that clspv must either pass a list of features to be disabled
to Clang (not sure this would be accepted upstream) or disable features
after the target-specific defaults have been applied. The latter is the
approach proposed in this change: extensions and features are disabled
after the creation of the TargetInfo and before the CompilerInstance
is configured to use it.
The new options are enabled by …
> Add options for fp16 and fp64 and disable unsupported CL3 features

- include/clspv/Option.h
- lib/Compiler.cpp
- lib/Option.cpp
- test/Reflection/uniform_workgroup_size.cl
This PR makes it possible to specify workgroups as uniform to disable some push constants' emission on frontends of variety.
Using SPIR-V generated by `clspv` with C++ frontend enabled from simple Vulkan applications, having push constants emitted for "region offset" included causes vkCreateComputePipelines to throw an unknown error. When layout accommodates these push constant ranges, the error goes away, but this can be unexpected/unnecessary from the application's perspective. Despite what the application developer thinks, some (not all) drivers care about that part of the layout.
Maybe a more holistic (and nicer-looking) solution would be to "optimize away" these push constants when detected as not used by the module, but this works and is explicit.
> Make it possible to specify workgroups as uniform

- include/clspv/Option.h
- include/clspv/Passes.h
- kokoro/scripts/linux/build-clvk.sh
- lib/Compiler.cpp
- lib/Option.cpp
- lib/Passes.cpp
- lib/Passes.h
- lib/ReplaceLLVMIntrinsicsPass.cpp
- lib/SPIRVProducerPass.cpp
- test/Spv1p4/copy.ll
- test/Spv1p4/copy_two_operands.ll
- test/Spv1p4/int_fetch.ll
- test/Spv1p4/int_read.ll
- test/Spv1p4/int_sample.ll
- test/Spv1p4/int_write.ll
- test/Spv1p4/interface_global_push_constant.ll
- test/Spv1p4/interface_global_workgroup.ll
- test/Spv1p4/interface_pod_pushconstant.ll
- test/Spv1p4/interface_private_builtin.ll
- test/Spv1p4/interface_ssbo_resource.ll
- test/Spv1p4/interface_workgroup_resource.ll
- test/Spv1p4/load.ll
- test/Spv1p4/scalar_cond_vector_data.ll
- test/Spv1p4/store.ll
- test/Spv1p4/uint_fetch.ll
- test/Spv1p4/uint_read.ll
- test/Spv1p4/uint_sample.ll
- test/Spv1p4/uint_write.ll
- tools/reflection/main.cpp
Major changes:
* SPIRVProducerPass is now unit testable
* uses a simple constructor and outputs spir-v to a special file (specified via an option)
* SPIR-V 1.4 support
* Layout decorations are only applied to storage buffer, uniform and push constant storage classes
* uses OpCopyLogical to convert aggregates 
* when loading, copying and storing only the memory has a layout and internal values have no layout
* type mapping now tracks laid out and non-laid out versions of the type
* Interfaces include all used global variables
* resources are specific to the entry point
* static globals are added to all entry points
* storage buffer and variable pointer extensions no longer added to 1.3 and higher
* select condition splatting does not happen for 1.4 or higher
* Add ZeroExtend and SignExtend …
> Support SPIR-V 1.4 and 1.5

- lib/LongVectorLoweringPass.cpp
- lib/SPIRVProducerPass.cpp
- test/longvector-metadata.ll
When expanding vectors of 8 or more components, the pass was crashing on instructions with Metadata operands.
Skip trying to handle these instructions.
Also ignore alias scope intrinsic markers when generating output.
> Ignore metadata types on LongVector support

- test/longvector-metadata.ll
The default output file name is causing file permission errors in
downstream builds, so replace with an explicit file name.
> Add test output file for longvector-metadata.ll

- lib/SPIRVProducerPass.cpp
- test/LLVMIntrinsics/smax.ll
- test/LLVMIntrinsics/smin.ll
- test/ProgramScopeConstants/constant_array.cl
- test/Reflection/literal_sampler.cl
- test/UBO/constant_and_image.cl
- test/UBO/copy_nested.cl
- test/UBO/transform_local.cl
- test/VaryingLocalSizes/one_kernel.cl
- test/VaryingLocalSizes/reqd_work_group_size_one_kernel.cl
- test/VaryingLocalSizes/reqd_work_group_size_two_kernels.cl
- test/VaryingLocalSizes/two_kernels.cl
- test/WorkItemBuiltins/get_enqueued_local_size.cl
- test/WorkItemBuiltins/get_global_id-with-global-offset-push-constant.cl
- test/WorkItemBuiltins/get_global_offset-push-constant-non-constant-dim.cl
- test/WorkItemBuiltins/get_global_offset-push-constant.cl
- test/WorkItemBuiltins/get_global_size.cl
- test/WorkItemBuiltins/get_global_size_hack_initializers.cl
- test/WorkItemBuiltins/multiple-push-constant.cl
- test/reuse_kernel_arg_var.cl
* Since the refactor of the producer, the type list is no longer needed
as dependencies are automatically generated correctly
* remove all references to the type list
* update tests to be more agnostic to type declaration order
> Remove the need for the type list

- lib/SPIRVProducerPass.cpp
- test/LLVMIntrinsics/umax.ll
- test/LLVMIntrinsics/umin.ll
LLVM optimisations are generating them as part of loop unrolling
(the test_compiler::pragma_unroll CTS test triggers this behaviour).
> Add support for llvm.{umax,umin} intrinsics

- lib/ClusterConstants.cpp
- lib/Constants.h
- lib/SPIRVProducerPass.cpp
- test/Spv1p4/function-pointer-parameter-that-needs-layout.ll
- test/Spv1p4/interface_module_constants_in_storage_buffer.ll
- test/Spv1p4/interface_sampler.ll
- test/Spv1p4/pod-in-ubo.ll
- Add literal samplers to the entry point interface lists.
- Add the constant args buffer to the interface lists when present.
- Add Uniform to the list of address spaces to which pointers always require layout.
- Don't generate duplicate types when functions with pointer arguments in storage
classes that require layout are present. When generating OpTypeFunction, types for
parameters were always generated with needs_layout = false, potentially leading to
duplicate types when the type with explicit layout was otherwise produced.
These fixes enable clvk to use SPIR-V 1.5 with no OpenCL CTS tests regressions.
> A few fixes to SPIR-V 1.4 support

- lib/SPIRVProducerPass.cpp
- test/Spv1p4/interface_literal_sampler_in_helper.ll
- test/Spv1p4/interface_sampler.ll
- test/Spv1p4/opaque_structs.ll
Fixes #753
Fixes #754
* Ensure opaque structs are not considered to have a layout
* Add all literal samplers to all entry points
> SPIR-V 1.4 fixes

- include/clspv/Option.h
- lib/Option.cpp
The corresponding Vulkan limits are uint32_t values and some implementations
report values greater than INT_MAX
See https://github.com/kpet/clvk/issues/318
> Fix type for --max-ubo-size and --max-pushconstant-size options

- lib/SPIRVProducerPass.cpp
- test/Spv1p4/pointer_comparisons.ll
- test/Spv1p4/pointer_comparisons_with_null.ll
- test/Spv1p4/pointer_comparisons_workgroup.ll
No attempt was made to validate that the operands to OpPtrDiff are
"pointers to element numbers in [0, L] in the same array". This means
users can easily produce SPIR-V triggering undefined behaviour when
this doesn't hold.
We could maybe check that both pointers are derived from the same resource
var and even check that all but one indices match when pointers are
produced with a single GEP from a resource var.
Fixes #383
> Support some pointer comparisons when targeting SPIR-V 1.4+

- lib/SPIRVProducerPass.cpp
- lib/Types.cpp
- lib/Types.h
Done as part of looking at what is needed to support 1D buffer images.
- Add variants of functions in type utilities that take a StructType
- Centralise queries based on image type names
> Tidy up handling of image types in SPIR-V Producer pass

- lib/AllocateDescriptorsPass.cpp
- lib/ClusterConstants.cpp
- lib/DefineOpenCLWorkItemBuiltinsPass.cpp
- lib/LongVectorLoweringPass.cpp
- lib/MultiVersionUBOFunctionsPass.cpp
- lib/PushConstant.cpp
- lib/ReplaceLLVMIntrinsicsPass.cpp
- lib/ReplaceOpenCLBuiltinPass.cpp
- lib/ReplacePointerBitcastPass.cpp
- lib/UndoInstCombinePass.cpp
These are being removed in upstream LLVM, breaking the build
https://github.com/llvm/llvm-project/commit/89eb85ac6eab6431ef72ef705d560c72c5ed71f3
> Migrate clspv off deprecated llvm::IRBuilder APIs

- lib/CMakeLists.txt
Using BUILD_SHARED_LIBS forces all libraries to be built as shared
libraries. This can drastically reduce the time spent on linking
and thus iteration time.
> Make it possible to build with BUILD_SHARED_LIBS

- lib/ReplacePointerBitcastPass.cpp
- test/PointerCasts/load_cast_array_of_array.ll
- test/PointerCasts/load_cast_array_of_array_int_to_long.ll
- test/PointerCasts/load_cast_array_of_array_local.ll
- test/PointerCasts/store_cast_array_of_array.ll
- test/PointerCasts/store_cast_array_of_array_int_to_long.ll
- test/PointerCasts/store_cast_array_of_array_local.ll
When a bitcast of an array of array followed by a gep is detected,
generated a new gep that consider each dimension of the array to
compute the proper indices.
If the source is from the private memory, force the first indice to be
zero (meaning no out-of-bounds possible), as it would be against the
expected spirv behavior later.
> ReplacePointerBitCast: manage indices for gep on multi-dim arrays

- include/clspv/Option.h
- lib/Compiler.cpp
- lib/Option.cpp
- lib/ThreeElementVectorLoweringPass.cpp
no-vec3-to-vec4 takes priority over vec3-to-vec4 as it intends to
avoid running into bugs in the vec3 pass implementation.
Ref #795
> vec3: add option to force disabling of the vec3 pass

- lib/SPIRVProducerPass.cpp
- test/int_mod.cl
For the OpSRem and OpSMod instructions, if either operand is negative
the result is undefined.
https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/chap46.html#spirvenv-precision-operation
> SRem: manage signed modulus explicitly

- lib/Compiler.cpp
Shares core logic between Compile and CompileFromSourceString to
allow for some previously unsupported options in
CompileFromSourceString such as support for input languages
other than OpenCL and outputting to a file.
> Allow for all options in CompileFromSourceString

- lib/Compiler.cpp
- test/composite_construct_varying.cl
- test/thread_id_kernel.ll
Redundant load/store instructions would affect the address space inference, so rearranged
the SROAPass to be in front of InferAddressSpacesPass to get rid of them.
Added test for LLVM IR to SPIRV to represent our use-case.
The SROAPass also simplified the code for aggregates and broke the assumption of another
test, updated that test.
> Fix address space inference

- lib/SPIRVProducerPass.cpp
- test/int_mod.cl
at the moment signed modulo are transform in clspv:
a % b = (abs(a) % abs(b)) * (a>0 ? 1 : -1)
Using OpSRem to perform the modulo creates a bug when 'a' is TYPE_MIN.
abs((signed)TYPE_MIN) => (unsigned)UTYPE_MAX => (signed)TYPE_MIN.
It leds to wrong output on some GPUs.
Let's use OpUMod instead of OpSRem to avoid this issue, as we use abs
before doing the modulo
> fix signed modulo implementation

- lib/ReplaceLLVMIntrinsicsPass.cpp
- test/IntegerBuiltins/rotate/rotate_uchar.cl
- test/IntegerBuiltins/rotate/rotate_uchar2.cl
- test/IntegerBuiltins/rotate/rotate_uchar3.cl
- test/IntegerBuiltins/rotate/rotate_uchar4.cl
- test/IntegerBuiltins/rotate/rotate_uchar_0.cl
- test/IntegerBuiltins/rotate/rotate_uchar_2.cl
- test/IntegerBuiltins/rotate/rotate_uchar_64.cl
- test/IntegerBuiltins/rotate/rotate_uint.cl
- test/IntegerBuiltins/rotate/rotate_uint2.cl
- test/IntegerBuiltins/rotate/rotate_uint3.cl
- test/IntegerBuiltins/rotate/rotate_uint4.cl
- test/IntegerBuiltins/rotate/rotate_ulong.cl
- test/IntegerBuiltins/rotate/rotate_ulong2.cl
- test/IntegerBuiltins/rotate/rotate_ulong3.cl
- test/IntegerBuiltins/rotate/rotate_ulong4.cl
- test/IntegerBuiltins/rotate/rotate_ushort.cl
- test/IntegerBuiltins/rotate/rotate_ushort2.cl
- test/IntegerBuiltins/rotate/rotate_ushort3.cl
- test/IntegerBuiltins/rotate/rotate_ushort4.cl
- test/LLVMIntrinsics/fshl.ll
Some CTS tests fail on some platforms when doing rotate of 0.
This is because rotate ends up to combination of shifts. One of them
being of type size in bits when rotating of 0.
But spirv says that shifting of the type size in bits results in an
undefined behavior.
> fix replaceFshl to avoid spirv undefined behavior

- include/clspv/Option.h
- lib/Option.cpp
- lib/ReplaceOpenCLBuiltinPass.cpp
- lib/SPIRVProducerPass.cpp
- test/hack_mul_extended/mad_hi_char_hack_mul_extended.cl
- test/hack_mul_extended/mad_hi_int_hack_mul_extended.cl
- test/hack_mul_extended/mad_hi_long_hack_mul_extended.cl
- test/hack_mul_extended/mad_hi_short_hack_mul_extended.cl
- test/hack_mul_extended/mad_hi_uchar_hack_mul_extended.cl
- test/hack_mul_extended/mad_hi_uint_hack_mul_extended.cl
- test/hack_mul_extended/mad_hi_ulong_hack_mul_extended.cl
- test/hack_mul_extended/mad_hi_ushort_hack_mul_extended.cl
- test/hack_mul_extended/mul_hi_char2_hack_mul_extended.cl
- test/hack_mul_extended/mul_hi_char_hack_mul_extended.cl
- test/hack_mul_extended/mul_hi_int2_hack_mul_extended.cl
- test/hack_mul_extended/mul_hi_int_hack_mul_extended.cl
- test/hack_mul_extended/mul_hi_long2_hack_mul_extended.cl
- test/hack_mul_extended/mul_hi_long_hack_mul_extended.cl
- test/hack_mul_extended/mul_hi_short2_hack_mul_extended.cl
- test/hack_mul_extended/mul_hi_short_hack_mul_extended.cl
- test/hack_mul_extended/mul_hi_uchar2_hack_mul_extended.cl
- test/hack_mul_extended/mul_hi_uchar_hack_mul_extended.cl
- test/hack_mul_extended/mul_hi_uint2_hack_mul_extended.cl
- test/hack_mul_extended/mul_hi_uint_hack_mul_extended.cl
- test/hack_mul_extended/mul_hi_ulong2_hack_mul_extended.cl
- test/hack_mul_extended/mul_hi_ulong_hack_mul_extended.cl
- test/hack_mul_extended/mul_hi_ushort2_hack_mul_extended.cl
- test/hack_mul_extended/mul_hi_ushort_hack_mul_extended.cl
- test/int_mod.cl
OpMulExtended only works on Intel GPU with 32bit types.
Workaround it with a new option 'hack-mul-extended' which prevents
clspv from using OpMulExtended.
Also change the SRem implementation not to use OpMulExtended all the
time.
> OpMulExtended: workaround Intel GPU issue

- CMakeLists.txt
- May help with https://github.com/google/clspv/pull/834
> Enable ccache if installed with defaults

- include/clspv/Option.h
- lib/Compiler.cpp
- lib/Option.cpp
- lib/SPIRVProducerPass.cpp
- test/Contraction/contract.cl
- test/Contraction/no_contract.cl
* Refactor some math options into Options
* move -cl-unsafe-math-optimziations, -cl-finite-math-only and
-cl-fast-relaxed-math
* add accessors that handle implications
* Change the SPIRVProducer to emit the NoContraction decoration on
OpFMul unless unsafe math is enabled
* this is more in line with where contractions should be allowed in
OpenCL C
* Clang will emit llvm.fmuladd (translated as fma) if contractions are
enabled, otherwise clspv assumes contractions shouldn't be allowed
generally
> Prevent contraction of OpFMul in more cases

- lib/AutoPodArgsPass.cpp
- lib/Builtins.cpp
- lib/Builtins.h
- lib/DefineOpenCLWorkItemBuiltinsPass.cpp
- lib/PushConstant.cpp
- lib/ReplaceOpenCLBuiltinPass.cpp
- lib/ReplaceOpenCLBuiltinPass.h
- lib/UndoByvalPass.cpp
- lib/UndoSRetPass.cpp
- lib/ZeroInitializeAllocasPass.cpp
* Remove uses of pointer element type from:
* UndoSRet
* UndoByval
* AutoPodArgs
* DefineOpenCLWorkItemBuiltins
* ReplaceOpenCLBuiltin
* ZeroInitiailizeAllocas
* Add a new method to parameter info for builtins to rebuild the
described llvm type
* currently only support gentypes
> Remove some uses of pointer element types

- lib/ClusterPodKernelArgumentsPass.cpp
- lib/NormalizeGlobalVariable.cpp
- test/NormalizeGlobalVariables/cluster_constants_opaque.ll
- test/NormalizeGlobalVariables/different_geometry_opaque.ll
- test/NormalizeGlobalVariables/mismatched_depths_opaque.ll
- test/NormalizeGlobalVariables/multiple_uses_opaque.ll
* Remove pointer element type uses in cluster pod kernel arguments
* Make normalize global variables work with both types of pointers
* duplicate IR tests as opaque versions
> Transition to opaque pointers

- lib/LongVectorLoweringPass.cpp
- test/LongVectorLowering/add_sat.ll
- test/LongVectorLowering/sub_sat.ll
- test/LongVectorLowering/uadd_sat.ll
- test/LongVectorLowering/usub_sat.ll
* Recent refactoring (#852) requires handling these llvm intrinsics
* Fixes add_sat and sub_sat OpenCL CTS tests
> Support llvm.{s|u}{add|sub}_sat in long vector lowering

- lib/SPIRVProducerPass.cpp
- lib/Types.cpp
- test/ImageBuiltins/get_image_width_image1d_buffer_readonly.cl
- test/ImageBuiltins/image_1d_buffer.cl
- test/SpecializeImageTypes/read_image1d_buffer_float.ll
- test/SpecializeImageTypes/read_image1d_buffer_int.ll
- test/SpecializeImageTypes/read_image1d_buffer_uint.ll
reading a image1d buffer needs to go through OpImageFetch and not
OpImageRead.
This is because OpImageRead requires the capability ReadWithoutFormat
which is not necessarily implemented on all vulkan compliant driver.
> Fix image1d buffer support

- lib/Constants.h
- lib/DirectResourceAccessPass.cpp
- lib/SPIRVProducerPass.cpp
- lib/Types.cpp
- lib/UBOTypeTransformPass.cpp
- test/Spv1p4/copy.ll
- test/Spv1p4/copy_two_operands.ll
- test/Spv1p4/function-pointer-parameter-that-needs-layout.ll
- test/Spv1p4/int_fetch.ll
- test/Spv1p4/int_read.ll
- test/Spv1p4/int_sample.ll
- test/Spv1p4/int_write.ll
- test/Spv1p4/interface_literal_sampler_in_helper.ll
- test/Spv1p4/interface_module_constants_in_storage_buffer.ll
- test/Spv1p4/interface_pod_pushconstant.ll
- test/Spv1p4/interface_sampler.ll
- test/Spv1p4/interface_ssbo_resource.ll
- test/Spv1p4/interface_workgroup_resource.ll
- test/Spv1p4/load.ll
- test/Spv1p4/opaque_structs.ll
- test/Spv1p4/pod-in-ubo.ll
- test/Spv1p4/pointer_comparisons.ll
- test/Spv1p4/pointer_comparisons_with_null.ll
- test/Spv1p4/pointer_comparisons_workgroup.ll
- test/Spv1p4/scalar_cond_vector_data.ll
- test/Spv1p4/store.ll
- test/Spv1p4/uint_fetch.ll
- test/Spv1p4/uint_read.ll
- test/Spv1p4/uint_sample.ll
- test/Spv1p4/uint_write.ll
* Convert simple cases of getPointerElementType() in SPIRVProducerPass
to finding the type in other ways
* generally uses the data type in the resource functions
* Added an enum for resource function operands
* Fixed a bug in UBOTypeTransformPass that was not properly visiting
constant operands
* This is now frequently covered by resource variable functions
> Transition SPIRVProducer to opaque pointers P1

- README.md
The instructions to rebuild the "clspv--.bc" did not produce the
expected out because of missing whitespace.
> fix README.md formatting

- lib/ClusterPodKernelArgumentsPass.cpp
- lib/DirectResourceAccessPass.cpp
- lib/ReplaceOpenCLBuiltinPass.cpp
- lib/ReplaceOpenCLBuiltinPass.h
- lib/SPIRVProducerPass.cpp
- lib/Types.cpp
- lib/Types.h
- lib/UBOTypeTransformPass.cpp
- test/SPIRVProducer/opaque_buffer_write_zero.ll
- test/SPIRVProducer/opaque_literal_sampler.ll
- test/SPIRVProducer/opaque_local_arg.ll
- test/SPIRVProducer/opaque_pointer_loop.ll
- test/SPIRVProducer/opaque_pointer_parameter.ll
- test/SPIRVProducer/opaque_pointer_return.ll
- test/SPIRVProducer/opaque_pointer_select.ll
- test/SPIRVProducer/opaque_sample_image2d_float.ll
Contributes to #816 
More changes to support opaque pointers in SPIRVProducer:
* Change image type queries to only accept a StructType
* remove the need to get the pointer element
* New tracking in SPIRVProducer for pointer and function types
* both require type inference to correctly generate a typed SPIR-V pointer
* Pointers are mapped aspace -> {element type -> [ids]}
* Functions generate a representative type used to create unique types for type caching
* Fix code generation to handle opaque pointers in
* geps
* functions calls
* function definitions
* select
* phi
* image instructions
* Fixed an issue where we generated a stronger capability than necessary
* Fixed a bug that caused infinite loops in type inference
* Changed how workgroup variable info is gathered to avoid the need …
> Transition SPIRVProducer to opaque pointers P2

- lib/LongVectorLoweringPass.cpp
- test/LongVectorLowering/constgep.ll
- test/LongVectorLowering/fract.ll
- test/LongVectorLowering/opaque_alloca.ll
- test/LongVectorLowering/opaque_constgep.ll
- test/LongVectorLowering/opaque_fract.ll
- test/LongVectorLowering/opaque_frexp.ll
- test/LongVectorLowering/opaque_gep.ll
- test/LongVectorLowering/opaque_load.ll
- test/LongVectorLowering/opaque_store.ll
* Converts most of LongVectorLowering to be able to support opaque
pointers
* Doesn't handle memory intrinsics (e.g. memcpy) yet
* Can generate some unfortunate implicit pointer casts due to GEP
folding
XFAILs two new lit tests due to a bug (#874)
> Transition LongVectorLowering to opaque pointers

- CMakeLists.txt
- cmake/util.cmake
- lib/CMakeLists.txt
- It's not make sense installing headers and libraries when the tools installation is needed. So installing headers and libraries will be proper regardless tools installation.
- Supporting the combined static library will be very helpful for people who want to link clspv_core. Because without the combined static library, they need to handle linking llvm and clang.
> Create the combined static library and install correctly

- lib/LongVectorLoweringPass.cpp
- test/LongVectorLowering/clspv_fract.ll
- test/LongVectorLowering/floor.ll
> longvector: add support for missing builtins

- lib/SPIRVProducerPass.cpp
- test/no_int2.cl
- test/no_int2.ll
Most vulkan drivers do not support integer type not being a multiple
of 8.
Make sure we always produce integer type with a size multiple of 8.
This will fix a compilation issue with libclc lgamma and lgamma_r
functions.
> roundup integer type to be a multiple of 8

- lib/InlineFuncWithPointerBitCastArgPass.cpp
- lib/ReplaceOpenCLBuiltinPass.cpp
- lib/ReplacePointerBitcastPass.cpp
- lib/Types.cpp
- test/PointerCasts/opaque_canonical_pointer.ll
- test/PointerCasts/opaque_clspv_vloada_half4_global.ll
- test/PointerCasts/opaque_clspv_vloada_half4_local.ll
- test/PointerCasts/opaque_deref_load_cast_float2_to_int4.ll
- test/PointerCasts/opaque_deref_load_cast_float4_to_int2.ll
- test/PointerCasts/opaque_deref_store_cast_int2_to_float4.ll
- test/PointerCasts/opaque_deref_store_cast_int4_to_float2.ll
- test/PointerCasts/opaque_inline_func_with_pointer_cast_as_argument.ll
- test/PointerCasts/opaque_issue-551.ll
- test/PointerCasts/opaque_load_cast_array_of_array_int_to_long.ll
- test/PointerCasts/opaque_load_cast_array_of_array_local.ll
- test/PointerCasts/opaque_load_cast_of_array.ll
- test/PointerCasts/opaque_load_store_struct_i64_1.ll
- test/PointerCasts/opaque_load_store_struct_i64_2.ll
- test/PointerCasts/opaque_load_store_struct_i64_3.ll
- test/PointerCasts/opaque_load_store_struct_i64_4.ll
- test/PointerCasts/opaque_store_cast_array_of_array.ll
- test/PointerCasts/opaque_store_cast_array_of_array_int_to_long.ll
- test/PointerCasts/opaque_store_cast_array_of_array_local.ll
- test/PointerCasts/opaque_vload_half2_pointer_cast_from_float4.ll
- test/PointerCasts/opaque_vstore_half4_pointer_cast_to_float4.ll
* Inline functions where there is an implicit pointer cast in the
arguments
* Support implicit pointer casts in replace pointer bitcasts
* Cover alloca and global variables for inferring types from the result
* Remove some unnecessary pointer casts in ReplaceOpenCLBuiltin when
using opaque pointers
> Support opaque pointers in ReplacePointerBitcast and InlineFuncWithPointerBitCastArg

- lib/LongVectorLoweringPass.cpp
- test/LongVectorLowering/cluster_pod_args_offsets.cl
Long-vector POD args are lowered to arrays. When these args are clustered in a struct, changing these member types can change the layout of the struct. This can result in the clustered POD arg struct not having the same layout as the corresponding reflection metadata.
Fix this behavior by using the same remapped type offset/size metadata as the UBO Type Transform Pass to preserve the original layout.
The test case here comes from the basic/parameter_types test from the OpenCL CTS.
> Fix incorrect POD arg struct layout for kernels with long-vector POD args

- lib/SPIRVProducerPass.cpp
- test/ImageBuiltins/get_image_channel_multiple_kernel.cl
- test/ImageBuiltins/get_image_channel_with_pod_arg.cl
ordinal could changed when we have pod arguments before the image arg.
> fix generation of image metadata reflection

- lib/ReplaceLLVMIntrinsicsPass.cpp
- lib/ReplaceLLVMIntrinsicsPass.h
- lib/SPIRVProducerPass.cpp
- test/LLVMIntrinsics/assume.ll
- utils/make_test.py
* **Delete llvm.assume declaration and its calls**: as llvm.assume will require SPV_KHR_expect_assume extension which is not supported by Vulkan at the moment. So, we delete it for now. llvm.assume is a compiler hint so should be safe to ignore. One of the CTS tests that was affected: basic/test_basic kernel_call_kernel_function.
* **Print a meaningful error when there is unsupported llvm intrinsic call or unhandled function declaration/definition**: the current code will handle unsupported llvm intrinsic calls or unlinked function declarations by treating them as llvm::Constants and eventually will fail with ("unsupported Constant???") error. That should be handled so any future call for llvm intrinsic that is not supported or unlinked function declarations is identified.
* **Fix …
> delete llvm.assume calls 

- lib/LongVectorLoweringPass.cpp
- lib/LongVectorLoweringPass.h
- test/HalfStorage/vstore_half16.cl
- test/HalfStorage/vstore_half8.cl
- test/LongVectorLowering/char_struct_ssbo.cl
- test/LongVectorLowering/cluster_pod_args_offsets.cl
- test/LongVectorLowering/padded_struct.ll
- test/LongVectorLowering/struct.ll
vectors are aligned on their size. But when lowering them to arrays,
it changes their alignment to be on the alignment of the element.
When lowering a structure make sure that we are keeping the offset
right. If not add a padding element.
Also make sure that the structure has the same size before and after
the lowering. If not add a padding element at the end.
As the lowered type might have more element than the original one,
rework the indices when lowering gep extractvalue or insertvalue
> fix alignment of structure when lowering long vectors

- lib/SimplifyPointerBitcastPass.cpp
- test/PointerCasts/opaque_trivial_casts.ll
- test/PointerCasts/trivial_casts.ll
* **Modify `SimplifyPointerBitcastPass::runOnBitcastFromGEP`**: This function should simplify cases when we bitcast a pointer that is generated from gep instruction. Before opaque pointers that case was valid as we could transform a pointer type to another pointer type like (i64* to i32*). After opaque pointer changes that case can't happen and will always be a trivial bitcast as we don't have any pointer type other than "ptr". Trivial bitcasts will be handled with `runOnTrivialBitcast`. So, we should delete this function after full transformation to opaque pointers.  
Example: `runOnTrivialBitcast` will delete the bitcast instruction. 
```
%gep = getelementptr i32, ptr %ptr, i32 0     
%cast = bitcast ptr %gep to ptr
```
* **Modify …
> Transition SimplifyPointerBitcastPass to opaque pointers

- lib/ReplaceLLVMIntrinsicsPass.cpp
- test/LLVMIntrinsics/memcpy_opaque.ll
- test/LLVMIntrinsics/memset_null_many_copies.ll
- test/LLVMIntrinsics/memset_opaque.ll
Use InferType to get the type. If InferType returns null, it means
that we are not capable of inferring the type. In that case, choose an
appropriate type and add a gep so that future pass can infer the type
we choose. ReplacePointerBitcast might rework what we did in this pass
to have something coherent at a function level.
Fix memcpy, which did not work as expected when having no unpacking
but a type smaller than the size of the copy. Fix it by removing the
if statement which is not needed. It will produce unnecessary gep,
which is not a issue.
Fix memset to work on a subset of a type. It still needs to be
complete type, like for memcpy.
> add support for memcpy/memset with opaque pointers

- lib/ClusterConstants.cpp
- test/NormalizeGlobalVariables/cluster_constants_alignment.ll
The alignment of each element might not be the alignment of their size
due to the lowering of long vectors.
But the global variable still holds the required alignment.
Use it to make sure that the alignment is correct. If not add a
padding element.
> fix cluster constants to keep the proper alignment of each element

- lib/ReplacePointerBitcastPass.cpp
- test/PointerCasts/opaque_implicit_gep.cl
- test/PointerCasts/opaque_implicit_gep.ll
- test/PointerCasts/opaque_implicit_gep_nested_struct.ll
- test/PointerCasts/opaque_implicit_gep_vector.ll
LLVM will optimize out the GEP to the first element of a vector or aggregate type when opaque pointers are enabled, as there is no real pointer arithmetic to be done. This needs explicitly handled to prevent the correct access chain being omitted from the SPIR-V.
The ReplacePointerBitcastPass will reinsert elided GEPs where possible.
This fixes some work item builtin calls like `get_global_id(0)`.
> Improve support for elided GetElementPtr instructions

- lib/ArgKind.cpp
- lib/UBOTypeTransformPass.cpp
- test/UBOTypeTransform/transform_global.ll
- test/UBOTypeTransform/transform_global_opaque.ll
- test/UBOTypeTransform/transform_local.ll
- test/UBOTypeTransform/transform_local_opaque.ll
UBOTypeTransform will now read the underlying type of pointer arguments from the clspv resource builtins.
I also removed an unneeded copy of the offsets when building the new struct type and ensured attributes were copied when created new global variables and functions.
#816
> UBOTypeTransformPass: Handle opaque pointers

- CMakeLists.txt
clspv-reflection requires SPIRV-tools. SPIRV-tools was first excluded when not building tests, causing the build to fail during linking.
> Include SPIRV-tools when not building tests

- CMakeLists.txt
ChromeOS build system already has spirv-dis built somewhere else and
it is available for clspv to use. Thus ChromeOS does not want to build
spirv-dis in clspv build system.
Adding an option to avoid building spirv-dis
> CMakeLists.txt: fix build of spirv-dis for ChromeOS

- lib/CMakeLists.txt
- lib/Compiler.cpp
- lib/FixupBuiltinsPass.cpp
- lib/FixupBuiltinsPass.h
- lib/PassRegistry.def
- lib/Passes.h
- test/MathBuiltins/sqrt/float2_rsqrt.cl
- test/MathBuiltins/sqrt/float2_sqrt.cl
- test/MathBuiltins/sqrt/float3_rsqrt.cl
- test/MathBuiltins/sqrt/float3_rsqrt_novec3.cl
- test/MathBuiltins/sqrt/float3_sqrt.cl
- test/MathBuiltins/sqrt/float3_sqrt_novec3.cl
- test/MathBuiltins/sqrt/float4_rsqrt.cl
- test/MathBuiltins/sqrt/float4_sqrt.cl
- test/MathBuiltins/sqrt/float_rsqrt.cl
- test/MathBuiltins/sqrt/float_sqrt.cl
This is the first step towards removing these builtins from our libclc
SOURCES and relying entirely on the GLSL instructions.
FixupBuiltinsPass is intended to be generic, and an alternative to
ReplaceOpenCLBuiltinsPass that doesn't necessitate erasing the original
function from the module.
> Add FixupBuiltinsPass to ensure NaN check is performed on sqrt and rsqrt

- lib/LongVectorLoweringPass.cpp
- test/LongVectorLowering/variable_index_vector_extract.ll
- test/LongVectorLowering/variable_index_vector_insert.ll
* **Support variable indices in insertelement/extractelement instructions for longVectorLowering pass**: Add 2 cases for lowering vectors inside insertelement/extractelement with variable indices:
* First case when we have the vector operand instruction as `load`.
* Second case is the general case where we add `alloca` instruction to extract the array pointer.
* Add tests for the 2 cases.
**Note**: This changes fixes CTS tests: spirv_new/op_vector_char16_extract, op_vector_char16_insert
**This contribution is being made by Codeplay on behalf of Samsung.**
> Support variable indices in insertelement/extractelement for LongVectorLoweringPass 

- lib/Compiler.cpp
- test/half-fma.cl
This is improving a lot workload using fp16.
It has been tested on tensorflow lite.
> enable native half support if fp16 is enable

- lib/UndoInstCombinePass.cpp
- test/UndoInstCombine/extract_load_cast_3xi32_to_12xi8.ll
- test/UndoInstCombine/extract_load_cast_opaque.ll
- test/UndoInstCombine/undo_extract_cast.cl
- test/UndoInstCombine/undo_shuffle_cast.cl
- test/UndoInstCombine/undo_shuffle_load_cast_opaque.ll
Handles opaque pointers in the UndoInstCombinePass by giving up on finding the original type when the pointer is opaque.
Obviously this does have a slight problem in that the purpose of the pass isn't really being fulfilled any more.
Is this currently a plan on how to deal with this or should I look further into inferring the type?
This is to contribute towards issue #816
> Handle opaque pointer in UndoInstCombinePass

- lib/Compiler.cpp
- test/print-all.cl
This allows flags like '-print-after-all' to work again with clspv
It doesn't print the names registered in `PassRegistry.def` for some reason, but printing the class names is good enough for general debugging use. I did check to see if this was related to the passes being in the clspv namespace but it doesn't seem to be the case.
> Use LLVM's StandardInstrumentations with the pass builder

- lib/LongVectorLoweringPass.cpp
- test/LongVectorLowering/ctz.ll
Following the last LLVM update, it is now required to pass the integer_ctz CTS test.
> Add support for llvm.cttz to the long vector lowering pass

- lib/LongVectorLoweringPass.cpp
Vector types wider than sixteen can be generated by optimizations, and if we
try to lower them we're prone to hitting asserts. The UndoInstCombine pass is
capable of handling long vectors in these cases so we're better off
leaving them for it to take care of.
The specific motivating case for this is if we include the libclc
conversion implementations in our builtins module and continue building
it with -O3 the resultant module has very long vectors in it that
UndoInstCombine handles better than LongVectorLowering does.
> Stop trying to lower extremely long vectors.

- lib/PushConstant.cpp
- test/PushConstant/cluster_global_pod_args-vectors.ll
This stops us hitting an assert that would otherwise happen when a long vector kernel arg didn't fit in regular push constant memory (or was forbidden from it by a flag like -no-16-bit-storage).
> Add support for long vectors of small types in the global push constant struct. 

- include/clspv/Compiler.h
- lib/Compiler.cpp
- test/CMakeLists.txt
- test/LongVectorLowering/phi.cl
- test/MultipleInputs/kernel.cl
- test/MultipleInputs/kernel.cl2
- test/MultipleInputs/kernel.ll
- test/MultipleInputs/kernel.ll2
- test/emit_ir.cl
- test/mfmt_c.cl
This is a first step to fix OpenCL-CTS 'compiler' tests in clvk.
The idea is to use llvm IR as the intermediate language to link
program together.
To do that, this PR is now exposing one new function:
- CompileFromSourcesString: which will allow to take several input
files, compile and link them together into 1 output buffer.
Major changes:
- 'InputFilename' (now 'InputsFilename') allows for multiple inputs.
- New option 'OutputFormat' allows to choose the output format among those 4 possibilities:
- `ll` Readable LLVM IR
- `bc` Binary LLVM IR
- `spv` Vulkan SPIR-V
- `c` C initializer list of Vulkan SPIR-V
Also clean now unused options `-emit-ir` and `-mfmt`.
- 'SetCompilerInstanceOptions' (and new function 'ProgramToModule')
expects 'program' to never be empty. The frontend 'Compile' …
> compiler: allow compilation of several inputs file together

- include/clspv/FeatureMacro.h
- include/clspv/Option.h
- lib/CMakeLists.txt
- lib/Compiler.cpp
- lib/FeatureMacro.cpp
- lib/Option.cpp
- test/Features/cl3-all-features.cl
- test/Features/cl3-no-features.cl
- test/Features/cl3-some-features.cl
This adds the ability to specify OpenCL3.0 feature macros that should be enabled by the clang frontend.
One thing I'm not sure about in this PR is the overlap of some options, specifically FP64 and ImageSupport. I think it would be best for the program to error out when one of these is disabled but the feature macro is enabled, but I'm not sure how CLSPV usually manages that.
> Added command line option to specify CL3.0 feature macros

- kokoro/scripts/linux/build-amber.sh
- kokoro/scripts/linux/build-clvk.sh
- kokoro/scripts/linux/build.sh
I'm planning on adding `gcc-10` and removing `gcc-7` from the docker image.
> Kokoro: Bump GCC from 7 -> 9

- lib/ReplaceOpenCLBuiltinPass.cpp
- test/AtomicBuiltins/atomic_init.cl
Add support for `atomic_init` by replacing it with a simple `OpStore`. `atomic_init` does a non-atomic initialization to an atomic variable.
This fixes `c11_atomics/atomic_init` CTS test
**This contribution is being made by Codeplay on behalf of Samsung.**
> Add support for atomic_init

- include/clspv/Option.h
- lib/Option.cpp
- lib/SPIRVProducerPass.cpp
- test/nonuniform-spv1.0.ll
- test/nonuniform.ll
Look for possible decoration for every pointers going to a load or a store.
Visit the origin of the pointer by going through phis, selects and geps.
Ref #945
> add option to decorate nonuniform pointers

- include/clspv/FeatureMacro.h
- lib/Compiler.cpp
- test/AtomicBuiltins/enum_values.cl
- test/Features/cl3-all-features.cl
- test/Features/cl3-no-features.cl
- test/Features/cl3-some-features.cl
This will allow CLSPV to turn off all the feature macros.
Due to opencl-c-base.h in the clang project [always defining](https://github.com/llvm/llvm-project/blob/1215e86a0e4703d4c6657564e1a758d95ea59c56/clang/lib/Headers/opencl-c-base.h#L68) certain preprocessor macros, I've added an `#undefine` for `__SPIR__`  and `__SPIRV__`. These defines should not be necessary since the [`BaseSPIRTargetInfo`](https://github.com/llvm/llvm-project/blob/1215e86a0e4703d4c6657564e1a758d95ea59c56/clang/lib/Basic/Targets/SPIR.h#L161) already defines all these feature macros, but I think it's not been fixed properly since a few are missing from [OpenCLExtensions.def](https://github.com/llvm/llvm-project/blob/1215e86a0e4703d4c6657564e1a758d95ea5 …
> Hack preprocessor to allow disabling all feature macros

- lib/SPIRVProducerPass.cpp
PHI node's operands may have not been process yet by `GenerateInstruction`, which can lead to `GetSPIRVValue` to fail when trying to decorate an operand that has not been processed.
> fix decorate non uniform

- lib/SplatArgPass.cpp
- test/SplatArgs/discard_incompatible_attrs.ll
These used to be retained which caused validator errors when they were present.
> Drop SExt and ZExt attributes when we splat int args into vectors.

- lib/Builtins.cpp
- lib/SPIRVProducerPass.cpp
* Final few cases in SPIRVProducerPass
* Small change in builtins
> Transition builtins and spirv producers to opaque pointers

- lib/SPIRVProducerPass.cpp
* Use getSPIRVPointerType instead of getSPIRVType when generating the type id for image metadata calls
> Fix type id generation for image metadata calls

- lib/SPIRVProducerPass.cpp
- test/ImageBuiltins/opaque_image_metadata.ll
- test/SPIRVProducer/opaque_alloca.ll
* Use getSPIRVPointerType in alloca codegen instead of getSPIRVType
> Fix opaque pointer alloca codegen

- lib/ReplacePointerBitcastPass.cpp
- test/PointerCasts/opaque_cast_and_no_cast.ll
- test/PointerCasts/opaque_different_casts_same_source.ll
* Further generalizes the fix from #973 to only operate on a single implicit bitcast at a time instead of all bitcasts from the same source
* properly handles both non-casts cases (previous PR) and when there are multiple different types of casts from the same source
> Better handling for opaque pointers in replace bitcasts

- README.md
These instructions were out of date after the spir64 target was added.
Also, a recent upstream change to libclc's cmake means the path to the LLVM installation is handled differently now. Note that you can no longer use an LLVM build directory that isn't an installation, you have to use the actual `install` target to ensure the necessary header files are present.
> Update build instructions for the builtins libraries

- README.md
Included `https://` preffix to `llvm-project` URL as the current URL redirects to a 404 repository
> fixed 404 error to  llvm-project

- lib/SPIRVOp.h
- lib/Types.cpp
- test/AllocateDescriptors/atomic_inc_dec.ll
* Add type inference for current SPIRVOps that are generated that use pointer operands
* fixes atomic cts tests atomic_dec and atomic_inc with opaque pointers
> Infer types for some SPIRVOps

- lib/ReplacePointerBitcastPass.cpp
- test/PointerCasts/opaque_single_array_cast.ll
* Identify an implicit gep when there is a single step to find the aliased type even if the target is another GEP
* fixes the basic cts test kernel_preprocessor_macros with opaque pointers
> Identify another implicit GEP case

- lib/ClusterPodKernelArgumentsPass.cpp
- test/cluster_pod_args_retain_kernel_calls.cl
ClusterPodKernelArgumentsPass creates copies of kernels and changes the original kernel to have the SPIR_FUNC calling convention. We need to update the calling convention of any call instructions that used the original function as well or the mismach causes InstCombine to consider the call invalid and optimize it out.
> Update calling convention for users of copied functions in ClusterPodArgs

- lib/SPIRVProducerPass.cpp
- test/llvm-ctpop.ll
llvm can generate intrinsic ctpop when detecting the popcount pattern.
Fixes #984
> add support for @llvm.ctpop.i32

- lib/Compiler.cpp
- lib/LongVectorLoweringPass.cpp
- test/LongVectorLowering/opaque_global_gep.ll
- test/LongVectorLowering/opaque_global_load.ll
- test/LongVectorLowering/opaque_global_store.ll
* Run promote pass before long vector lowering to handle easy cases
* Check for handled values and global variables on opaque pointer values in gep, load and store visits
> Long vector lowering improvements with opaque pointers

- lib/Compiler.cpp
during ProgramToModule, the memBuffer needs to stay allocated as long as the compilerInstance exists.
Fix #988
> fix ProgramToModule valgrind error

- lib/Types.cpp
- test/vec3_opaque_sampler_builtin.ll
* Three element vector lowering infers types of function declarations
* Just have type inference return the function type in that case
> Infer function types

- include/clspv/Option.h
- lib/CMakeLists.txt
- lib/Compiler.cpp
- lib/FrontendPlugin.cpp
- lib/LogicalPointerToIntPass.cpp
- lib/LogicalPointerToIntPass.h
- lib/LongVectorLoweringPass.cpp
- lib/Option.cpp
- lib/PassRegistry.def
- lib/Passes.h
- lib/PhysicalPointerArgsPass.cpp
- test/LogicalPtrToInt/disallow_inttoptr.cl
- test/LogicalPtrToInt/local_args_ptrtoint.cl
- test/LogicalPtrToInt/local_ptrtoint.cl
- test/LogicalPtrToInt/private_ptrtoint.cl
This effectively creates a compile-time virtual address space for function and workgroup storage. The only practical use of this support is for inspecting the layout of composite types in memory. In anything but this narrow scenario the behavior will be unchanged. This is enough for the CTS vector alignment tests to pass.
This is a less-than-ideal hack but I think it's the best solution to unblock these CTS tests with the current state of SPIR-V and Vulkan.
This also fixes a bug in LongVectorLowering where updated GEP indices were being used to refer to the original type, rather than the cumulative old indices up to the original index being looked at.
> Support limited uses of ptrtoint on logical address spaces

- lib/BitcastUtils.cpp
- lib/BitcastUtils.h
- lib/Compiler.cpp
- lib/InlineEntryPointsPass.cpp
- lib/InlineEntryPointsPass.h
- lib/LogicalPointerToIntPass.cpp
- lib/LongVectorLoweringPass.cpp
- lib/RewritePackedStructs.cpp
- lib/SimplifyPointerBitcastPass.cpp
- lib/ThreeElementVectorLoweringPass.cpp
- test/always_strip_generic.ll
Fixes #999
* Make all inlining passes unconditional
* Make generic address space inference unconditional
* Add functionality to inline entry points to look for generic address space and inline in that case
* also strips constexprs
* Rename `RemovedCstExprFromFunction` to `RemoveCstExprFromFunction`
> Change how the conditionality of inlining works

- lib/AddFunctionAttributesPass.cpp
- lib/SPIRVProducerPass.cpp
* Clspv cannot generate correct code without optimizations so remove any functions with the optnone attribute
* When generating a pointer type, if the data type is a pointer then the layout is based on that storage class
> Remove optnone attribute

- lib/DefineOpenCLWorkItemBuiltinsPass.cpp
- lib/PushConstant.cpp
- test/WorkItemBuiltins/get_global_offset-push-constant-non-constant-dim.ll
GetPushConstantPointer is designed to return a GEP into the push constant variable. When there is a single push constant or when indexing into the first one (i.e. the global offset), this leads to a GEP with all zero indices being created. With opaque pointers, this GEP is no longer created and CreateInBoundsGEP returns the original pointer. defineGlobalOffsetBuiltin was then assuming that the pointer returned pointed to a specific push constant rather than the global push constant variable itself which led to incorrect indices being used.
After this change, the extra indices are provided to GetPushConstantPointer so the full GEP into the global offset vector is created directly.
It seems that this is a generic issue and users who want to guard against this might now need to check whether …
> Fix definition of get_global_offset() when push constants are used

- lib/PushConstant.cpp
- test/PushConstant/opaque_pointer_gep_with_alias.ll
Found in a tflite kernel since we enable opaque pointers.
We can end up with gep on a subtype. Check for aliasing, and add enough indices to fall into the expected type.
> fix Redeclare global push constant with opaque pointer and gep

- lib/Compiler.cpp
Reverts google/clspv#1043
Noticed failures on compiler/options_build_optimizations for swiftshader and nvidia when importing this change.
> Revert "reenable unsafe-buffer-usage warning"

- lib/ThreeElementVectorLoweringPass.cpp
- test/ThreeElementVectorLowering/mad_sat.ll
Fixes #1045
* Opaque pointers now cause 3-element vector lowering in more cases so OpIAddCarry needs handled
> Support OpIAddCarry in 3-element vector lowering

- lib/ThreeElementVectorLoweringPass.cpp
- test/ThreeElementVectorLowering/ushort3_to_uchar6.ll
Fixes #1046
* Allow 3-element vector lowering to handle multiple-of-3 element vectors
* these can appear due to conversion functions with opaque pointers (e.g. bitcasting <3 x i16> to <6 x i8>)
> Handle multiple of 3 vectors in 3-element lowering

- lib/BitcastUtils.cpp
- lib/BitcastUtils.h
- lib/ReplacePointerBitcastPass.cpp
- lib/RewritePackedStructs.cpp
- lib/RewritePackedStructs.h
- lib/SimplifyPointerBitcastPass.cpp
- test/PointerCasts/opaque_trivial_casts.ll
- test/PointerCasts/srcLTdst/srcelemLTdstelem/store_cast_char_to_float.ll
- test/PointerCasts/srcLTdst/srcelemLTdstelem/store_cast_short_to_float.ll
- test/RewritePackedStructs/packed_struct.cl
- test/RewritePackedStructs/packed_struct2.ll
- test/RewritePackedStructs/packed_struct3.ll
- test/RewritePackedStructs/packed_struct4.ll
- test/RewritePackedStructs/packed_struct_opaque.ll
For opaque pointers, do not look for packed structure in kernel arguments.
Instead look for gep on packed structure or on structure with an implicit cast.
Lowering structure (even unpacked) in implicit cast gep is needed to avoid complicated issue (that I don't have a answer for) in replacepointerbitcastpass.
Lower all those GEPs using 2 new functions to rework GEP indices from a source type to a target type.
Also use those functions in Simplifypointerbitcastpass
SimplifyPointerBitcastPass needs to be updated with a new Map containing ImplicitCasts (between 2 GEPs) that can be lower in this pass. This is needed to avoid regression in the CTS.
Other minor fixes:
- ReplacePointerBitcastPass::ComputeLoad: CreateGEP might not create a GEP, use getIndexedType to get the Load Type.
- …
> fix Rewrite Packed Structs pass for opaque pointers

- lib/ClusterPodKernelArgumentsPass.cpp
- lib/Types.cpp
- test/KernelArgInfo/unused-arg-changed-order.cl
- test/KernelArgInfo/unused-intptr_t.cl
Now passing a full CTS sweep.
- Default to int for unknown types.
- Do not generate empty structure types for structures. Those do not have a correct layout.
- Support user-defined types and types whose name starts with one of the base types we are recognising.
- Use the arg_map when pod arguments have been clustered to figure out the original index of arguments to look at the right kernel arg info metadata.
- Add tests covering all these cases.
> Fix type inference from kernel arg info

- lib/SpecializeImageTypes.cpp
- test/SpecializeImageTypes/unused.cl
- test/SpecializeImageTypes/unused.ll
Fixes #1068
* Specialize unused image arguments to prevent type duplication
> Specialize unused image arguments

- lib/AllocateDescriptorsPass.cpp
- lib/ArgKind.cpp
- lib/ArgKind.h
- lib/ClusterPodKernelArgumentsPass.cpp
- lib/MultiVersionUBOFunctionsPass.cpp
- lib/RewritePackedStructs.cpp
* Since switching to target ext type for samplers and images, the inferred type is no longer necessary
> Remove inferred type parameter from GetArgKind

- docs/OpenCLCOnVulkan.md
- lib/Compiler.cpp
transparent pointers are not supported anymore since we have updated the builtins library using opaque pointers.
> return an error when using -enable-opaque-pointers=0

- lib/ReplaceOpenCLBuiltinPass.cpp
- lib/ReplaceOpenCLBuiltinPass.h
- test/HalfStorage/vload_half3.cl
- test/HalfStorage/vload_half3.ll
- test/HalfStorage/vload_half3_no_16bit_storage.ll
- test/HalfStorage/vstore_half3.cl
- test/HalfStorage/vstore_half3.ll
- test/HalfStorage/vstore_half3_no_16bit_storage.ll
- test/HalfStorage/vstorea_half3.cl
- test/HalfStorage/vstorea_half3.ll
- test/HalfStorage/vstorea_half3_no_16bit_storage.ll
we used to use 16bit storage even when not supported to implement vstore_half3 and vload_half3. Use vstore_half and vload_half implementation to implement those to make sure we do not use 16bit storage when not available
> fix vstore/vload_half3 when 16bit storage is not supported

- lib/FixupBuiltinsPass.cpp
- lib/FixupBuiltinsPass.h
- test/MathBuiltins/sqrt/fixup.ll
when sqrt/rsqrt input is a constant the IRBuilder optimize the select to directly get the right node. This lead to an assertion trying to cast select into an SelectInst.
Instead, just manage constant values staticaly
Fix #1083
> fix fixup for sqrt/rsqrt

- lib/AutoPodArgsPass.cpp
- lib/ClusterPodKernelArgumentsPass.cpp
- lib/ConstantEmitter.cpp
- lib/PushConstant.cpp
- lib/ReplaceLLVMIntrinsicsPass.cpp
- lib/UndoTruncateToOddIntegerPass.cpp
This takes care of all deprecation warnings except those that relate to getPointerElementType().
> Replace deprecated LLVM functions with the suggested replacement

- include/clspv/Option.h
- lib/Compiler.cpp
- lib/Option.cpp
- lib/SPIRVProducerPass.cpp
- test/MathBuiltins/sqrt/fixup.ll
* Remove transparent remnants from:
* SPIRVProducer.cpp
* Option.cpp
* Generalize a test
> Remove opaque pointer todos

- lib/FixupStructuredCFGPass.cpp
- lib/InlineFuncWithPointerBitCastArgPass.cpp
- lib/SPIRVProducerPass.cpp
- test/DirectResourceAccess/local_variable.cl
- test/FixupStructuredCFG/split_and_isolate.ll
- test/PointerCasts/inline_implicit_cast_through_function.ll
- test/ProgramScopeConstants/constant_array_with_function_call.cl
- test/ProgramScopeConstants/constant_array_with_function_call_module_constants_storage_buffer.cl
Fixes #1095
* Perform structured cfg fixes in opposite order to preserve loop info
* Simplify (and catch more cases) of inlining a function due to an implicit cast
* caused some miscellaneous test changes due to more inlining
* Add a debug option to emit OpName instructions for each basic block
> Fixes for Darktable kernels

- lib/PhysicalPointerArgsPass.cpp
- test/PhysicalStorageBuffers/parameter_attributes.ll
Fixes #1099
* Conversion of pointer arguments to physical SSBO references was copying all kernel function attributes
* Instead it should not copy any pointer specific attributes for converted parameters
> Remove pointer parameter attributes when converting to physical SSBO

- lib/PhysicalPointerArgsPass.cpp
- test/PhysicalStorageBuffers/issue-1098.cl
When a kernel is called by another function, we cannot erase it. We need to keep the version with explicit arguments that can be called.
Fix #1098
> fix physicalpointerargspass when kernel are called by other fcts

- lib/LowerAddrSpaceCastPass.cpp
- lib/LowerAddrSpaceCastPass.h
- test/AddressSpaceCast/inttoptr.ll
- test/AddressSpaceCast/issue-1107.cl
- test/AddressSpaceCast/ptrtoint.ll
ptrtoint is quite simple.
But inttoptr can get quite complex like in #1107. In that case, use the global address space as it is the only one on which we will be able to perform a `OpConvertUToPtr`.
Fix #1107
> add support for inttoptr/ptrtoint in loweraddrspacecastpass

- lib/LongVectorLoweringPass.cpp
- lib/ThreeElementVectorLoweringPass.cpp
- test/LongVectorLowering/codependent.ll
- test/ThreeElementVectorLowering/codependent_3element.ll
Fixes #1105
* Fix phi handling in LongVectorLowering and ThreeElementVectorLowering
* Before main visit loop, create placeholder phis and register them as replacements
* After main loop add incoming values to placeholders and remove from originals
* Main loop now just uses placeholder phi as updated value
* Remove dead code from long vector lowering
> Fix handling of codependent phi loops

- lib/BitcastUtils.cpp
- lib/SimplifyPointerBitcastPass.cpp
- lib/SimplifyPointerBitcastPass.h
- test/PointerCasts/multiple_implcit_casts.ll
- test/PointerCasts/opaque_trivial_casts.ll
Fixes #1113
* Refactored runOnGEPImplicitCasts into separate functions
* no longer attempts multiple transforms at the same time
* refactored methods now iterate deterministically
* Handle a case in GEP index calculation where the heterogeneous struct is larger than the offset of the gep
> Fixes for pointer cast simplification

- lib/SimplifyPointerBitcastPass.cpp
- test/PointerCasts/issue-1122.ll
first indices is always needed. If we have only 1 index, skip there is nothing to do here.
Fix #1122
> fix runOnUnneededIndices

- lib/SPIRVProducerPass.cpp
- test/SPIRVProducer/physical_storage_buffer_layout.ll
- test/SPIRVProducer/physical_storage_buffer_layout2.ll
- test/SPIRVProducer/physical_storage_buffer_layout3.ll
See https://github.com/kpet/clvk/issues/477
* Collect physical ssbo types that need a layout early in the producer
> Ensure types in physical storage buffers get layouts

- lib/Compiler.cpp
- lib/LogicalPointerToIntPass.cpp
- lib/LogicalPointerToIntPass.h
- lib/Option.cpp
- test/LogicalPtrToInt/function_inlining.ll
- test/LogicalPtrToInt/geps.ll
- test/LogicalPtrToInt/local_args_ptrtoint.cl
- test/LogicalPtrToInt/private_ptrtoint.cl
This PR is fixing the following CTS tests:
- vectors/vec_align_*
- basic/kernel_memory_alignment_*
This is done by:
- Support all GEPs, not just ones with constant offset.
- Support recursive GEPs.
- Inline function containing PtrToInt instead of skipping.
- If Physical Storage Buffers is not enable, consider every address space.
- Move pass later in the flow to make sure every needed inlining has been done and inst has been combine to remove as many IntToPtr and PtrToInt as possible.
- Enable to pass by default, I don't see a clear reason to have it disable by default.
> update LogicalPointerToIntPass to support more cases

- lib/BitcastUtils.cpp
- lib/SimplifyPointerBitcastPass.cpp
- lib/SimplifyPointerBitcastPass.h
- test/PointerCasts/phi-from-gep.ll
This pattern has been seen in tflite.
Not lowering it leads to error such as:
```
OpPhi's result type <id> '282[%_ptr_StorageBuffer_uchar]' does not match incoming value <id> '123[%123]' type <id>'122[%_ptr_StorageBuffer_v4half]'.
```
> fix phi from gep in simplify pointer bitcast

- lib/LowerAddrSpaceCastPass.cpp
- test/AddressSpaceCast/issue-1096.ll
Conflict between two passes.
ReplaceOpenCLBuiltinPass - this pass uses the InsertSPIRVOp function to generate a new instruction with an unusual naming style.
LowerAddrSpaceCastPass::visitCallInst() – create a new version of the instruction from the ReplaceOpenCLBuiltinPass pass with some patches but can't handle the name.
> Add support clspv::Builtins::kSpirvOp instructions for the LowerAddrSpaceCastPass

- include/clspv/Option.h
- lib/Option.cpp
- lib/SPIRVProducerPass.cpp
- test/ConvertBuiltins/hack_convert_to_float.ll
Some driver optimize pattern this pattern to completely remove the two
conversions, while libclc relies on this pattern to be executed to
perform rounded conversions.
```
%0 = OpConvertSToF %float %input
%1 = OpConvertFToS %int %0
```
The hack-convert-to-float option add a dummy instruction after
`OpConvertSToF` to prevent this optimisation.
> add hack option to prevent unwanted driver optimisation

- lib/AnnotationToMetadataPass.cpp
- lib/AnnotationToMetadataPass.h
- lib/CMakeLists.txt
- lib/Compiler.cpp
- lib/Constants.cpp
- lib/Constants.h
- lib/FrontendPlugin.cpp
- lib/FrontendPlugin.h
- lib/PassRegistry.def
- lib/Passes.h
- lib/SPIRVProducerPass.cpp
- test/kernel_attributes.cl
reading the attrs
added kernel attrs as nonsemantic information
hacked kernel attribute information into nonsemantic information write annotations to metadata when possible
read attributes into spirv
This PR is just a clean rebase of #990
I have checked the implementation using a clean rebase of https://github.com/kpet/clvk/pull/489 on both swiftshader and nvidia. It fixes `test_api kernel_attributes`.
> Read kernel attributes and add them to non-semantic reflection information

- lib/SPIRVProducerPass.cpp
- test/SubGroup/subgroup_all.cl
- test/SubGroup/subgroup_any.cl
Fixes #1140
* Fix generation of OpGroupNonUniformAny/All
* convert input to bool by comparing not equal to 0
* convert subgroup result back to integer using a select
> Fix generation of non-uniform any/all

- lib/PhysicalPointerArgsPass.cpp
- test/PhysicalStorageBuffers/kernel_call_kernel_function.ll
We used to leave the calling conv of callinst of spir_kernel function as spir_kernel, while we had changed the function to be just a spir_function.
This used to lead to instcombine just getting rid of the call as (I think) it cannot find the function with this calling conv.
Set the calling conv to spir_func so that the call is not remove by mistake.
This patch is fixing some compiler tests of the CTS when running with physical addressing enabled.
> fix physicalStorageBuffers when a kernel is calling another kernel

- lib/CMakeLists.txt
- lib/ClusterPodKernelArgumentsPass.cpp
- lib/Compiler.cpp
- lib/KernelArgNamesToMetadataPass.cpp
- lib/KernelArgNamesToMetadataPass.h
- lib/PassRegistry.def
- lib/Passes.h
- lib/SPIRVProducerPass.cpp
- test/KernelArgInfo/kernel-arg-info-physical-storage-buffers.cl
- test/KernelArgInfo/kernel-arg-info.ll
This pass handle kernel arguments names through the metadata.
This is needed when running with physical storage buffers as all arguments are cluster in the push constant, and end up missing with the current implementation.
> add kernel arg names to metadata pass

- include/clspv/Compiler.h
Compiling on arch-linux with gcc-13 failed on this missing header
> add missing header in Compiler.h

- lib/PrintfPass.cpp
- test/Printf/printf.ll
- test/Printf/printf_args.cl
- test/Printf/printf_physical_buffer.cl
- test/Printf/printf_string.cl
- test/Printf/printf_vector.cl
If we do not have the space to store all the arguments, we should not store them. It leads to memory corruption from out-of-bounds access on platform like lavapipe.
I thought of merging the tests for the printf id and the args, but we need both of them.
Here is an example to understand:
Considering we have a printf with 1 argument and a buffer size of 8 bytes (2 words).
The first word is for the counter of number of words written. We are left with one word.
When performing the printf, we will execute the atomic add, which will set the counter to 2 (1 for the printfid and 1 for the arg). If we do not store the printf id, the runtime won't be able to know whether we are trying to print 2 string without argument (each one needing 1 word) or if we are printing 1 string with 1 argument.
> fix printf when reaching end of printf buffer

- lib/SPIRVProducerPass.cpp
- lib/Types.cpp
- test/PointerCasts/issue-1166.2.ll
- test/PointerCasts/issue-1166.cl
- test/PointerCasts/issue-1166.ll
If the bigger type is a struct, we need to make sure that all its fields are bigger or equal to the type selected to return. Otherwise, return the smaller type amongst the fields of the structure.
This fix ends up generating vector of 1 element. Fix getSPIRVConstant and getSPIRVType to avoid generating vector of 1 element as it is not allowed in SPIR-V.
Fix #1166
> fix SmallerTypeNotAliasing when a structure is involved

- lib/PrintfPass.cpp
- test/Printf/printf_string_64bit_ptr.ll
literal string are store with a 32bit identifier, while the size of the arg when pointers are 64bit is 8 bytes. It does not match the real stored size of 4 bytes, which leads to error in the runtime when running the CTS.
> fix printf of literal string when pointers are 64bit

- lib/BitcastUtils.cpp
- test/PointerCasts/issue-1171.cl
If we can infer a type of one operand of memcpy, do nothing to avoid dereferencing nullptr.
fix #1171
> fix IsImplicitCast for memcpy

- lib/ReplacePointerBitcastPass.cpp
- lib/SimplifyPointerBitcastPass.cpp
- lib/SimplifyPointerBitcastPass.h
- test/PointerCasts/issue-1180.ll
rework alloca when its type is incompatible with its users.
Fix #1180
> rework alloca in simplifypointerbitcast

- lib/ReplaceLLVMIntrinsicsPass.cpp
- test/LLVMIntrinsics/issue-1173.cl
- test/LLVMIntrinsics/issue-1173.ll
When LowerAddrSpaceCastPass rework the function to remove the generic addrspace part of it, it generates a name with a itanium mangling.
Take it into account in ReplaceLLVMInstrinsics so that those function are taken care of.
Also add them to the DeadFunctions to avoid error later in the verifier pass
Fix #1173
> fix to consider memcpy and memset with generic addrspace

- lib/BitcastUtils.cpp
- lib/BitcastUtils.h
- lib/ReplacePointerBitcastPass.cpp
- test/PointerCasts/issue-1032.cl
- test/PointerCasts/issue-1184.cl
- test/PointerCasts/issue-1185.cl
- test/UBO/copy_nested.cl
When guessing the type from the users, do not consider aliasing when type match the first element of the struct.
Fix DowngradeSourceToTy to avoid modifying node on which we are iterating.
No regression on CTS with swiftshader and nvidia
Fix #1184
Fix #1185
> Fix for struct needed to get downgraded to handle pointerbitcast

- lib/SimplifyPointerBitcastPass.cpp
- test/PointerCasts/issue-1204.ll
- test/PointerCasts/srcLTdst/srcelemLTdstelem/store_cast_char_to_float.ll
- test/PointerCasts/srcLTdst/srcelemLTdstelem/store_cast_short_to_float.ll
when src_gep indices are all zeros, just use src_gep pointer, and don't try to rework the indices which can lead to unsupported cases
Ref #1204
> fix runOnImplicitCasts

- lib/SimplifyPointerBitcastPass.cpp
- test/issue-1204.ll
When a gep is used by 2 phis, make sure to process it only once.
Ref #1204
> fix runOnPHIFromGEP

- lib/ReplaceLLVMIntrinsicsPass.cpp
- test/LLVMIntrinsics/memset_opaque.ll
The starting type for the gep needs to be the one we use to `unpack` from in the code
Ref #1208
> fix replaceMemset

- lib/ClusterConstants.cpp
- test/NormalizeGlobalVariables/cluster_constants_phi.ll
- test/NormalizeGlobalVariables/cluster_constants_phi_physical_storage_buffers.ll
When a constant in a phi node, we don't want to create a gep before it.
Instead create a gep in the basicblock of the incoming value of the PHI node.
Ref #1208
> fix ClusterConstants

- lib/LowerPrivatePointerPHIPass.cpp
- test/PrivatePointerPHI/loop64.ll
when pointer are 64 bits, we need to use int64 to store the offset along the way.
Ref #1208 #1209
> fix LowerPrivatePointerPHIPass

- lib/PushConstant.cpp
- test/cluster_pod_args_spir64_cst_expr_gep.ll
Structure can only be accessed through i32 index.
This bug was found running with spir64 and physical addressing enabled.
> fix RedeclareGlobalPushConstants to avoid i64 index for struct

- docs/OpenCLCOnVulkan.md
- lib/BuiltinsEnum.h
- lib/BuiltinsMap.inc
- lib/CMakeLists.txt
- lib/ReplaceOpenCLBuiltinPass.cpp
- lib/ReplaceOpenCLBuiltinPass.h
- lib/SPIRVProducerPass.cpp
- lib/SamplerUtils.cpp
- lib/SamplerUtils.h
- test/ImageBuiltins/read_image3d_with_literal_unorm_sampler.cl
- test/ImageBuiltins/read_image3d_with_literal_unorm_sampler.ll
We cannot use unormalized sampled with 3D images.
This commit intend to fix that for literal sampler (static sampler defined in the kernel).
When detecting a case of reading a image3d with a literal sampler using unnormalized coordinate:
- create a equivalent sampler using normalized coordinate
- normalized the coordinate
Ref #1202
> always use normalized sampler to read image3d with literal sampler

- include/clspv/Option.h
- lib/FixupBuiltinsPass.cpp
- lib/FixupBuiltinsPass.h
- lib/Option.cpp
- test/hack-image1d-buffer-bgra.cl
- test/hack-image1d-buffer-bgra.ll
Some devices do not support VK_FORMAT_B8G8R8A8 with texel buffers. As {CL_BGRA, CL_UNORM_INT8} is mandatory to be OpenCL compliant, those devices have to find a map for it. A possible solution for those devices is to map it to VK_FORMAT_R8G8B8A8. Using the swizzling we can manage to have the proper order of component when reading using a sampler, but for samplerless reads, we need to rework the component by ourselves.
> add hack to shuffle component of read_image

- lib/BitcastUtils.cpp
- test/phi_with_cst_expr.ll
constant expr inside phi nodes need to be inserted in the correct basic block to avoid inserting non-phi instructions before phi ones.
Ref #1222
> fix rework on constant expr from phi nodes

- lib/BitcastUtils.cpp
- lib/ReplacePointerBitcastPass.cpp
- test/PointerCasts/issue-1222-2.ll
- test/PointerCasts/issue-1222.ll
- test/PointerCasts/opaque_trivial_casts.ll
If we cannot figure out the indices from constant offset using the source type, it means that it is most probably smaller than the gep result type. In that case use the gep result type as the source type.
Also if the source type is not a vector, array of struct, still consider the scalar the go through it once.
We might need to merge it with some indice already existing.
Ref #1222
> fix replacepointerbitcast for gep with result type smaller than src

- lib/BitcastUtils.cpp
- lib/BitcastUtils.h
- lib/ReplacePointerBitcastPass.cpp
- lib/SimplifyPointerBitcastPass.cpp
- test/PointerCasts/issue-1222-3.ll
- test/PointerCasts/issue-1222-4.ll
Types used to interface with SPIR-V have a null size (types like: `{[0 x Ty]}`).
Try to avoid it by going through the type as long as SizeInBits returns zero to get the real type size for it.
Do not do it for runOnUnneededCasts and runOnImplicitGEP because either it is already taken into account in ReplacePointerBitcastPass, or it can break the module to remove or insert gep.
Ref #1222
> fix PointerBitcast considering type with null size

- lib/LowerPrivatePointerPHIPass.cpp
- lib/LowerPrivatePointerPHIPass.h
- test/PrivatePointerPHI/icmp.ll
- test/PrivatePointerPHI/ptrtoint.ll
When reusing geps, it is very complicated to make sure that the gep dominates the instruction that will be using it.
I tried to force the gep to be just after the `Src` instruction, but in that case, the gep might dominates some of its indices which is wrong as well.
Let's just get rid of this optimisation idea for the time being.
Ref #1222
> fix LowerPrivatePointerPHIPass by removing gep_map

- lib/BitcastUtils.cpp
- lib/LowerPrivatePointerPHIPass.cpp
- lib/SimplifyPointerBitcastPass.cpp
- test/PointerCasts/phi-from-gep.ll
- test/PrivatePointerPHI/scalar-alloca.ll
- test/issue-1204.ll
- fix isimplicitcast for phi nodes:
- compare infertype of phi with type of incoming values instead of incoming values against each other.
- insert needed gep between gep an phi aliasing
- consider scalar-alloca to avoid adding wrong gep
Fix #1224
> fix phi on private pointer

- lib/SPIRVProducerPass.cpp
- test/MathBuiltins/asin/float_asin.cl
- test/MathBuiltins/fabs/float2_fabs.cl
- test/MathBuiltins/fabs/float3_fabs.cl
- test/MathBuiltins/fabs/float3_fabs_novec3.cl
- test/MathBuiltins/fabs/float4_fabs.cl
- test/MathBuiltins/fabs/float_fabs.cl
- test/MathBuiltins/recip/float2_half_recip.cl
- test/MathBuiltins/recip/float3_half_recip.cl
- test/MathBuiltins/recip/float3_half_recip_novec3.cl
- test/MathBuiltins/recip/float4_half_recip.cl
- test/MathBuiltins/recip/float_half_recip.cl
- test/MathBuiltins/round/float2_round.cl
- test/MathBuiltins/round/float3_round.cl
- test/MathBuiltins/round/float3_round_novec3.cl
- test/MathBuiltins/round/float4_round.cl
- test/MathBuiltins/round/float_round.cl
- test/NativeBuiltins/MathBuiltins/fabs/float2_fabs.cl
- test/NativeBuiltins/MathBuiltins/fabs/float3_fabs.cl
- test/NativeBuiltins/MathBuiltins/fabs/float3_fabs_novec3.cl
- test/NativeBuiltins/MathBuiltins/fabs/float4_fabs.cl
- test/NativeBuiltins/MathBuiltins/fabs/float_fabs.cl
- test/div/float2_div.cl
- test/div/float3_div.cl
- test/div/float3_div_novec3.cl
- test/div/float4_div.cl
- test/div/float_div.cl
Both the OpenCL and the SPIR-V specification allow denormalized numbers to be flushed to zero.
But since llvm/llvm-project@5c0da5839de1bdc08f411a04305a9bdadf538ad5 patterns from libclc like in `cbrt` are converted to call to fabs:
```
float input;
int input_as_uint = as_uint(input);
int input_without_sign = input_as_uint & 0x7fffffff;
```
This is causing issue as the cbrt algorithm in libclc needs denormalized numbers not to be flushed to zero to be OpenCL compliant.
Unless clspv is called with fabs in the native builtins list, use a software version of fabs that guarantees denormalized numbers will not be flushed to zero.
> Add fabs version not flushing to zero denormalized numbers

- lib/SimplifyPointerBitcastPass.cpp
- test/PointerCasts/issue-1225.ll
Since runOnGEPFromGEP has been supported more cases, the if statement removed by this commit is not needed. In fact, removing it fix code as shown in the test here added.
Fix #1225
> fix runOnImplicitGEP for more than 1 index missing

- CMakeLists.txt
- test/CMakeLists.txt
SPIRV-Tools no longer builds any executables when targeting Android, so disable attempts to build and use `spirv-dis` in Clspv.
> Fix Android build

- test/constant_data_seq_string.ll
- test/extract_constant.ll
Otherwise, this fails tests in some environments that check the existence of the output file.
> Add --producer-out-file to tests as needed

- deps.json
- lib/AllocateDescriptorsPass.cpp
- lib/Types.cpp
- lib/Types.h
- lib/ZeroInitializeAllocasPass.cpp
- test/AllocateDescriptors/spec_images_no_sharing.ll
- test/AllocateDescriptors/spec_images_sharing.ll
- test/AutoPodArgs/contains_read_image3d.ll
- test/ImageBuiltins/get_image_array_size_image1d_array_readonly.ll
- test/ImageBuiltins/get_image_array_size_image1d_array_readwrite.ll
- test/ImageBuiltins/get_image_array_size_image1d_array_writeonly.ll
- test/ImageBuiltins/get_image_array_size_image2d_array_readonly.ll
- test/ImageBuiltins/get_image_array_size_image2d_array_readwrite.ll
- test/ImageBuiltins/get_image_array_size_image2d_array_writeonly.ll
- test/ImageBuiltins/opaque_image_metadata.ll
- test/ImageBuiltins/read_image3d_with_non_literal_sampler.ll
- test/KernelArgInfo/kernel-arg-info.ll
- test/SPIRVProducer/opaque_literal_sampler.ll
- test/SPIRVProducer/opaque_sample_image2d_float.ll
- test/Spv1p4/int_fetch.ll
- test/Spv1p4/int_read.ll
- test/Spv1p4/int_sample.ll
- test/Spv1p4/int_write.ll
- test/Spv1p4/interface_literal_sampler_in_helper.ll
- test/Spv1p4/interface_sampler.ll
- test/Spv1p4/opaque_structs.ll
- test/Spv1p4/uint_fetch.ll
- test/Spv1p4/uint_read.ll
- test/Spv1p4/uint_sample.ll
- test/Spv1p4/uint_write.ll
The spirv.Image target type no longer supports zeroinitializer value (See https://github.com/llvm/llvm-project/pull/73887)
Use undef instead.
Add a new clspv::GetDummyValue that returns the zeroinitializer value when it can, and otherwise returns the undef value.
> Update LLVM: avoid zeroinitializer for spirv.Image type

- lib/DirectResourceAccessPass.cpp
- lib/SPIRVProducerPass.cpp
Zero-init to avoid "maybe uninitialized" warnings
Mark variable as [[maybe_unused]] when only used in an assert
> Fix clang warnings

- lib/Types.cpp
- lib/ZeroInitializeAllocasPass.cpp
- include what you use.
- parameter names in function declaration should match the names in the function definition.
> Fix clang-tidy complaints

- lib/ThreeElementVectorLoweringPass.cpp
- test/ThreeElementVectorLowering/gep_of_gep_of_push_constant.ll
As we do not nower SPIR Gobal variable, do not lower any gep having a SPIR global variable as a parent recursively.
This will help avoid ending up on complicated pointer bitcast reworking in future PR.
> ThreeElementVectorLowering: do not lower gep of gep of spirv gv

- lib/BitcastUtils.cpp
- lib/BitcastUtils.h
- lib/LowerPrivatePointerPHIPass.cpp
- lib/ReplacePointerBitcastPass.cpp
- lib/SimplifyPointerBitcastPass.cpp
- test/PointerCasts/issue-1243.ll
- test/PointerCasts/simplify_gep_from_gep.ll
- test/PointerCasts/srcGTdst/load_cast_float2_to_float.ll
- test/PointerCasts/srcGTdst/load_cast_float2_to_int.ll
- test/PointerCasts/srcGTdst/load_cast_float4_to_float.ll
- test/PointerCasts/srcGTdst/load_cast_float4_to_int.ll
- test/PointerCasts/srcGTdst/store_cast_float2_to_char2_global_variable.ll
- test/PointerCasts/srcGTdst/store_cast_float2_to_float.ll
- test/PointerCasts/srcGTdst/store_cast_float2_to_int.ll
- test/PointerCasts/srcGTdst/store_cast_float4_to_float.ll
- test/PointerCasts/srcGTdst/store_cast_float4_to_int.ll
The most important part is the removal of the else condition is
runOnGEPFromGEP which was just assembling the 2 geps indices without
considering anything type-wise. Instead rework all those conditions to
have the else using ExtractOffsetFromGEP and GetIdxsForTyFromOffset
which contain a lot of logic to generate appropriate indices
considering the types in question.
Other changes are also needed to avoid regression in clspv tests and
in the OpenCL-CTS:
- Rework condition to avoid creating gep performing out-of-bound struct
access.
- Rework condition in GetIdxsForTyFromOffset to know when to force first
index to `0`.
- RunOnUnneededCasts is not needed anymore, and causes issues when not
removed.
Depends on https://github.com/google/clspv/pull/1281
> fix SimplifyPointerBitcastPass::runOnGEPFromGEP

- lib/SimplifyPointerBitcastPass.cpp
- lib/Types.cpp
- test/PointerCasts/phi-from-gep.ll
Refactor the part of InferType dealing with users type in a function.
For PHI Nodes, consider the type coming from the users, but also the
type from the incoming values.
The goal here is to end up with a reported type which is the bigger
one that all users and incoming values can easily bitcast to/from.
Previous implementation is leading to unsupported cases in pointer
bitcast passes for issue #1208 #1209 #1220 #1221 #1223
Depends on https://github.com/google/clspv/pull/1282
> change infer type for phi nodes: consider incoming values

- lib/BitcastUtils.cpp
- test/PointerCasts/store_local.ll
Both resource and local type start with array of zero element. Also fix the startIdx for those as the "empty" array will be removed by the rework of the type getting rid of it.
> fix GetIdxsForTyFromOffset with local type

- test/PointerAccessChains/pointer_index_is_constant_1.cl
The new code is correct.  The constant indexing into an array of arrays of floats collapses into a constant index of an array of floats.
Ref #1292
> Fix expectations for PointerAccessChains/pointer_index_is_constant_1.cl

- lib/UndoByvalPass.cpp
- test/issue-1228.cl
This change fixes #1228 by correctly copying over the metadata to any new calls generated as a result of undoing pass by val.
> Copy metadata for new call functions when undoing pass by val

- lib/SimplifyPointerBitcastPass.cpp
- test/PointerCasts/phi-from-gep.ll
Take phi incoming values into account to avoid creating an infinite loop try to both:
- fix gep from phi
- upgrading constant casts
> fix runOnUpgradeableConstantCasts

- lib/SimplifyPointerBitcastPass.cpp
- test/PointerCasts/phi-from-gep.ll
- test/kernel-no-i8-ptr.cl
The goal of this PR is to upgrade more gep to avoid having i8 types when it is not needed. This is currently impacting performances on ChromeOS. This PR is fixing those issues.
Phi can depend on phis, go through them recursively to find all the values needing to be upgraded to change the phi type.
On top of gep with constant indices, consider i8 gep which single indices can be upgraded looking at the `mul` and `shl` composing it.
> improve runOnUpgradeableConstantCasts

- lib/PushConstant.cpp
- test/PushConstant/no_8bit_storage_pod_args.cl
In this case, a couple of variables can be packed into one cell.
Example:
func(uchar2 a, char2 b)
> Fix PushConstant behavior for vectors with 1 byte types.

- lib/SimplifyPointerBitcastPass.cpp
- test/PointerCasts/issue-1318.ll
- test/PointerCasts/srcLTdst/srcelemLTdstelem/store_cast_char_to_float.ll
- test/PointerCasts/srcLTdst/srcelemLTdstelem/store_cast_short_to_float.ll
> clean unsused instruction to avoid fake pointer bitcast

- lib/SimplifyPointerBitcastPass.cpp
- test/PointerCasts/issue-1322.ll
If target is not reachable, still try to upgrade to type bigger than the actual type used by gep.
fixes #1322
> Always try to upgrade gep to avoid fragmenting

- deps.json
- lib/SPIRVProducerPass.cpp
* Prevent the SPIRVProducer from adding duplicate NonUniform decorations
https://github.com/KhronosGroup/SPIRV-Tools/pull/5641 added new validation.
> Update SPIRV-Headers and SPIRV-Tools

- lib/AnnotationToMetadataPass.cpp
A recent change to LLVM introduces pointer address space casts on the function pointer. 
Use `stripPointerCasts()` on the operand to make the `dyn_cast` work.
> Update AnnotationToMetadataPass to handle pointer casts in `llvm.global.annotations`

- lib/Builtins.cpp
- test/BuiltinsWithGenericPointer/issue-1343.cl
This tries to address #1343 
@rjodinchr should I also add a test?
> Use demangled name for BuiltinWithGenericPointer

- include/clspv/Option.h
- lib/Compiler.cpp
- lib/Option.cpp
- lib/SPIRVProducerPass.cpp
- test/CPlusPlus/cpp-2021.cl
* Allows `-cl-std=CLC++2021`
* Removes `missing-prototypes` warnings for C++ (any version)
* Removes `c++98-compat` warnings for CLC++2021
* Test
> Add option for CLC++2021

- lib/LowerAddrSpaceCastPass.cpp
- lib/LowerAddrSpaceCastPass.h
- test/AddressSpaceCast/issue-1341.ll
* Adds support for phi instructions in LowerAddrSpaceCast
* Adds code to remove dead phi instructions (overcomes the circular dependency)
* Adds test
Note that I have made the assumption that the first incoming value to the phi node will not depend on the phi node itself... I guess this could be improved in the future.
Closes #1341
> Support PHI in LowerAddrSpaceCastPass

- lib/SPIRVProducerPass.cpp
Drivers can use the stronger alignments to vectorize loads/stores.
> Always generate MemoryAccessAlignedMask (#1356)

- lib/ThreeElementVectorLoweringPass.cpp
- lib/ThreeElementVectorLoweringPass.h
- test/ThreeElementVectorLowering/invalid_vec3_gep.ll
- test/ThreeElementVectorLowering/invalid_vec3_gep2.ll
- test/ThreeElementVectorLowering/valid_vec3_gep.ll
If a gep ends up trying to access the 4th element of a vec3, we need to lower vec3 to vec4.
This is fixing a regression on CTS test_half
Ref https://github.com/kpet/clvk/pull/698
> fix detection to run ThreeElementVectorLoweringPass

- lib/LowerAddrSpaceCastPass.cpp
- test/AddressSpaceCast/issue-1364.ll
Adds logic to check for phi dependent operands
Figures out the phi type from non-dependent types
Test with dependent incoming value first
It also keeps the phi node valid if the incoming values have different address spaces by re-inserting some addrspacecasts. It will crash at the spirv producer but an additional pass could try and fix it up before then.
Closes #1364
> Improve handling of PHI in LowerAddrSpaceCast

- lib/Compiler.cpp
- test/vector_subgroup_broadcast.cl
This define is missing from clang OpenCLExtensions.def. 
Adding it manually if SPIRVVersion is 1.3 or later to be sure that GroupNonUniformBallot capability is supported.
> add cl_khr_subgroup_extended_types define

- lib/SPIRVProducerPass.cpp
- test/trunc_to_bool.ll
LLVM defines '%trunc = trunc i32 %2 to i1' as discarding the high bits of %2 prior to conversion, but the SPIRV-Producer pass was implementing it as '%2 != 0'. And away the high bits before doing the conversion.
Fixes #1379.
> Fix trunc to bool handling

- lib/SPIRVProducerPass.cpp
It will allow to avoid optimization of certain driver breaking the implementation of the libclc.
> add nocontraction decoration to conversions to floating point

- lib/PrintfPass.cpp
- lib/PrintfPass.h
- test/Printf/printf_ptr_to_char4_zero.ll
- test/Printf/printf_string_only_null.ll
Add tests:
- verify the new case
- verify we don't mess up pointer-to-zero-char4
Fixed: #1385
> printf: handle empty string, and string of only null

- lib/SPIRVOp.cpp
Fixed the bug #1400 that missing `OpLine` information for atomic instructions
> keep source-level location also for atomic instructions

- lib/SPIRVProducerPass.cpp
- test/correct_stride_int8_not_supported.ll
- test/correct_stride_int8_not_supported_char_arr.ll
please see issue #1396 for more details
> change stride to 4 instead of 1 if int8 is not supported

- lib/SPIRVProducerPass.cpp
Reported as `UndefinedBehaviorSanitizer: invalid-bool-load`
> Initialize HasIntegerDot

- deps.json
- lib/LongVectorLoweringPass.cpp
- lib/ReplaceLLVMIntrinsicsPass.cpp
- lib/ReplaceOpenCLBuiltinPass.cpp
- test/ProgramScopeConstants/in_storage_buffer_descriptor_map.cl
- test/UBO/transform_global.cl
Update LLVM
- Rename Intrinsic::getDeclaration to Intrinsic::getOrInsertDeclaration
- Update one test to avoid disabling int8
Bug: https://crbug.com/373696543
> rename Intrinsic::getDeclaration to Intrinsic::getOrInsertDeclaration

- lib/LongVectorLoweringPass.cpp
- test/PhysicalStorageBuffers/issue-1422.cl
When a lowered long-vector global is still in use, we cannot erase it. We need to check if a global variable is not in use before erasing it from parent.
Fix #1422
> fix LongVectorLoweringPass when removing dead long-vector globals that were lowered.

- CMakeLists.txt
When using CLSPV_LLVM_SOURCE_DIR we need to look for CMAKE_MODULE at the right place, not in 'third_party/llvm'.
> cmake: fix when using CLSPV_LLVM_SOURCE_DIR

- kokoro/scripts/linux/build-amber.sh
- kokoro/scripts/linux/build-clvk.sh
- kokoro/scripts/linux/build.sh
- kokoro/scripts/windows/build.bat
The Windows build VM now has Python 3.12, so use it from its path.
> Use cmake 3.31.2 on linux, win; Python 3.12 on windows

- lib/ReplaceOpenCLBuiltinPass.cpp
- test/mad-float-optimization.cl
make -cl-mad-enable or -cl-unsafe-math-optimisation required to lower mad to fma.
This avoid CTS failure on erf for Nvidia devices
> do not lower mad to fma when using only native fma

- lib/Types.cpp
- test/PointerCasts/phi-from-gep.ll
- test/PointerCasts/phi-uint-uint4.cl
When incoming values of phinode do not match the inferred type of the phi node from users, keep the smallest type to make sure types can be lowered.
This is fixing a bug found using tensorflow lite leading to an invalid SPIR-V code generated by clspv.
> fix infertype of phinode

- lib/FixupStructuredCFGPass.cpp
- lib/FixupStructuredCFGPass.h
- test/FixupStructuredCFG/split_convergent_continue_branch.ll
- test/FixupStructuredCFG/split_convergent_continue_cond_branch.ll
- test/loop_continue_no_selection_merge.cl
* Adds a new transform to FixupStructuredCFG to split a continue (latch) into two blocks under certain circumstances:
* The loop header is a conditional branch to the body and latch
* The latch has two predecessors
* The latch contains a convergent call
* This transformation prevents clspv forces (along with the breakConditionalHeader transform in the same pass) to prevent convergent operations from being placed in the loop continue contruct. Instead they end up as a structured selection in the body. This ensures reconvergence more robustly than previously. SPIRV-Cross, for example, inlines continues into the body under the assumption that reconvergence is not expected
> Split continues with convergent calls in some cases

- kokoro/check-format/continuous.cfg
- kokoro/check-format/presubmit.cfg
- kokoro/check-format/presubmit_check_format.cfg
- rename presubmit job config file. The fact it is for check-format is already in the directory name. Keep the old file until the Google-internal config file has been renamed.
- presubmit and continuous use the same build script
> kokoro: simplify check-format jobs

- kokoro/check-format/build-docker.sh
- kokoro/check-format/build_continuous.sh
- kokoro/check-format/continuous.cfg
- utils/check_code_format.sh
Avoid downloading all of LLVM and Clang source during check-format.
Instead, take clang-format-diff.py from the image.
Update ./utils/check_code_format.sh so it can use env vars:
- CLANG_FORMAT to find clang-format
- CLANG_FORMAT_DIFF to find clang-format-diff.py
Both of these are set in the Docker image.
BUG=397439901
> kokoro: check-format uses a streamlined formatter image

- lib/Compiler.cpp
- lib/PhysicalPointerArgsPass.cpp
- test/PhysicalStorageBuffers/physical_dead_const_global.cl
Move PhysicalPointerArgsPass before:
- AutoPodArgsPass
- DeclarePushConstantsPass
- DefineOpenCLWorkItemBuiltinsPass
Also call NormalizeGlobalVariables at end of
PhysicalPointerArgsPass to remove dead const globals.
Otherwise, subsequent PCs will see 8 byte offset
for a dead/removed module constant storage buffer.
> Fix/remove dead const globals for PhysicalStorageBuffers support

- lib/BitcastUtils.cpp
- lib/BitcastUtils.h
- lib/SimplifyPointerBitcastPass.cpp
- test/PointerCasts/issue-1473.cl
- test/PointerCasts/issue-1473.ll
This change marks all-constant-indice-global-GEPs via metadata tag as an indicator to avoid further transforms on subsequent sub-passes.
This fixes issue where SimplifyPointerBitcastPass endlessly loops on converting and reconverting these particular GEPs.
fixes: #1473
> Fix SimplifyPointerBitcastPass hang on const GEP GVs

- utils/check_code_format.sh
When doing the clang format check, the current branch is compared with main to see which files changed, and if there are any formating issues in those files. This can cause false positives if the current branch is too far behind main. If another PR fixed the formating in main, then that will be flagged as an error because it looks like the current PR will undo that change.
The fix is to use the merge-base for main and HEAD to find the first common ancestor of the two to determine which files are changed in the current branch.
Bug: crbug.com/414577655
> kokoro format-check: use merge-base to find files to scan

- lib/SimplifyPointerBitcastPass.cpp
As described in [issue 1487](https://github.com/google/clspv/issues/1487).
There was an issue in ```SimplifyPointerBitcast```, specifically ```runOnUpgradeableConstantCasts```, where dynamic indices would be lost for GEP operations on multi-dimensional arrays. This change resolves the issue by marking the GEP indices to not be upgradable when the number of indices != 1.
> Fix Dynamic Indexing in Multi-Dimensional Arrays

- lib/Compiler.cpp
- lib/FixupBuiltinsPass.cpp
On some machine, compilation tends to fail due to the pre-declared rsqrt on cmath.  
Namespace will be named `clspv_local` to avoid the declaration crash.  
Plus, Method will be static to avoid global declaration to avoid.
The change will look something like this.
```cc
/** Naming annonymous */
namespace clspv_local {
static double rsqrt(double input) { return 1.0 / sqrt(input); }
} // namespace
bool FixupBuiltinsPass::runOnFunction(Function &F) {
auto &FI = Builtins::Lookup(&F);
switch (FI.getType()) {
case Builtins::kSqrt:
return fixupSqrt(F, sqrt);
case Builtins::kRsqrt:
return fixupSqrt(F, clspv_local::rsqrt); /** Using rsqrt with namespace since rsqrt is not part of the regular cmath as I know. */
case Builtins::kReadImagef:
case Builtins::kReadImagei:
case Builtins::kReadImageui:
if …
```
> Fix trial of building failure on systems where function rsqrt is declared as cmath builtin (reopened)

- kokoro/windows-msvc-2019-release/common.cfg
- kokoro/windows-vs2022-amd64-debug/common.cfg
- kokoro/windows-vs2022-amd64-release/common.cfg
Revert this if we can drastically reduce build times again.
Bug: crbug.com/437080645
> kokoro: increase timeout for windows builds to 300 min

- lib/SimplifyPointerBitcastPass.cpp
- test/PointerCasts/gep_from_gep_struct.ll
- test/WorkItemBuiltins/get_global_id.ll
- test/WorkItemBuiltins/get_global_offset-spec-constant-non-constant-dim.ll
- test/WorkItemBuiltins/get_global_size.ll
- test/WorkItemBuiltins/get_group_id.ll
- test/WorkItemBuiltins/get_local_id.ll
- test/WorkItemBuiltins/get_num_groups.ll
- test/packed_struct_novec3.cl
Refs #1524
* Split the default case in runOnGEPFromGEP to handle struct based geps differently
This fixes the work item builtin CTS failures.
> Improve gep from gep bitcast handling
